// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

#ifndef _VTSS_MALIBU_REGS_H_
#define _VTSS_MALIBU_REGS_H_


#include "vtss_malibu_regs_line_pma.h"
#include "vtss_malibu_regs_line_kr_dev1.h"
#include "vtss_malibu_regs_sfp_tws.h"
#include "vtss_malibu_regs_gpio_intr_ctrl.h"
#include "vtss_malibu_regs_line_pma_32bit.h"
#include "vtss_malibu_regs_host_pma.h"
#include "vtss_malibu_regs_host_kr_dev1.h"
#include "vtss_malibu_regs_host_pma_32bit.h"
#include "vtss_malibu_regs_wis.h"
#include "vtss_malibu_regs_line_pcs10g.h"
#include "vtss_malibu_regs_host_pcs10g.h"
#include "vtss_malibu_regs_host_pcs1g.h"
#include "vtss_malibu_regs_line_pcs1g.h"
#include "vtss_malibu_regs_mac_fc_buffer.h"
#include "vtss_malibu_regs_host_mac.h"
#include "vtss_malibu_regs_line_mac.h"
#include "vtss_malibu_regs_fifo_bist.h"
#include "vtss_malibu_regs_line_kr_dev7.h"
#include "vtss_malibu_regs_host_kr_dev7.h"
#include "vtss_malibu_regs_macsec_ingr.h"
#include "vtss_malibu_regs_macsec_egr.h"
#include "vtss_malibu_regs_global.h"
#include "vtss_malibu_regs_clk_cfg.h"
#include "vtss_malibu_regs_global_reset.h"
#include "vtss_malibu_regs_host_pll5g.h"
#include "vtss_malibu_regs_line_pll5g.h"
#include "vtss_malibu_regs_ptp_0.h"
#include "vtss_malibu_regs_ptp_1.h"
#include "vtss_malibu_regs_ptp_ana0_ingr_cfg01.h"
#include "vtss_malibu_regs_ptp_ana0_egr_cfg01.h"
#include "vtss_malibu_regs_ptp_ana1_ingr_cfg01.h"
#include "vtss_malibu_regs_ptp_ana1_egr_cfg01.h"
#include "vtss_malibu_regs_ptp_ana2_ingr_cfg01.h"
#include "vtss_malibu_regs_ptp_ana2_egr_cfg01.h"
#include "vtss_malibu_regs_f2df_df2f_16bit.h"
#include "vtss_malibu_regs_f2df_df2f_32bit.h"
#include "vtss_malibu_regs_exp.h"
#include "vtss_malibu_regs_gpio_ctrl.h"
#include "vtss_malibu_regs_ptp_2.h"
#include "vtss_malibu_regs_ptp_3.h"
#include "vtss_malibu_regs_ptp_ana0_ingr_cfg23.h"
#include "vtss_malibu_regs_ptp_ana0_egr_cfg23.h"
#include "vtss_malibu_regs_ptp_ana1_ingr_cfg23.h"
#include "vtss_malibu_regs_ptp_ana1_egr_cfg23.h"
#include "vtss_malibu_regs_ptp_ana2_ingr_cfg23.h"
#include "vtss_malibu_regs_ptp_ana2_egr_cfg23.h"

#endif /* _VTSS_MALIBU_REGS_H_ */
