// Copyright (c) 2004-2021 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

/* Generation Tag is temp */

/* ================================================================= *
 *               Note: This code is autogenerated from the
 *                     Universal Tcl Environment (UTE) which provides
 *                     consistent setup functions for
 *       ^             - Verification
 *      / \            - Validation
 *     /   \           - Test Pattern Generation and
 *    /  |  \          - Software
 *   /   !   \         It should not be modified manually.
 *  /_________\
 * ================================================================= */

#ifndef _VTSS_MASERATI__API_SD6G40_H_UTE
#define _VTSS_MASERATI__API_SD6G40_H_UTE

#include <vtss/api/options.h>  // To get the ARCH define

vtss_rc vtss_maserati_sd6g40_setup_lane(vtss_state_t *vtss_state, const vtss_sd6g40_setup_args_t config, u32 idx);

#endif
