// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

/*
 * File         :   lan80XX_serdes_config.h
 * Version      :   1.4
 * Description  :   Lan80xx serdes configuration
 *
 */

/* ========================================================================== *
 *      Note    :   This file is autogenerated from SourceOfTruth.xls
 *                      Which provides consistent serdes preset values
 *                          - 25G
 *                          - 10G
 *                          - 1G
 *                  It should not be modified manually!!
 *
 * ========================================================================== */

/*******************************************************************************
 * Copyright (C) 2025 Microchip Technology Inc. and its subsidiaries.
 *
 * Subject to your compliance with these terms, you may use Microchip software
 * and any derivatives exclusively with Microchip products. It is your
 * responsibility to comply with third party license terms applicable to your
 * use of third party software (including open source software) that may
 * accompany Microchip software.
 *
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
 * PARTICULAR PURPOSE.
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
 * ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
 * THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *******************************************************************************/

#ifndef _LAN80XX_SERDES_CONFIG_H
#define _LAN80XX_SERDES_CONFIG_H

/******************* 25G_SPEED ***********************/
/***** PMA Common Configuration *****/
/* CMU_1A - Select Reg control */
#define LAN80XX_25G_R_DWIDTHCTRL_FROM_HWT               			(0x00)
#define LAN80XX_R_DWIDTHCTRL_FROM_HWT_POS               			(4)
#define LAN80XX_R_DWIDTHCTRL_FROM_HWT_MASK              			(0x0010)

/* CMU_1A - Select Reg control */
#define LAN80XX_25G_R_REG_MANUAL                        			(0x0001)
#define LAN80XX_R_REG_MANUAL_POS                        			(6)
#define LAN80XX_R_REG_MANUAL_MASK                       			(0x0040)

/* CMU_31 - By default Termination controlled by Pin H3/L3 . No impact by CMU_31 */
#define LAN80XX_25G_CFG_COMMON_RESERVE_7_0              			(0x01)
#define LAN80XX_CFG_COMMON_RESERVE_7_0_POS              			(0)
#define LAN80XX_CFG_COMMON_RESERVE_7_0_MASK             			(0x00ff)

/* CMU_09 - Use Internal regulator for VCO power */
#define LAN80XX_25G_CFG_EN_DUMMY                        			(0x00)
#define LAN80XX_CFG_EN_DUMMY_POS                        			(1)
#define LAN80XX_CFG_EN_DUMMY_MASK                       			(0x0002)

/* CMU_13 - Use Internal regulator for VCO power */
#define LAN80XX_25G_CFG_PLL_RESERVE_3_0                 			(0xF)
#define LAN80XX_CFG_PLL_RESERVE_3_0_POS                 			(0)
#define LAN80XX_CFG_PLL_RESERVE_3_0_MASK                			(0x000f)

/* CMU_40 - Internal use */
#define LAN80XX_25G_L0_CFG_TXCAL_EN                     			(0x00)
#define LAN80XX_L0_CFG_TXCAL_EN_POS                     			(3)
#define LAN80XX_L0_CFG_TXCAL_EN_MASK                    			(0x0008)

/* CMU_46 - Set something to 0x4CF0 */
#define LAN80XX_25G_L0_CFG_TX_RESERVE_15_8              			(0x4C)
#define LAN80XX_L0_CFG_TX_RESERVE_15_8_POS              			(0)
#define LAN80XX_L0_CFG_TX_RESERVE_15_8_MASK             			(0x00ff)

/* CMU_45 - Set something to 0x4CF0 */
#define LAN80XX_25G_L0_CFG_TX_RESERVE_7_0               			(0xF0)
#define LAN80XX_L0_CFG_TX_RESERVE_7_0_POS               			(0)
#define LAN80XX_L0_CFG_TX_RESERVE_7_0_MASK              			(0x00ff)

/* CMU_0B - Set VCO calibration to 0 */
#define LAN80XX_CFG_VCO_CAL_RESETN_POS                  			(3)
#define LAN80XX_CFG_VCO_CAL_RESETN_MASK                 			(0x0008)

/* CMU_19 - Internal use */
#define LAN80XX_R_CK_RESETB_POS                         			(0)
#define LAN80XX_R_CK_RESETB_MASK                        			(0x0001)

/* CMU_18 - Set reset signal to 0 for pll */
#define LAN80XX_R_PLL_RSTN_POS                          			(0)
#define LAN80XX_R_PLL_RSTN_MASK                         			(0x0001)

/* CMU_0C - Enable PLL Loss of Lock */
#define LAN80XX_25G_CFG_PLL_LOL_SET                     			(0x0001)
#define LAN80XX_CFG_PLL_LOL_SET_POS                     			(0)
#define LAN80XX_CFG_PLL_LOL_SET_MASK                    			(0x0001)

/* CMU_12 - Configure the VCO current tuning to 0x6 */
#define LAN80XX_25G_CFG_I_VCO_3_0                       			(0x6)
#define LAN80XX_CFG_I_VCO_3_0_POS                       			(0)
#define LAN80XX_CFG_I_VCO_3_0_MASK                      			(0x000f)

/* CMU_0F - Set PLL loop parameter tuning */
#define LAN80XX_25G_CFG_ICP_BASE_SEL_3_0                			(0x3)
#define LAN80XX_CFG_ICP_BASE_SEL_3_0_POS                			(4)
#define LAN80XX_CFG_ICP_BASE_SEL_3_0_MASK               			(0x00f0)

/* CMU_11 - Set PLL loop parameter tuning */
#define LAN80XX_25G_CFG_ICP_SEL_2_0                     			(0x3)
#define LAN80XX_CFG_ICP_SEL_2_0_POS                     			(0)
#define LAN80XX_CFG_ICP_SEL_2_0_MASK                    			(0x0007)

/* CMU_0F - Set PLL loop parameter tuning */
#define LAN80XX_25G_CFG_RSEL_2_0                        			(0x5)
#define LAN80XX_CFG_RSEL_2_0_POS                        			(0)
#define LAN80XX_CFG_RSEL_2_0_MASK                       			(0x0007)

/* CMU_1A - Data width from PMC to PMA to 40-bit */
#define LAN80XX_25G_R_DWIDTHCTRL_2_0                    			(0x4)
#define LAN80XX_R_DWIDTHCTRL_2_0_POS                    			(0)
#define LAN80XX_R_DWIDTHCTRL_2_0_MASK                   			(0x0007)

/* CMU_30 - Set the FIFOs on the TXFIFO to support 40-bit */
#define LAN80XX_25G_R_TXFIFO_CK_DIV_PMAD_2_0            			(0x0)
#define LAN80XX_R_TXFIFO_CK_DIV_PMAD_2_0_POS            			(0)
#define LAN80XX_R_TXFIFO_CK_DIV_PMAD_2_0_MASK           			(0x0007)

/* CMU_30 - Set the FIFOs on the RXFIFO to support 40-bit */
#define LAN80XX_25G_R_RXFIFO_CK_DIV_PMAD_2_0            			(0x0)
#define LAN80XX_R_RXFIFO_CK_DIV_PMAD_2_0_POS            			(4)
#define LAN80XX_R_RXFIFO_CK_DIV_PMAD_2_0_MASK           			(0x0070)

/* CMU_0C - VCO divider setting of 00, divide by 0 */
#define LAN80XX_25G_CFG_VCO_DIV_MODE_1_0                			(0x0)
#define LAN80XX_CFG_VCO_DIV_MODE_1_0_POS                			(4)
#define LAN80XX_CFG_VCO_DIV_MODE_1_0_MASK               			(0x0030)

/* CMU_0D - Reference clock divide set to 01 divide by 2 */
#define LAN80XX_25G_CFG_PRE_DIVSEL_1_0                  			(0x1)
#define LAN80XX_CFG_PRE_DIVSEL_1_0_POS                  			(4)
#define LAN80XX_CFG_PRE_DIVSEL_1_0_MASK                 			(0x0030)

/* CMU_0E - PLL multiplying factor(Divide by 330) */
#define LAN80XX_25G_CFG_SEL_DIV_3_0                     			(0xF)
#define LAN80XX_CFG_SEL_DIV_3_0_POS                     			(0)
#define LAN80XX_CFG_SEL_DIV_3_0_MASK                    			(0x000f)

/* CMU_1F - Internal Use */
#define LAN80XX_25G_R_MULTI_LANE_MODE                   			(0x00)
#define LAN80XX_R_MULTI_LANE_MODE_POS                   			(4)
#define LAN80XX_R_MULTI_LANE_MODE_MASK                  			(0x0010)

/* CMU_17 - Set LS3 loopback(MB25 H4/L4) enable to 0 */
#define LAN80XX_25G_R_LBSLV_IN_PMAD                     			(0x00)
#define LAN80XX_R_LBSLV_IN_PMAD_POS                     			(1)
#define LAN80XX_R_LBSLV_IN_PMAD_MASK                    			(0x0002)

/***** PMA Line Configuration *****/
/* LANE_0C - Configure the PMA Clock bitwidth to support 40-bit */
#define LAN80XX_25G_LN_CFG_PMA_TX_CK_BITWIDTH_2_0       			(0x3)
#define LAN80XX_LN_CFG_PMA_TX_CK_BITWIDTH_2_0_POS       			(0)
#define LAN80XX_LN_CFG_PMA_TX_CK_BITWIDTH_2_0_MASK      			(0x0007)

/* LANE_01 - Set the PCS to PMA tx subrate control to 0 */
#define LAN80XX_25G_LN_CFG_TX_PREDIV_1_0                			(0x0)
#define LAN80XX_LN_CFG_TX_PREDIV_1_0_POS                			(4)
#define LAN80XX_LN_CFG_TX_PREDIV_1_0_MASK               			(0x0030)

/* LANE_18 - Set the  value 0x3 for PMA RX clock frequency selection to support 40-bit data interface. */
#define LAN80XX_25G_LN_CFG_RXDIV_SEL_2_0                			(0x3)
#define LAN80XX_LN_CFG_RXDIV_SEL_2_0_POS                			(4)
#define LAN80XX_LN_CFG_RXDIV_SEL_2_0_MASK               			(0x0070)

/* LANE_2C - Set the Transmitter frequency subrate to support the full frequency */
#define LAN80XX_25G_LN_CFG_TX_SUBRATE_2_0               			(0x0)
#define LAN80XX_LN_CFG_TX_SUBRATE_2_0_POS               			(0)
#define LAN80XX_LN_CFG_TX_SUBRATE_2_0_MASK              			(0x0007)

/* LANE_28 - Set the receiver frequency subrate to support the full frequency */
#define LAN80XX_25G_LN_CFG_RX_SUBRATE_2_0               			(0x0)
#define LAN80XX_LN_CFG_RX_SUBRATE_2_0_POS               			(4)
#define LAN80XX_LN_CFG_RX_SUBRATE_2_0_MASK              			(0x0070)

/* LANE_18 - Set CDRCK_EN to 1 for normal mode.(need set it to 0 if  loopback mode is enabled) */
#define LAN80XX_25G_LN_CFG_CDRCK_EN                     			(0x0001)
#define LAN80XX_LN_CFG_CDRCK_EN_POS                     			(0)
#define LAN80XX_LN_CFG_CDRCK_EN_MASK                    			(0x0001)

/* LANE_0F - Enable 5 different DFE Taps? */
#define LAN80XX_25G_LN_CFG_DFETAP_EN_5_1                			(0x1F)
#define LAN80XX_LN_CFG_DFETAP_EN_5_1_POS                			(0)
#define LAN80XX_LN_CFG_DFETAP_EN_5_1_MASK               			(0x001f)

/* LANE_18 - Power up the error amplifier in the DFE (PD bit set to 0) */
#define LAN80XX_25G_LN_CFG_ERRAMP_PD                    			(0x00)
#define LAN80XX_LN_CFG_ERRAMP_PD_POS                    			(3)
#define LAN80XX_LN_CFG_ERRAMP_PD_MASK                   			(0x0008)

/* LANE_1D - Enable PI DFE block required to use the DFW(Internal use) */
#define LAN80XX_25G_LN_CFG_PI_DFE_EN                    			(0x0001)
#define LAN80XX_LN_CFG_PI_DFE_EN_POS                    			(5)
#define LAN80XX_LN_CFG_PI_DFE_EN_MASK                   			(0x0020)

/* LANE_19 - Clock and Data Recovery  Enhance Design Part Power Down control(Internal use) */
#define LAN80XX_25G_LN_CFG_ECDR_PD                      			(0x0001)
#define LAN80XX_LN_CFG_ECDR_PD_POS                      			(1)
#define LAN80XX_LN_CFG_ECDR_PD_MASK                     			(0x0002)

/* LANE_01 - TX margin setting */
#define LAN80XX_25G_LN_CFG_ITX_IPDRIVER_BASE_2_0        			(0x0001)
#define LAN80XX_LN_CFG_ITX_IPDRIVER_BASE_2_0_POS        			(0)
#define LAN80XX_LN_CFG_ITX_IPDRIVER_BASE_2_0_MASK       			(0x0007)

/* LANE_03 - Set the Tap Delay of the DFE to a value of 0x12 */
#define LAN80XX_25G_LN_CFG_TAP_DLY_4_0                  			(0x12)
#define LAN80XX_LN_CFG_TAP_DLY_4_0_POS                  			(0)
#define LAN80XX_LN_CFG_TAP_DLY_4_0_MASK                 			(0x001f)

/* LANE_06 - Set the Pre-equalization level control to 0x6 */
#define LAN80XX_25G_LN_CFG_TAP_ADV_3_0                  			(0x3)
#define LAN80XX_LN_CFG_TAP_ADV_3_0_POS                  			(4)
#define LAN80XX_LN_CFG_TAP_ADV_3_0_MASK                 			(0x00f0)

/* LANE_07 - Enable the pre-equalization settings */
#define LAN80XX_25G_LN_CFG_EN_ADV                       			(0x0001)
#define LAN80XX_LN_CFG_EN_ADV_POS                       			(0)
#define LAN80XX_LN_CFG_EN_ADV_MASK                      			(0x0001)

/* LANE_07 - Enable the 1st stage post-equaliztion control of the transmitter */
#define LAN80XX_25G_LN_CFG_EN_DLY                       			(0x0001)
#define LAN80XX_LN_CFG_EN_DLY_POS                       			(2)
#define LAN80XX_LN_CFG_EN_DLY_MASK                      			(0x0004)

/* LANE_0D - De-Multiplexor Power Down Control */
#define LAN80XX_25G_LN_CFG_DMUX_PD                      			(0x00)
#define LAN80XX_LN_CFG_DMUX_PD_POS                      			(6)
#define LAN80XX_LN_CFG_DMUX_PD_MASK                     			(0x0040)

/* LANE_04 - Power up the CML circuits by setting the PD bit to 0 */
#define LAN80XX_25G_LN_CFG_PD_CML                       			(0x00)
#define LAN80XX_LN_CFG_PD_CML_POS                       			(2)
#define LAN80XX_LN_CFG_PD_CML_MASK                      			(0x0004)

/* LANE_04 - Power up the TX Driver by setting the PD bit to 0 */
#define LAN80XX_25G_LN_CFG_PD_DRIVER                    			(0x00)
#define LAN80XX_LN_CFG_PD_DRIVER_POS                    			(4)
#define LAN80XX_LN_CFG_PD_DRIVER_MASK                   			(0x0010)

/* LANE_19 - Power up the Receiver regulator */
#define LAN80XX_25G_LN_CFG_RX_REG_PU                    			(0x0001)
#define LAN80XX_LN_CFG_RX_REG_PU_POS                    			(4)
#define LAN80XX_LN_CFG_RX_REG_PU_MASK                   			(0x0010)

/* LANE_19 - Power down the RMS Detect, this is the default value */
#define LAN80XX_25G_LN_CFG_PD_RMS_DET                   			(0x0001)
#define LAN80XX_LN_CFG_PD_RMS_DET_POS                   			(6)
#define LAN80XX_LN_CFG_PD_RMS_DET_MASK                  			(0x0040)

/* LANE_19 - Clock and Data Recovery Main Design Circuit Power Down control(Internal use) */
#define LAN80XX_25G_LN_CFG_DCDR_PD                      			(0x00)
#define LAN80XX_LN_CFG_DCDR_PD_POS                      			(0)
#define LAN80XX_LN_CFG_DCDR_PD_MASK                     			(0x0001)

/* LANE_2E - Squelch Circuit Power Down Control(Internal use) */
#define LAN80XX_LN_CFG_PD_SQ_POS                        			(2)
#define LAN80XX_LN_CFG_PD_SQ_MASK                       			(0x0004)

/* LANE_04 - Enable the TX data path by setting to 1 */
#define LAN80XX_25G_LN_CFG_TAP_MAIN                     			(0x0001)
#define LAN80XX_LN_CFG_TAP_MAIN_POS                     			(5)
#define LAN80XX_LN_CFG_TAP_MAIN_MASK                    			(0x0020)

/* LANE_06 - Enable the TX data path control */
#define LAN80XX_25G_LN_CFG_EN_MAIN                      			(0x0001)
#define LAN80XX_LN_CFG_EN_MAIN_POS                      			(0)
#define LAN80XX_LN_CFG_EN_MAIN_MASK                     			(0x0001)

/* LANE_0E - Disable eye scan feature by setting EN to 0 */
#define LAN80XX_25G_LN_CFG_ISCAN_EN                     			(0x00)
#define LAN80XX_LN_CFG_ISCAN_EN_POS                     			(0)
#define LAN80XX_LN_CFG_ISCAN_EN_MASK                    			(0x0001)

/* LANE_2E - Disable fast eye scan feature by setting EN to 0 */
#define LAN80XX_25G_LN_CFG_EN_FAST_ISCAN                			(0x00)
#define LAN80XX_LN_CFG_EN_FAST_ISCAN_POS                			(0)
#define LAN80XX_LN_CFG_EN_FAST_ISCAN_MASK               			(0x0001)

/* LANE_0D - DFE Related Clock set to enable */
#define LAN80XX_25G_LN_CFG_DFECK_EN                     			(0x0001)
#define LAN80XX_LN_CFG_DFECK_EN_POS                     			(7)
#define LAN80XX_LN_CFG_DFECK_EN_MASK                    			(0x0080)

/* LANE_1C - Power up the DFE Analog Circuits (set PD bit to 0) */
#define LAN80XX_25G_LN_CFG_DFE_PD                       			(0x00)
#define LAN80XX_LN_CFG_DFE_PD_POS                       			(1)
#define LAN80XX_LN_CFG_DFE_PD_MASK                      			(0x0002)

/* LANE_0E - Digital MUX Clock Power Down Control by setting  to 0(Internal use) */
#define LAN80XX_25G_LN_CFG_DMUX_CLK_PD                  			(0x00)
#define LAN80XX_LN_CFG_DMUX_CLK_PD_POS                  			(1)
#define LAN80XX_LN_CFG_DMUX_CLK_PD_MASK                 			(0x0002)

/* LANE_23 - Enable PI (PI Filter) (Internal use) */
#define LAN80XX_25G_LN_CFG_PI_EN                        			(0x0001)
#define LAN80XX_LN_CFG_PI_EN_POS                        			(0)
#define LAN80XX_LN_CFG_PI_EN_MASK                       			(0x0001)

/* LANE_19 - Power up the CTLE by setting the PD bit to 0 */
#define LAN80XX_25G_LN_CFG_PD_CTLE                      			(0x00)
#define LAN80XX_LN_CFG_PD_CTLE_POS                      			(7)
#define LAN80XX_LN_CFG_PD_CTLE_MASK                     			(0x0080)

/* LANE_0D - Enable the summer */
#define LAN80XX_25G_LN_CFG_SUMMER_EN                    			(0x0001)
#define LAN80XX_LN_CFG_SUMMER_EN_POS                    			(5)
#define LAN80XX_LN_CFG_SUMMER_EN_MASK                   			(0x0020)

/* LANE_1E - PMA Digital clock function PD bit to 0 */
#define LAN80XX_25G_LN_CFG_PMAD_CK_PD                   			(0x00)
#define LAN80XX_LN_CFG_PMAD_CK_PD_POS                   			(7)
#define LAN80XX_LN_CFG_PMAD_CK_PD_MASK                  			(0x0080)

/* LANE_04 - Power Down clock circuits bit to 0 */
#define LAN80XX_25G_LN_CFG_PD_CLK                       			(0x00)
#define LAN80XX_LN_CFG_PD_CLK_POS                       			(3)
#define LAN80XX_LN_CFG_PD_CLK_MASK                      			(0x0008)

/* LANE_29 - Set 2nd order CDR setting */
#define LAN80XX_25G_LN_CFG_FILTER2ND_YZ_6_0             			(0x3F)
#define LAN80XX_LN_CFG_FILTER2ND_YZ_6_0_POS             			(0)
#define LAN80XX_LN_CFG_FILTER2ND_YZ_6_0_MASK            			(0x00ff)

/* LANE_43 - TX Speed Change Registers(Internal use) */
#define LAN80XX_25G_LN_CFG_TX_RESERVE_15_8              			(0xCC)
#define LAN80XX_LN_CFG_TX_RESERVE_15_8_POS              			(0)
#define LAN80XX_LN_CFG_TX_RESERVE_15_8_MASK             			(0x00ff)

/* LANE_42 - TX Speed Change Registers(Internal use) */
#define LAN80XX_25G_LN_CFG_TX_RESERVE_7_0               			(0xFE)
#define LAN80XX_LN_CFG_TX_RESERVE_7_0_POS               			(0)
#define LAN80XX_LN_CFG_TX_RESERVE_7_0_MASK              			(0x00ff)

/* LANE_05 - TX Speed BW configured to 0x3 for 25G (Internal use) */
#define LAN80XX_25G_LN_CFG_BW_1_0                       			(0x3)
#define LAN80XX_LN_CFG_BW_1_0_POS                       			(4)
#define LAN80XX_LN_CFG_BW_1_0_MASK                      			(0x0030)

/* LANE_0B - Enable manual TX Calibration */
#define LAN80XX_25G_LN_CFG_TXCAL_MAN_EN                 			(0x0001)
#define LAN80XX_LN_CFG_TXCAL_MAN_EN_POS                 			(0)
#define LAN80XX_LN_CFG_TXCAL_MAN_EN_MASK                			(0x0001)

/* LANE_0A - Set the TX Calibration shift code to 0x02 */
#define LAN80XX_25G_LN_CFG_TXCAL_SHIFT_CODE_5_0         			(0x02)
#define LAN80XX_LN_CFG_TXCAL_SHIFT_CODE_5_0_POS         			(0)
#define LAN80XX_LN_CFG_TXCAL_SHIFT_CODE_5_0_MASK        			(0x003f)

/* LANE_09 - Set the TX Calbration Valid Sel variable to 0x4 */
#define LAN80XX_25G_LN_CFG_TXCAL_VALID_SEL_3_0          			(0x4)
#define LAN80XX_LN_CFG_TXCAL_VALID_SEL_3_0_POS          			(0)
#define LAN80XX_LN_CFG_TXCAL_VALID_SEL_3_0_MASK         			(0x000f)

/* LANE_1A - CDR Block  (internal use) */
#define LAN80XX_25G_LN_CFG_CDR_KF_2_0                   			(0x1)
#define LAN80XX_LN_CFG_CDR_KF_2_0_POS                   			(4)
#define LAN80XX_LN_CFG_CDR_KF_2_0_MASK                  			(0x0070)

/* LANE_1B - Set the Clock Data Recovery bandwidth settings to 0x04 */
#define LAN80XX_25G_LN_CFG_CDR_M_7_0                    			(0x04)
#define LAN80XX_LN_CFG_CDR_M_7_0_POS                    			(0)
#define LAN80XX_LN_CFG_CDR_M_7_0_MASK                   			(0x00ff)

/* LANE_2B - Set the Phase Interpolator badwidth setting to 0x00, data rate dependent */
#define LAN80XX_25G_LN_CFG_PI_BW_3_0                    			(0x0)
#define LAN80XX_LN_CFG_PI_BW_3_0_POS                    			(0)
#define LAN80XX_LN_CFG_PI_BW_3_0_MASK                   			(0x000f)

/* LANE_2C - Enable 2nd Order CDR (DIS bit set to 1) */
#define LAN80XX_25G_LN_CFG_DIS_2NDORDER                 			(0x00)
#define LAN80XX_LN_CFG_DIS_2NDORDER_POS                 			(4)
#define LAN80XX_LN_CFG_DIS_2NDORDER_MASK                			(0x0010)

/* LANE_2E - Continuous-Time Linear Equalizer reset */
#define LAN80XX_25G_LN_CFG_CTLE_RSTN                    			(0x0001)
#define LAN80XX_LN_CFG_CTLE_RSTN_POS                    			(7)
#define LAN80XX_LN_CFG_CTLE_RSTN_MASK                   			(0x0080)

/* LANE_44 - EMS_PHY CDR Register Settings for 25G */
#define LAN80XX_25G_LN_CFG_RX_RESERVE_7_0               			(0xBF)
#define LAN80XX_LN_CFG_RX_RESERVE_7_0_POS               			(0)
#define LAN80XX_LN_CFG_RX_RESERVE_7_0_MASK              			(0x00ff)

/* LANE_45 - EMS_PHY CDR Register Settings for 25G */
#define LAN80XX_25G_LN_CFG_RX_RESERVE_15_8              			(0x61)
#define LAN80XX_LN_CFG_RX_RESERVE_15_8_POS              			(0)
#define LAN80XX_LN_CFG_RX_RESERVE_15_8_MASK             			(0x00ff)

/* LANE_0D - Configure RX terminations for 25G(Internal use) */
#define LAN80XX_25G_LN_CFG_RXTERM_2_0                   			(0x0)
#define LAN80XX_LN_CFG_RXTERM_2_0_POS                   			(0)
#define LAN80XX_LN_CFG_RXTERM_2_0_MASK                  			(0x0007)

/* LANE_21 - Variable Gain Control Code bypass */
#define LAN80XX_25G_LN_CFG_VGA_CTRL_BYP_4_0             			(0xF)
#define LAN80XX_LN_CFG_VGA_CTRL_BYP_4_0_POS             			(0)
#define LAN80XX_LN_CFG_VGA_CTRL_BYP_4_0_MASK            			(0x001f)

/* LANE_22 - CTLE ResistorManual Control mode */
#define LAN80XX_25G_LN_CFG_EQR_FORCE_3_0                			(0xB)
#define LAN80XX_LN_CFG_EQR_FORCE_3_0_POS                			(0)
#define LAN80XX_LN_CFG_EQR_FORCE_3_0_MASK               			(0x000f)

/* LANE_1C - CTLE Capacitor Manual Control mode */
#define LAN80XX_25G_LN_CFG_EQC_FORCE_3_0                			(0x0)
#define LAN80XX_LN_CFG_EQC_FORCE_3_0_POS                			(4)
#define LAN80XX_LN_CFG_EQC_FORCE_3_0_MASK               			(0x00f0)

/* LANE_1E - Enable the sum setcm in the RX Equalizer (Internal use) */
#define LAN80XX_25G_LN_CFG_SUM_SETCM_EN                 			(0x0001)
#define LAN80XX_LN_CFG_SUM_SETCM_EN_POS                 			(5)
#define LAN80XX_LN_CFG_SUM_SETCM_EN_MASK                			(0x0020)

/* LANE_25 -  Set the RX Equalizer Initial position of ISCAN to 0x06(Internal use) */
#define LAN80XX_25G_LN_CFG_INIT_POS_ISCAN_6_0           			(0x06)
#define LAN80XX_LN_CFG_INIT_POS_ISCAN_6_0_POS           			(0)
#define LAN80XX_LN_CFG_INIT_POS_ISCAN_6_0_MASK          			(0x007f)

/* LANE_26 - Set the RX Equalizer Initial position of iPI to 0x09 (Internal use) */
#define LAN80XX_25G_LN_CFG_INIT_POS_IPI_6_0             			(0x09)
#define LAN80XX_LN_CFG_INIT_POS_IPI_6_0_POS             			(0)
#define LAN80XX_LN_CFG_INIT_POS_IPI_6_0_MASK            			(0x007f)

/* LANE_0E -  Set DFEDIG M Time Constant for DFE adaptation to 0x6 */
#define LAN80XX_25G_LN_CFG_DFEDIG_M_2_0                 			(0x6)
#define LAN80XX_LN_CFG_DFEDIG_M_2_0_POS                 			(4)
#define LAN80XX_LN_CFG_DFEDIG_M_2_0_MASK                			(0x0070)

/* LANE_0E - Enable DFE digital adaptation in the RX Equalizer by setting the EN bit to 1 */
#define LAN80XX_25G_LN_CFG_EN_DFEDIG                    			(0x0001)
#define LAN80XX_LN_CFG_EN_DFEDIG_POS                    			(2)
#define LAN80XX_LN_CFG_EN_DFEDIG_MASK                   			(0x0004)

/* LANE_40 - System Specific, disable TX polarity inversion */
#define LAN80XX_25G_LN_R_TX_POL_INV                     			(0x00)
#define LAN80XX_LN_R_TX_POL_INV_POS                     			(1)
#define LAN80XX_LN_R_TX_POL_INV_MASK                    			(0x0002)

/* LANE_40 - System Specific, enable RX polarity inversion */
#define LAN80XX_25G_LN_R_RX_POL_INV                     			(0x0001)
#define LAN80XX_LN_R_RX_POL_INV_POS                     			(3)
#define LAN80XX_LN_R_RX_POL_INV_MASK                    			(0x0008)

/* LANE_04 - Disable H1/L1 Loopback */
#define LAN80XX_25G_LN_CFG_RX2TX_LP_EN                  			(0x00)
#define LAN80XX_LN_CFG_RX2TX_LP_EN_POS                  			(1)
#define LAN80XX_LN_CFG_RX2TX_LP_EN_MASK                 			(0x0002)

/* LANE_04 - Disable H1/L1 Loopback */
#define LAN80XX_25G_LN_CFG_TX2RX_LP_EN                  			(0x00)
#define LAN80XX_LN_CFG_TX2RX_LP_EN_POS                  			(0)
#define LAN80XX_LN_CFG_TX2RX_LP_EN_MASK                 			(0x0001)

/* LANE_1E - Disable H6/L6 and H5/L5 Receiver Loopback */
#define LAN80XX_25G_LN_CFG_RXLB_EN                      			(0x00)
#define LAN80XX_LN_CFG_RXLB_EN_POS                      			(4)
#define LAN80XX_LN_CFG_RXLB_EN_MASK                     			(0x0010)

/* LANE_19 - Disable H6/L6 and H5/L5 Transmitter Loopback */
#define LAN80XX_25G_LN_CFG_TXLB_EN                      			(0x00)
#define LAN80XX_LN_CFG_TXLB_EN_POS                      			(3)
#define LAN80XX_LN_CFG_TXLB_EN_MASK                     			(0x0008)

/***** SERDES LOS Enable *****/
/* LANE_2D - ALOS Threshold adjustment */
#define LAN80XX_25G_LN_CFG_ALOS_THR_2_0                 			(0x0)
#define LAN80XX_LN_CFG_ALOS_THR_2_0_POS                 			(0)
#define LAN80XX_LN_CFG_ALOS_THR_2_0_MASK                			(0x0007)

/* LANE_3F - ALOS enable */
#define LAN80XX_25G_LN_R_ALOS_EN                        			(0x0001)
#define LAN80XX_LN_R_ALOS_EN_POS                        			(4)
#define LAN80XX_LN_R_ALOS_EN_MASK                       			(0x0010)

/* LANE_2E - SQulelth Enabled */
#define LAN80XX_25G_LN_CFG_DIS_SQ                       			(0x00)
#define LAN80XX_LN_CFG_DIS_SQ_POS                       			(1)
#define LAN80XX_LN_CFG_DIS_SQ_MASK                      			(0x0002)

/* SERDES_LOS - SD25 LOS Enabled */
#define LAN80XX_25G_SD25G_LOS_EN                        			(0x0001)
#define LAN80XX_SD25G_LOS_EN_POS                        			(4)
#define LAN80XX_SD25G_LOS_EN_MASK                       			(0x0010)

/* SERDES_LOS - SD25 LOS : No invertion */
#define LAN80XX_25G_SD25G_LOS_INV                       			(0x00)
#define LAN80XX_SD25G_LOS_INV_POS                       			(5)
#define LAN80XX_SD25G_LOS_INV_MASK                      			(0x0020)

/* SERDES_LOS - Module LOS Disabled */
#define LAN80XX_25G_MOD_LOS_EN                          			(0x00)
#define LAN80XX_MOD_LOS_EN_POS                          			(6)
#define LAN80XX_MOD_LOS_EN_MASK                         			(0x0040)

/* SERDES_LOS - Module  LOS : No invertion */
#define LAN80XX_25G_MOD_LOS_INV                         			(0x00)
#define LAN80XX_MOD_LOS_INV_POS                         			(7)
#define LAN80XX_MOD_LOS_INV_MASK                        			(0x0080)

/***** These functions are not part of the 25G SerDes configuration, but needed to execute this test stand alone *****/
/******************* 10G_SPEED ***********************/
/***** PMA Common Configuration *****/
/* CMU_1A - Select Reg control */
#define LAN80XX_10G_R_DWIDTHCTRL_FROM_HWT               			(0x0)

/* CMU_1A - Select Reg control */
#define LAN80XX_10G_R_REG_MANUAL                        			(0x1)

/* CMU_31 - By default Termination controlled by Pin H3/L3 . No impact by CMU_31 */
#define LAN80XX_10G_CFG_COMMON_RESERVE_7_0              			(0x1)

/* CMU_09 - Use Internal regulator for VCO power */
#define LAN80XX_10G_CFG_EN_DUMMY                        			(0x0)

/* CMU_13 - Use Internal regulator for VCO power */
#define LAN80XX_10G_CFG_PLL_RESERVE_3_0                 			(0xf)

/* CMU_40 - Internal use */
#define LAN80XX_10G_L0_CFG_TXCAL_EN                     			(0x1)

/* CMU_46 - Set something to 0x4CF0 */
#define LAN80XX_10G_L0_CFG_TX_RESERVE_15_8              			(0x40)

/* CMU_45 - Set something to 0x4CF0 */
#define LAN80XX_10G_L0_CFG_TX_RESERVE_7_0               			(0x40)

/* CMU_0C - Enable PLL Loss of Lock */
#define LAN80XX_10G_CFG_PLL_LOL_SET                     			(0x1)

/* CMU_12 - Configure the VCO current tuning to 0x6 */
#define LAN80XX_10G_CFG_I_VCO_3_0                       			(0x6)

/* CMU_0F - Set PLL loop parameter tuning */
#define LAN80XX_10G_CFG_ICP_BASE_SEL_3_0                			(0x3)

/* CMU_11 - Set PLL loop parameter tuning */
#define LAN80XX_10G_CFG_ICP_SEL_2_0                     			(0x3)

/* CMU_0F - Set PLL loop parameter tuning */
#define LAN80XX_10G_CFG_RSEL_2_0                        			(0x6)

/* CMU_1A - Data width from PMC to PMA to 40-bit */
#define LAN80XX_10G_R_DWIDTHCTRL_2_0                    			(0x4)

/* CMU_30 - Set the FIFOs on the TXFIFO to support 40-bit */
#define LAN80XX_10G_R_TXFIFO_CK_DIV_PMAD_2_0            			(0x0)

/* CMU_30 - Set the FIFOs on the RXFIFO to support 40-bit */
#define LAN80XX_10G_R_RXFIFO_CK_DIV_PMAD_2_0            			(0x0)

/* CMU_0C - VCO divider setting of 00, divide by 0 */
#define LAN80XX_10G_CFG_VCO_DIV_MODE_1_0                			(0x1)

/* CMU_0D - Reference clock divide set to 01 divide by 2 */
#define LAN80XX_10G_CFG_PRE_DIVSEL_1_0                  			(0x0)

/* CMU_0E - PLL multiplying factor(Divide by 330) */
#define LAN80XX_10G_CFG_SEL_DIV_3_0                     			(0x9)

/* CMU_1F - Internal Use */
#define LAN80XX_10G_R_MULTI_LANE_MODE                   			(0x0)

/* CMU_17 - Set LS3 loopback(MB25 H4/L4) enable to 0 */
#define LAN80XX_10G_R_LBSLV_IN_PMAD                     			(0x0)

/***** PMA Line Configuration *****/
/* LANE_0C - Configure the PMA Clock bitwidth to support 40-bit */
#define LAN80XX_10G_LN_CFG_PMA_TX_CK_BITWIDTH_2_0       			(0x3)

/* LANE_01 - Set the PCS to PMA tx subrate control to 0 */
#define LAN80XX_10G_LN_CFG_TX_PREDIV_1_0                			(0x0)

/* LANE_18 - Set the  value 0x3 for PMA RX clock frequency selection to support 40-bit data interface. */
#define LAN80XX_10G_LN_CFG_RXDIV_SEL_2_0                			(0x3)

/* LANE_2C - Set the Transmitter frequency subrate to support the full frequency */
#define LAN80XX_10G_LN_CFG_TX_SUBRATE_2_0               			(0x0)

/* LANE_28 - Set the receiver frequency subrate to support the full frequency */
#define LAN80XX_10G_LN_CFG_RX_SUBRATE_2_0               			(0x0)

/* LANE_18 - Set CDRCK_EN to 1 for normal mode.(need set it to 0 if  loopback mode is enabled) */
#define LAN80XX_10G_LN_CFG_CDRCK_EN                     			(0x1)

/* LANE_0F - Enable 5 different DFE Taps? */
#define LAN80XX_10G_LN_CFG_DFETAP_EN_5_1                			(0x0)

/* LANE_18 - Power up the error amplifier in the DFE (PD bit set to 0) */
#define LAN80XX_10G_LN_CFG_ERRAMP_PD                    			(0x1)

/* LANE_1D - Enable PI DFE block required to use the DFW(Internal use) */
#define LAN80XX_10G_LN_CFG_PI_DFE_EN                    			(0x1)

/* LANE_19 - Clock and Data Recovery  Enhance Design Part Power Down control(Internal use) */
#define LAN80XX_10G_LN_CFG_ECDR_PD                      			(0x1)

/* LANE_01 - TX margin setting */
#define LAN80XX_10G_LN_CFG_ITX_IPDRIVER_BASE_2_0        			(0x0)

/* LANE_03 - Set the Tap Delay of the DFE to a value of 0x12 */
#define LAN80XX_10G_LN_CFG_TAP_DLY_4_0                  			(0x7)

/* LANE_06 - Set the Pre-equalization level control to 0x6 */
#define LAN80XX_10G_LN_CFG_TAP_ADV_3_0                  			(0x0)

/* LANE_07 - Enable the pre-equalization settings */
#define LAN80XX_10G_LN_CFG_EN_ADV                       			(0x1)

/* LANE_07 - Enable the 1st stage post-equaliztion control of the transmitter */
#define LAN80XX_10G_LN_CFG_EN_DLY                       			(0x1)

/* LANE_0D - De-Multiplexor Power Down Control */
#define LAN80XX_10G_LN_CFG_DMUX_PD                      			(0x0)

/* LANE_04 - Power up the CML circuits by setting the PD bit to 0 */
#define LAN80XX_10G_LN_CFG_PD_CML                       			(0x0)

/* LANE_04 - Power up the TX Driver by setting the PD bit to 0 */
#define LAN80XX_10G_LN_CFG_PD_DRIVER                    			(0x0)

/* LANE_19 - Power up the Receiver regulator */
#define LAN80XX_10G_LN_CFG_RX_REG_PU                    			(0x1)

/* LANE_19 - Power down the RMS Detect, this is the default value */
#define LAN80XX_10G_LN_CFG_PD_RMS_DET                   			(0x1)

/* LANE_19 - Clock and Data Recovery Main Design Circuit Power Down control(Internal use) */
#define LAN80XX_10G_LN_CFG_DCDR_PD                      			(0x0)

/* LANE_04 - Enable the TX data path by setting to 1 */
#define LAN80XX_10G_LN_CFG_TAP_MAIN                     			(0x1)

/* LANE_06 - Enable the TX data path control */
#define LAN80XX_10G_LN_CFG_EN_MAIN                      			(0x1)

/* LANE_0E - Disable eye scan feature by setting EN to 0 */
#define LAN80XX_10G_LN_CFG_ISCAN_EN                     			(0x0)

/* LANE_2E - Disable fast eye scan feature by setting EN to 0 */
#define LAN80XX_10G_LN_CFG_EN_FAST_ISCAN                			(0x0)

/* LANE_0D - DFE Related Clock set to enable */
#define LAN80XX_10G_LN_CFG_DFECK_EN                     			(0x0)

/* LANE_1C - Power up the DFE Analog Circuits (set PD bit to 0) */
#define LAN80XX_10G_LN_CFG_DFE_PD                       			(0x1)

/* LANE_0E - Digital MUX Clock Power Down Control by setting  to 0(Internal use) */
#define LAN80XX_10G_LN_CFG_DMUX_CLK_PD                  			(0x0)

/* LANE_23 - Enable PI (PI Filter) (Internal use) */
#define LAN80XX_10G_LN_CFG_PI_EN                        			(0x1)

/* LANE_19 - Power up the CTLE by setting the PD bit to 0 */
#define LAN80XX_10G_LN_CFG_PD_CTLE                      			(0x0)

/* LANE_0D - Enable the summer */
#define LAN80XX_10G_LN_CFG_SUMMER_EN                    			(0x1)

/* LANE_1E - PMA Digital clock function PD bit to 0 */
#define LAN80XX_10G_LN_CFG_PMAD_CK_PD                   			(0x0)

/* LANE_04 - Power Down clock circuits bit to 0 */
#define LAN80XX_10G_LN_CFG_PD_CLK                       			(0x0)

/* LANE_29 - Set 2nd order CDR setting */
#define LAN80XX_10G_LN_CFG_FILTER2ND_YZ_6_0             			(0x3f)

/* LANE_43 - TX Speed Change Registers(Internal use) */
#define LAN80XX_10G_LN_CFG_TX_RESERVE_15_8              			(0x4c)

/* LANE_42 - TX Speed Change Registers(Internal use) */
#define LAN80XX_10G_LN_CFG_TX_RESERVE_7_0               			(0x44)

/* LANE_05 - TX Speed BW configured to 0x3 for 25G (Internal use) */
#define LAN80XX_10G_LN_CFG_BW_1_0                       			(0x3)

/* LANE_0B - Enable manual TX Calibration */
#define LAN80XX_10G_LN_CFG_TXCAL_MAN_EN                 			(0x1)

/* LANE_0A - Set the TX Calibration shift code to 0x02 */
#define LAN80XX_10G_LN_CFG_TXCAL_SHIFT_CODE_5_0         			(0x2)

/* LANE_09 - Set the TX Calbration Valid Sel variable to 0x4 */
#define LAN80XX_10G_LN_CFG_TXCAL_VALID_SEL_3_0          			(0x4)

/* LANE_1A - CDR Block  (internal use) */
#define LAN80XX_10G_LN_CFG_CDR_KF_2_0                   			(0x1)

/* LANE_1B - Set the Clock Data Recovery bandwidth settings to 0x04 */
#define LAN80XX_10G_LN_CFG_CDR_M_7_0                    			(0x2)

/* LANE_2B - Set the Phase Interpolator badwidth setting to 0x00, data rate dependent */
#define LAN80XX_10G_LN_CFG_PI_BW_3_0                    			(0x0)

/* LANE_2C - Enable 2nd Order CDR (DIS bit set to 1) */
#define LAN80XX_10G_LN_CFG_DIS_2NDORDER                 			(0x0)

/* LANE_2E - Continuous-Time Linear Equalizer reset */
#define LAN80XX_10G_LN_CFG_CTLE_RSTN                    			(0x1)

/* LANE_44 - EMS_PHY CDR Register Settings for 25G */
#define LAN80XX_10G_LN_CFG_RX_RESERVE_7_0               			(0xbf)

/* LANE_45 - EMS_PHY CDR Register Settings for 25G */
#define LAN80XX_10G_LN_CFG_RX_RESERVE_15_8              			(0x61)

/* LANE_0D - Configure RX terminations for 25G(Internal use) */
#define LAN80XX_10G_LN_CFG_RXTERM_2_0                   			(0x3)

/* LANE_21 - Variable Gain Control Code bypass */
#define LAN80XX_10G_LN_CFG_VGA_CTRL_BYP_4_0             			(0x8)

/* LANE_22 - CTLE ResistorManual Control mode */
#define LAN80XX_10G_LN_CFG_EQR_FORCE_3_0                			(0x4)

/* LANE_1C - CTLE Capacitor Manual Control mode */
#define LAN80XX_10G_LN_CFG_EQC_FORCE_3_0                			(0xf)

/* LANE_1E - Enable the sum setcm in the RX Equalizer (Internal use) */
#define LAN80XX_10G_LN_CFG_SUM_SETCM_EN                 			(0x1)

/* LANE_25 -  Set the RX Equalizer Initial position of ISCAN to 0x06(Internal use) */
#define LAN80XX_10G_LN_CFG_INIT_POS_ISCAN_6_0           			(0x6)

/* LANE_26 - Set the RX Equalizer Initial position of iPI to 0x09 (Internal use) */
#define LAN80XX_10G_LN_CFG_INIT_POS_IPI_6_0             			(0x9)

/* LANE_0E -  Set DFEDIG M Time Constant for DFE adaptation to 0x6 */
#define LAN80XX_10G_LN_CFG_DFEDIG_M_2_0                 			(0x6)

/* LANE_0E - Enable DFE digital adaptation in the RX Equalizer by setting the EN bit to 1 */
#define LAN80XX_10G_LN_CFG_EN_DFEDIG                    			(0x0)

/* LANE_40 - System Specific, disable TX polarity inversion */
#define LAN80XX_10G_LN_R_TX_POL_INV                     			(0x0)

/* LANE_40 - System Specific, enable RX polarity inversion */
#define LAN80XX_10G_LN_R_RX_POL_INV                     			(0x1)

/* LANE_04 - Disable H1/L1 Loopback */
#define LAN80XX_10G_LN_CFG_RX2TX_LP_EN                  			(0x0)

/* LANE_04 - Disable H1/L1 Loopback */
#define LAN80XX_10G_LN_CFG_TX2RX_LP_EN                  			(0x0)

/* LANE_1E - Disable H6/L6 and H5/L5 Receiver Loopback */
#define LAN80XX_10G_LN_CFG_RXLB_EN                      			(0x0)

/* LANE_19 - Disable H6/L6 and H5/L5 Transmitter Loopback */
#define LAN80XX_10G_LN_CFG_TXLB_EN                      			(0x0)

/***** SERDES LOS Enable *****/
/* LANE_2D - ALOS Threshold adjustment */
#define LAN80XX_10G_LN_CFG_ALOS_THR_2_0                 			(0x0)

/* LANE_3F - ALOS enable */
#define LAN80XX_10G_LN_R_ALOS_EN                        			(0x1)

/* LANE_2E - SQulelth Enabled */
#define LAN80XX_10G_LN_CFG_DIS_SQ                       			(0x0)

/* SERDES_LOS - SD25 LOS Enabled */
#define LAN80XX_10G_SD25G_LOS_EN                        			(0x1)

/* SERDES_LOS - SD25 LOS : No invertion */
#define LAN80XX_10G_SD25G_LOS_INV                       			(0x0)

/* SERDES_LOS - Module LOS Disabled */
#define LAN80XX_10G_MOD_LOS_EN                          			(0x0)

/* SERDES_LOS - Module  LOS : No invertion */
#define LAN80XX_10G_MOD_LOS_INV                         			(0x0)

/***** These functions are not part of the 25G SerDes configuration, but needed to execute this test stand alone *****/
/******************* 1G_SPEED ***********************/
/***** PMA Common Configuration *****/
/* CMU_1A - Select Reg control */
#define LAN80XX_1G_R_DWIDTHCTRL_FROM_HWT                			(0x0)

/* CMU_1A - Select Reg control */
#define LAN80XX_1G_R_REG_MANUAL                         			(0x1)

/* CMU_31 - By default Termination controlled by Pin H3/L3 . No impact by CMU_31 */
#define LAN80XX_1G_CFG_COMMON_RESERVE_7_0               			(0x1)

/* CMU_09 - Use Internal regulator for VCO power */
#define LAN80XX_1G_CFG_EN_DUMMY                         			(0x0)

/* CMU_13 - Use Internal regulator for VCO power */
#define LAN80XX_1G_CFG_PLL_RESERVE_3_0                  			(0xf)

/* CMU_40 - Internal use */
#define LAN80XX_1G_L0_CFG_TXCAL_EN                      			(0x1)

/* CMU_46 - Set something to 0x4CF0 */
#define LAN80XX_1G_L0_CFG_TX_RESERVE_15_8               			(0x0)

/* CMU_45 - Set something to 0x4CF0 */
#define LAN80XX_1G_L0_CFG_TX_RESERVE_7_0                			(0x61)

/* CMU_0C - Enable PLL Loss of Lock */
#define LAN80XX_1G_CFG_PLL_LOL_SET                      			(0x1)

/* CMU_12 - Configure the VCO current tuning to 0x6 */
#define LAN80XX_1G_CFG_I_VCO_3_0                        			(0x6)

/* CMU_0F - Set PLL loop parameter tuning */
#define LAN80XX_1G_CFG_ICP_BASE_SEL_3_0                 			(0x3)

/* CMU_11 - Set PLL loop parameter tuning */
#define LAN80XX_1G_CFG_ICP_SEL_2_0                      			(0x3)

/* CMU_0F - Set PLL loop parameter tuning */
#define LAN80XX_1G_CFG_RSEL_2_0                         			(0x5)

/* CMU_1A - Data width from PMC to PMA to 40-bit */
#define LAN80XX_1G_R_DWIDTHCTRL_2_0                     			(0x0)

/* CMU_30 - Set the FIFOs on the TXFIFO to support 40-bit */
#define LAN80XX_1G_R_TXFIFO_CK_DIV_PMAD_2_0             			(0x1)

/* CMU_30 - Set the FIFOs on the RXFIFO to support 40-bit */
#define LAN80XX_1G_R_RXFIFO_CK_DIV_PMAD_2_0             			(0x1)

/* CMU_0C - VCO divider setting of 00, divide by 0 */
#define LAN80XX_1G_CFG_VCO_DIV_MODE_1_0                 			(0x1)

/* CMU_0D - Reference clock divide set to 01 divide by 2 */
#define LAN80XX_1G_CFG_PRE_DIVSEL_1_0                   			(0x0)

/* CMU_0E - PLL multiplying factor(Divide by 330) */
#define LAN80XX_1G_CFG_SEL_DIV_3_0                      			(0x8)

/* CMU_1F - Internal Use */
#define LAN80XX_1G_R_MULTI_LANE_MODE                    			(0x0)

/* CMU_17 - Set LS3 loopback(MB25 H4/L4) enable to 0 */
#define LAN80XX_1G_R_LBSLV_IN_PMAD                      			(0x0)

/***** PMA Line Configuration *****/
/* LANE_0C - Configure the PMA Clock bitwidth to support 40-bit */
#define LAN80XX_1G_LN_CFG_PMA_TX_CK_BITWIDTH_2_0        			(0x3)

/* LANE_01 - Set the PCS to PMA tx subrate control to 0 */
#define LAN80XX_1G_LN_CFG_TX_PREDIV_1_0                 			(0x0)

/* LANE_18 - Set the  value 0x3 for PMA RX clock frequency selection to support 40-bit data interface. */
#define LAN80XX_1G_LN_CFG_RXDIV_SEL_2_0                 			(0x3)

/* LANE_2C - Set the Transmitter frequency subrate to support the full frequency */
#define LAN80XX_1G_LN_CFG_TX_SUBRATE_2_0                			(0x3)

/* LANE_28 - Set the receiver frequency subrate to support the full frequency */
#define LAN80XX_1G_LN_CFG_RX_SUBRATE_2_0                			(0x3)

/* LANE_18 - Set CDRCK_EN to 1 for normal mode.(need set it to 0 if  loopback mode is enabled) */
#define LAN80XX_1G_LN_CFG_CDRCK_EN                      			(0x1)

/* LANE_0F - Enable 5 different DFE Taps? */
#define LAN80XX_1G_LN_CFG_DFETAP_EN_5_1                 			(0x0)

/* LANE_18 - Power up the error amplifier in the DFE (PD bit set to 0) */
#define LAN80XX_1G_LN_CFG_ERRAMP_PD                     			(0x1)

/* LANE_1D - Enable PI DFE block required to use the DFW(Internal use) */
#define LAN80XX_1G_LN_CFG_PI_DFE_EN                     			(0x1)

/* LANE_19 - Clock and Data Recovery  Enhance Design Part Power Down control(Internal use) */
#define LAN80XX_1G_LN_CFG_ECDR_PD                       			(0x1)

/* LANE_01 - TX margin setting */
#define LAN80XX_1G_LN_CFG_ITX_IPDRIVER_BASE_2_0         			(0x0)

/* LANE_03 - Set the Tap Delay of the DFE to a value of 0x12 */
#define LAN80XX_1G_LN_CFG_TAP_DLY_4_0                   			(0x0)

/* LANE_06 - Set the Pre-equalization level control to 0x6 */
#define LAN80XX_1G_LN_CFG_TAP_ADV_3_0                   			(0x0)

/* LANE_07 - Enable the pre-equalization settings */
#define LAN80XX_1G_LN_CFG_EN_ADV                        			(0x1)

/* LANE_07 - Enable the 1st stage post-equaliztion control of the transmitter */
#define LAN80XX_1G_LN_CFG_EN_DLY                        			(0x1)

/* LANE_0D - De-Multiplexor Power Down Control */
#define LAN80XX_1G_LN_CFG_DMUX_PD                       			(0x0)

/* LANE_04 - Power up the CML circuits by setting the PD bit to 0 */
#define LAN80XX_1G_LN_CFG_PD_CML                        			(0x0)

/* LANE_04 - Power up the TX Driver by setting the PD bit to 0 */
#define LAN80XX_1G_LN_CFG_PD_DRIVER                     			(0x0)

/* LANE_19 - Power up the Receiver regulator */
#define LAN80XX_1G_LN_CFG_RX_REG_PU                     			(0x1)

/* LANE_19 - Power down the RMS Detect, this is the default value */
#define LAN80XX_1G_LN_CFG_PD_RMS_DET                    			(0x1)

/* LANE_19 - Clock and Data Recovery Main Design Circuit Power Down control(Internal use) */
#define LAN80XX_1G_LN_CFG_DCDR_PD                       			(0x0)

/* LANE_04 - Enable the TX data path by setting to 1 */
#define LAN80XX_1G_LN_CFG_TAP_MAIN                      			(0x1)

/* LANE_06 - Enable the TX data path control */
#define LAN80XX_1G_LN_CFG_EN_MAIN                       			(0x1)

/* LANE_0E - Disable eye scan feature by setting EN to 0 */
#define LAN80XX_1G_LN_CFG_ISCAN_EN                      			(0x0)

/* LANE_2E - Disable fast eye scan feature by setting EN to 0 */
#define LAN80XX_1G_LN_CFG_EN_FAST_ISCAN                 			(0x0)

/* LANE_0D - DFE Related Clock set to enable */
#define LAN80XX_1G_LN_CFG_DFECK_EN                      			(0x0)

/* LANE_1C - Power up the DFE Analog Circuits (set PD bit to 0) */
#define LAN80XX_1G_LN_CFG_DFE_PD                        			(0x1)

/* LANE_0E - Digital MUX Clock Power Down Control by setting  to 0(Internal use) */
#define LAN80XX_1G_LN_CFG_DMUX_CLK_PD                   			(0x0)

/* LANE_23 - Enable PI (PI Filter) (Internal use) */
#define LAN80XX_1G_LN_CFG_PI_EN                         			(0x1)

/* LANE_19 - Power up the CTLE by setting the PD bit to 0 */
#define LAN80XX_1G_LN_CFG_PD_CTLE                       			(0x0)

/* LANE_0D - Enable the summer */
#define LAN80XX_1G_LN_CFG_SUMMER_EN                     			(0x1)

/* LANE_1E - PMA Digital clock function PD bit to 0 */
#define LAN80XX_1G_LN_CFG_PMAD_CK_PD                    			(0x0)

/* LANE_04 - Power Down clock circuits bit to 0 */
#define LAN80XX_1G_LN_CFG_PD_CLK                        			(0x0)

/* LANE_29 - Set 2nd order CDR setting */
#define LAN80XX_1G_LN_CFG_FILTER2ND_YZ_6_0              			(0x3f)

/* LANE_43 - TX Speed Change Registers(Internal use) */
#define LAN80XX_1G_LN_CFG_TX_RESERVE_15_8               			(0x8)

/* LANE_42 - TX Speed Change Registers(Internal use) */
#define LAN80XX_1G_LN_CFG_TX_RESERVE_7_0                			(0xce)

/* LANE_05 - TX Speed BW configured to 0x3 for 25G (Internal use) */
#define LAN80XX_1G_LN_CFG_BW_1_0                        			(0x0)

/* LANE_0B - Enable manual TX Calibration */
#define LAN80XX_1G_LN_CFG_TXCAL_MAN_EN                  			(0x1)

/* LANE_0A - Set the TX Calibration shift code to 0x02 */
#define LAN80XX_1G_LN_CFG_TXCAL_SHIFT_CODE_5_0          			(0x2)

/* LANE_09 - Set the TX Calbration Valid Sel variable to 0x4 */
#define LAN80XX_1G_LN_CFG_TXCAL_VALID_SEL_3_0           			(0x4)

/* LANE_1A - CDR Block  (internal use) */
#define LAN80XX_1G_LN_CFG_CDR_KF_2_0                    			(0x1)

/* LANE_1B - Set the Clock Data Recovery bandwidth settings to 0x04 */
#define LAN80XX_1G_LN_CFG_CDR_M_7_0                     			(0x4)

/* LANE_2B - Set the Phase Interpolator badwidth setting to 0x00, data rate dependent */
#define LAN80XX_1G_LN_CFG_PI_BW_3_0                     			(0x0)

/* LANE_2C - Enable 2nd Order CDR (DIS bit set to 1) */
#define LAN80XX_1G_LN_CFG_DIS_2NDORDER                  			(0x0)

/* LANE_2E - Continuous-Time Linear Equalizer reset */
#define LAN80XX_1G_LN_CFG_CTLE_RSTN                     			(0x0)

/* LANE_44 - EMS_PHY CDR Register Settings for 25G */
#define LAN80XX_1G_LN_CFG_RX_RESERVE_7_0                			(0xbf)

/* LANE_45 - EMS_PHY CDR Register Settings for 25G */
#define LAN80XX_1G_LN_CFG_RX_RESERVE_15_8               			(0x61)

/* LANE_0D - Configure RX terminations for 25G(Internal use) */
#define LAN80XX_1G_LN_CFG_RXTERM_2_0                    			(0x0)

/* LANE_21 - Variable Gain Control Code bypass */
#define LAN80XX_1G_LN_CFG_VGA_CTRL_BYP_4_0              			(0x8)

/* LANE_22 - CTLE ResistorManual Control mode */
#define LAN80XX_1G_LN_CFG_EQR_FORCE_3_0                 			(0x4)

/* LANE_1C - CTLE Capacitor Manual Control mode */
#define LAN80XX_1G_LN_CFG_EQC_FORCE_3_0                 			(0xf)

/* LANE_1E - Enable the sum setcm in the RX Equalizer (Internal use) */
#define LAN80XX_1G_LN_CFG_SUM_SETCM_EN                  			(0x1)

/* LANE_25 -  Set the RX Equalizer Initial position of ISCAN to 0x06(Internal use) */
#define LAN80XX_1G_LN_CFG_INIT_POS_ISCAN_6_0            			(0x6)

/* LANE_26 - Set the RX Equalizer Initial position of iPI to 0x09 (Internal use) */
#define LAN80XX_1G_LN_CFG_INIT_POS_IPI_6_0              			(0x9)

/* LANE_0E -  Set DFEDIG M Time Constant for DFE adaptation to 0x6 */
#define LAN80XX_1G_LN_CFG_DFEDIG_M_2_0                  			(0x6)

/* LANE_0E - Enable DFE digital adaptation in the RX Equalizer by setting the EN bit to 1 */
#define LAN80XX_1G_LN_CFG_EN_DFEDIG                     			(0x0)

/* LANE_40 - System Specific, disable TX polarity inversion */
#define LAN80XX_1G_LN_R_TX_POL_INV                      			(0x0)

/* LANE_40 - System Specific, enable RX polarity inversion */
#define LAN80XX_1G_LN_R_RX_POL_INV                      			(0x1)

/* LANE_04 - Disable H1/L1 Loopback */
#define LAN80XX_1G_LN_CFG_RX2TX_LP_EN                   			(0x00)

/* LANE_04 - Disable H1/L1 Loopback */
#define LAN80XX_1G_LN_CFG_TX2RX_LP_EN                   			(0x00)

/* LANE_1E - Disable H6/L6 and H5/L5 Receiver Loopback */
#define LAN80XX_1G_LN_CFG_RXLB_EN                       			(0x00)

/* LANE_19 - Disable H6/L6 and H5/L5 Transmitter Loopback */
#define LAN80XX_1G_LN_CFG_TXLB_EN                       			(0x00)

/***** SERDES LOS Enable *****/
/* LANE_2D - ALOS Threshold adjustment */
#define LAN80XX_1G_LN_CFG_ALOS_THR_2_0                  			(0x0)

/* LANE_3F - ALOS enable */
#define LAN80XX_1G_LN_R_ALOS_EN                         			(0x0001)

/* LANE_2E - SQulelth Enabled */
#define LAN80XX_1G_LN_CFG_DIS_SQ                        			(0x00)

/* SERDES_LOS - SD25 LOS Enabled */
#define LAN80XX_1G_SD25G_LOS_EN                         			(0x0001)

/* SERDES_LOS - SD25 LOS : No invertion */
#define LAN80XX_1G_SD25G_LOS_INV                        			(0x00)

/* SERDES_LOS - Module LOS Disabled */
#define LAN80XX_1G_MOD_LOS_EN                           			(0x00)

/* SERDES_LOS - Module  LOS : No invertion */
#define LAN80XX_1G_MOD_LOS_INV                          			(0x00)

/***** These functions are not part of the 25G SerDes configuration, but needed to execute this test stand alone *****/

#endif /* _LAN80XX_SERDES_CONFIG_H */
