// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

= MESA-2021.06

== MESA-2021.06

|===
|Version:          |MESA-2021.09
|Previous Version: |MESA-2021.06
|Date:             |2021-10-08
|Description:      |Roadmap release
|===

=== Disclaimers

==== LAN9662 and LAN9668 in BETA

LAN966x (LAN9662 and LAN9668) support is included in this release, but they
are still not fully tested and should be treated as BETA quality.

LAN966x in this release can be used for early access to evaluate the features
and/or start SW integration. It is not suitable for production use.


==== LAN8814 (PHY) in BETA with limited support

The support of LAN8814 in this release is considered to be in BETA quality. It
can be used for early access to evaluate the features and/or start SW
integration. It is not suitable for production use.

=== General

This release contains a number of bugfixes for the LAN966x family, but no new
major features have been introduced.
