// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

= MESA-2020.06

== MESA-2020.06

|===
|Version:          |MESA-2020.06
|Previous Version: |MESA-2020.03
|Date:             |2020-06-19
|Description:      |Roadmap release
|===


=== Disclaimers

==== SparX-5/5i (all SKUs)

Affected SKUs: VSC7546, VSC7549, VSC7552, VSC7556, VSC7558, VSC7546TSN,
VSC7549TSN, VSC7552TSN, VSC7556TSN and VSC7558TSN.

The support of SparX-5/5i (all SKUs) in this release is considered to be in BETA
quality. It can be used for early access, to evaluate the features and/or start
SW integration. It is not suitable for production use.


=== Genreal

==== 10G/25G 802.3ap Backplane Ethernet (KR) has been added for SparX-5/5i (all SKUs)

This release updates the existing KR API, and with this it introduce support for
the SparX-5/5i family. The existing APIs prefixed with `mesa_port_10g_kr_*` has
been renamed to `mesa_port_kr_*`. Beside from this change, a number of
additional APIs has been added to fully support SparX-5/5i.


==== Serval-T is regressions solved

Affected SKUs: VSC7410, VSC7415, VSC7430, VSC7435, VSC7436, VSC7437 and VSC7440

The MESA-2020.03 release had some NOR/NAND issues. These issues are now solved
in this release, and Serval-T is considered stable again.


==== VSC7414, VSC7416 and VSC7418 (Serval1 family) removed

The SW support of VSC7414, VSC7416 and VSC7418 has been removed in this release.

Customer who needs support for these parts needs to stay at the MESA-2020.03
release.


