// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

#ifndef _VTSS_LAGUNA_REGS_GPV_H_
#define _VTSS_LAGUNA_REGS_GPV_H_

#include "vtss_laguna_regs_common.h"

/***********************************************************************
 *
 * Target: \a GPV
 *
 *
 *
 ***********************************************************************/

/**
 * Register Group: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53
 *
 * a single contiguous block of memory
 */


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:PERIPH_ID_4
 */
#define VTSS_GPV_PERIPH_ID_4                 VTSS_IOREG(VTSS_TO_GPV,0x7f4)

/**
 * \details
 * Field: ::VTSS_GPV_PERIPH_ID_4 . PERIPH_ID_4
 */
#define  VTSS_F_GPV_PERIPH_ID_4_PERIPH_ID_4(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_GPV_PERIPH_ID_4_PERIPH_ID_4     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_GPV_PERIPH_ID_4_PERIPH_ID_4(x)  VTSS_EXTRACT_BITFIELD(x,0,8)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:PERIPH_ID_5
 */
#define VTSS_GPV_PERIPH_ID_5                 VTSS_IOREG(VTSS_TO_GPV,0x7f5)

/**
 * \details
 * Field: ::VTSS_GPV_PERIPH_ID_5 . PERIPH_ID_5
 */
#define  VTSS_F_GPV_PERIPH_ID_5_PERIPH_ID_5(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_GPV_PERIPH_ID_5_PERIPH_ID_5     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_GPV_PERIPH_ID_5_PERIPH_ID_5(x)  VTSS_EXTRACT_BITFIELD(x,0,8)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:PERIPH_ID_6
 */
#define VTSS_GPV_PERIPH_ID_6                 VTSS_IOREG(VTSS_TO_GPV,0x7f6)

/**
 * \details
 * Field: ::VTSS_GPV_PERIPH_ID_6 . PERIPH_ID_6
 */
#define  VTSS_F_GPV_PERIPH_ID_6_PERIPH_ID_6(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_GPV_PERIPH_ID_6_PERIPH_ID_6     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_GPV_PERIPH_ID_6_PERIPH_ID_6(x)  VTSS_EXTRACT_BITFIELD(x,0,8)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:PERIPH_ID_7
 */
#define VTSS_GPV_PERIPH_ID_7                 VTSS_IOREG(VTSS_TO_GPV,0x7f7)

/**
 * \details
 * Field: ::VTSS_GPV_PERIPH_ID_7 . PERIPH_ID_7
 */
#define  VTSS_F_GPV_PERIPH_ID_7_PERIPH_ID_7(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_GPV_PERIPH_ID_7_PERIPH_ID_7     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_GPV_PERIPH_ID_7_PERIPH_ID_7(x)  VTSS_EXTRACT_BITFIELD(x,0,8)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:PERIPH_ID_0
 */
#define VTSS_GPV_PERIPH_ID_0                 VTSS_IOREG(VTSS_TO_GPV,0x7f8)

/**
 * \details
 * Field: ::VTSS_GPV_PERIPH_ID_0 . PERIPH_ID_0
 */
#define  VTSS_F_GPV_PERIPH_ID_0_PERIPH_ID_0(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_GPV_PERIPH_ID_0_PERIPH_ID_0     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_GPV_PERIPH_ID_0_PERIPH_ID_0(x)  VTSS_EXTRACT_BITFIELD(x,0,8)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:PERIPH_ID_1
 */
#define VTSS_GPV_PERIPH_ID_1                 VTSS_IOREG(VTSS_TO_GPV,0x7f9)

/**
 * \details
 * Field: ::VTSS_GPV_PERIPH_ID_1 . PERIPH_ID_1
 */
#define  VTSS_F_GPV_PERIPH_ID_1_PERIPH_ID_1(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_GPV_PERIPH_ID_1_PERIPH_ID_1     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_GPV_PERIPH_ID_1_PERIPH_ID_1(x)  VTSS_EXTRACT_BITFIELD(x,0,8)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:PERIPH_ID_2
 */
#define VTSS_GPV_PERIPH_ID_2                 VTSS_IOREG(VTSS_TO_GPV,0x7fa)

/**
 * \details
 * Field: ::VTSS_GPV_PERIPH_ID_2 . PERIPH_ID_2
 */
#define  VTSS_F_GPV_PERIPH_ID_2_PERIPH_ID_2(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_GPV_PERIPH_ID_2_PERIPH_ID_2     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_GPV_PERIPH_ID_2_PERIPH_ID_2(x)  VTSS_EXTRACT_BITFIELD(x,0,8)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:PERIPH_ID_3
 */
#define VTSS_GPV_PERIPH_ID_3                 VTSS_IOREG(VTSS_TO_GPV,0x7fb)

/**
 * \details
 * Field: ::VTSS_GPV_PERIPH_ID_3 . CUST_MOD_NUM
 */
#define  VTSS_F_GPV_PERIPH_ID_3_CUST_MOD_NUM(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_GPV_PERIPH_ID_3_CUST_MOD_NUM     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_GPV_PERIPH_ID_3_CUST_MOD_NUM(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

/**
 * \details
 * Field: ::VTSS_GPV_PERIPH_ID_3 . REV_AND
 */
#define  VTSS_F_GPV_PERIPH_ID_3_REV_AND(x)    VTSS_ENCODE_BITFIELD(x,4,4)
#define  VTSS_M_GPV_PERIPH_ID_3_REV_AND       VTSS_ENCODE_BITMASK(4,4)
#define  VTSS_X_GPV_PERIPH_ID_3_REV_AND(x)    VTSS_EXTRACT_BITFIELD(x,4,4)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:COMP_ID_0
 */
#define VTSS_GPV_COMP_ID_0                   VTSS_IOREG(VTSS_TO_GPV,0x7fc)

/**
 * \details
 * Field: ::VTSS_GPV_COMP_ID_0 . COMP_ID_0
 */
#define  VTSS_F_GPV_COMP_ID_0_COMP_ID_0(x)    VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_GPV_COMP_ID_0_COMP_ID_0       VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_GPV_COMP_ID_0_COMP_ID_0(x)    VTSS_EXTRACT_BITFIELD(x,0,8)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:COMP_ID_1
 */
#define VTSS_GPV_COMP_ID_1                   VTSS_IOREG(VTSS_TO_GPV,0x7fd)

/**
 * \details
 * Field: ::VTSS_GPV_COMP_ID_1 . COMP_ID_1
 */
#define  VTSS_F_GPV_COMP_ID_1_COMP_ID_1(x)    VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_GPV_COMP_ID_1_COMP_ID_1       VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_GPV_COMP_ID_1_COMP_ID_1(x)    VTSS_EXTRACT_BITFIELD(x,0,8)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:COMP_ID_2
 */
#define VTSS_GPV_COMP_ID_2                   VTSS_IOREG(VTSS_TO_GPV,0x7fe)

/**
 * \details
 * Field: ::VTSS_GPV_COMP_ID_2 . COMP_ID_2
 */
#define  VTSS_F_GPV_COMP_ID_2_COMP_ID_2(x)    VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_GPV_COMP_ID_2_COMP_ID_2       VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_GPV_COMP_ID_2_COMP_ID_2(x)    VTSS_EXTRACT_BITFIELD(x,0,8)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:COMP_ID_3
 */
#define VTSS_GPV_COMP_ID_3                   VTSS_IOREG(VTSS_TO_GPV,0x7ff)

/**
 * \details
 * Field: ::VTSS_GPV_COMP_ID_3 . COMP_ID_3
 */
#define  VTSS_F_GPV_COMP_ID_3_COMP_ID_3(x)    VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_GPV_COMP_ID_3_COMP_ID_3       VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_GPV_COMP_ID_3_COMP_ID_3(x)    VTSS_EXTRACT_BITFIELD(x,0,8)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:SECURITY_BOOT_RAM
 */
#define VTSS_GPV_SECURITY_BOOT_RAM           VTSS_IOREG(VTSS_TO_GPV,0x3)

/**
 * \details
 * Field: ::VTSS_GPV_SECURITY_BOOT_RAM . SECURITY_BOOT_RAM
 */
#define  VTSS_F_GPV_SECURITY_BOOT_RAM_SECURITY_BOOT_RAM(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_SECURITY_BOOT_RAM_SECURITY_BOOT_RAM  VTSS_BIT(0)
#define  VTSS_X_GPV_SECURITY_BOOT_RAM_SECURITY_BOOT_RAM(x)  VTSS_EXTRACT_BITFIELD(x,0,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:SECURITY_DDR_CSS
 */
#define VTSS_GPV_SECURITY_DDR_CSS            VTSS_IOREG(VTSS_TO_GPV,0x5)

/**
 * \details
 * Field: ::VTSS_GPV_SECURITY_DDR_CSS . SECURITY_DDR_CSS
 */
#define  VTSS_F_GPV_SECURITY_DDR_CSS_SECURITY_DDR_CSS(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_SECURITY_DDR_CSS_SECURITY_DDR_CSS  VTSS_BIT(0)
#define  VTSS_X_GPV_SECURITY_DDR_CSS_SECURITY_DDR_CSS(x)  VTSS_EXTRACT_BITFIELD(x,0,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:SECURITY_CSR_REGS
 */
#define VTSS_GPV_SECURITY_CSR_REGS           VTSS_IOREG(VTSS_TO_GPV,0x7)

/**
 * \details
 * Field: ::VTSS_GPV_SECURITY_CSR_REGS . SECURITY_CSR_REGS
 */
#define  VTSS_F_GPV_SECURITY_CSR_REGS_SECURITY_CSR_REGS(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_SECURITY_CSR_REGS_SECURITY_CSR_REGS  VTSS_BIT(0)
#define  VTSS_X_GPV_SECURITY_CSR_REGS_SECURITY_CSR_REGS(x)  VTSS_EXTRACT_BITFIELD(x,0,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:SECURITY_CPU_REGS
 */
#define VTSS_GPV_SECURITY_CPU_REGS           VTSS_IOREG(VTSS_TO_GPV,0x8)

/**
 * \details
 * Field: ::VTSS_GPV_SECURITY_CPU_REGS . SECURITY_CPU_REGS
 */
#define  VTSS_F_GPV_SECURITY_CPU_REGS_SECURITY_CPU_REGS(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_SECURITY_CPU_REGS_SECURITY_CPU_REGS  VTSS_BIT(0)
#define  VTSS_X_GPV_SECURITY_CPU_REGS_SECURITY_CPU_REGS(x)  VTSS_EXTRACT_BITFIELD(x,0,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:SECURITY_PCIE_DBI
 */
#define VTSS_GPV_SECURITY_PCIE_DBI           VTSS_IOREG(VTSS_TO_GPV,0xd)

/**
 * \details
 * Field: ::VTSS_GPV_SECURITY_PCIE_DBI . SECURITY_PCIE_DBI
 */
#define  VTSS_F_GPV_SECURITY_PCIE_DBI_SECURITY_PCIE_DBI(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_SECURITY_PCIE_DBI_SECURITY_PCIE_DBI  VTSS_BIT(0)
#define  VTSS_X_GPV_SECURITY_PCIE_DBI_SECURITY_PCIE_DBI(x)  VTSS_EXTRACT_BITFIELD(x,0,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:SECURITY_PCIE_OB
 */
#define VTSS_GPV_SECURITY_PCIE_OB            VTSS_IOREG(VTSS_TO_GPV,0xe)

/**
 * \details
 * Field: ::VTSS_GPV_SECURITY_PCIE_OB . SECURITY_PCIE_OB
 */
#define  VTSS_F_GPV_SECURITY_PCIE_OB_SECURITY_PCIE_OB(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_SECURITY_PCIE_OB_SECURITY_PCIE_OB  VTSS_BIT(0)
#define  VTSS_X_GPV_SECURITY_PCIE_OB_SECURITY_PCIE_OB(x)  VTSS_EXTRACT_BITFIELD(x,0,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:SECURITY_PCIE_CFG
 */
#define VTSS_GPV_SECURITY_PCIE_CFG           VTSS_IOREG(VTSS_TO_GPV,0xf)

/**
 * \details
 * Field: ::VTSS_GPV_SECURITY_PCIE_CFG . SECURITY_PCIE_CFG
 */
#define  VTSS_F_GPV_SECURITY_PCIE_CFG_SECURITY_PCIE_CFG(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_SECURITY_PCIE_CFG_SECURITY_PCIE_CFG  VTSS_BIT(0)
#define  VTSS_X_GPV_SECURITY_PCIE_CFG_SECURITY_PCIE_CFG(x)  VTSS_EXTRACT_BITFIELD(x,0,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:SECURITY_APB_CSS3
 */
#define VTSS_GPV_SECURITY_APB_CSS3           VTSS_IOREG(VTSS_TO_GPV,0x11)

/**
 * \brief
 * Interface Name		  | Region
 * ----------------------------------------
 * SYS_CNT_RO			  | 0
 * SYS_CNT_CTRL 		  | 1
 * SYS_APB			  | 2

 *
 * \details
 * Field: ::VTSS_GPV_SECURITY_APB_CSS3 . SECURITY_APB_CSS3
 */
#define  VTSS_F_GPV_SECURITY_APB_CSS3_SECURITY_APB_CSS3(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_GPV_SECURITY_APB_CSS3_SECURITY_APB_CSS3     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_GPV_SECURITY_APB_CSS3_SECURITY_APB_CSS3(x)  VTSS_EXTRACT_BITFIELD(x,0,16)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:SECURITY_APB_MAIN3
 */
#define VTSS_GPV_SECURITY_APB_MAIN3          VTSS_IOREG(VTSS_TO_GPV,0x12)

/**
 * \brief
 * Interface Name		  | Region
 * ----------------------------------------
 * DDR_CTL			  | 0
 * DDR_PHY			  | 1
 * TIMERS			  | 2
 * WDT				  | 3
 * UVOV 			  | 4
 * TZC_CFG			  | 5
 * PCIE_PHY			  | 6

 *
 * \details
 * Field: ::VTSS_GPV_SECURITY_APB_MAIN3 . SECURITY_APB_MAIN3
 */
#define  VTSS_F_GPV_SECURITY_APB_MAIN3_SECURITY_APB_MAIN3(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_GPV_SECURITY_APB_MAIN3_SECURITY_APB_MAIN3     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_GPV_SECURITY_APB_MAIN3_SECURITY_APB_MAIN3(x)  VTSS_EXTRACT_BITFIELD(x,0,16)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:SECURITY_APB_CSS2
 */
#define VTSS_GPV_SECURITY_APB_CSS2           VTSS_IOREG(VTSS_TO_GPV,0x13)

/**
 * \brief
 * Interface Name		  | Region
 * ----------------------------------------
 * OTP				  | 0
 * SJTAG			  | 1

 *
 * \details
 * Field: ::VTSS_GPV_SECURITY_APB_CSS2 . SECURITY_APB_CSS2
 */
#define  VTSS_F_GPV_SECURITY_APB_CSS2_SECURITY_APB_CSS2(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_GPV_SECURITY_APB_CSS2_SECURITY_APB_CSS2     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_GPV_SECURITY_APB_CSS2_SECURITY_APB_CSS2(x)  VTSS_EXTRACT_BITFIELD(x,0,16)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:CA53_FN_MOD
 */
#define VTSS_GPV_CA53_FN_MOD                 VTSS_IOREG(VTSS_TO_GPV,0x10842)

/**
 * \details
 * Field: ::VTSS_GPV_CA53_FN_MOD . CA53_FN_MOD_FN_MOD
 */
#define  VTSS_F_GPV_CA53_FN_MOD_CA53_FN_MOD_FN_MOD(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_CA53_FN_MOD_CA53_FN_MOD_FN_MOD     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_CA53_FN_MOD_CA53_FN_MOD_FN_MOD(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:SECURITY_DDR_MAIN
 */
#define VTSS_GPV_SECURITY_DDR_MAIN           VTSS_IOREG(VTSS_TO_GPV,0xb)

/**
 * \details
 * Field: ::VTSS_GPV_SECURITY_DDR_MAIN . SECURITY_DDR_MAIN
 */
#define  VTSS_F_GPV_SECURITY_DDR_MAIN_SECURITY_DDR_MAIN(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_SECURITY_DDR_MAIN_SECURITY_DDR_MAIN  VTSS_BIT(0)
#define  VTSS_X_GPV_SECURITY_DDR_MAIN_SECURITY_DDR_MAIN(x)  VTSS_EXTRACT_BITFIELD(x,0,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:EXT_INITIATOR_IB_FN_MOD2
 */
#define VTSS_GPV_EXT_INITIATOR_IB_FN_MOD2    VTSS_IOREG(VTSS_TO_GPV,0x10c09)

/**
 * \details
 * Field: ::VTSS_GPV_EXT_INITIATOR_IB_FN_MOD2 . EXT_INITIATOR_IB_FN_MOD2_BYPASS_MERGE
 */
#define  VTSS_F_GPV_EXT_INITIATOR_IB_FN_MOD2_EXT_INITIATOR_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_EXT_INITIATOR_IB_FN_MOD2_EXT_INITIATOR_IB_FN_MOD2_BYPASS_MERGE  VTSS_BIT(0)
#define  VTSS_X_GPV_EXT_INITIATOR_IB_FN_MOD2_EXT_INITIATOR_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_EXTRACT_BITFIELD(x,0,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:EXT_INITIATOR_IB_FN_MOD
 */
#define VTSS_GPV_EXT_INITIATOR_IB_FN_MOD     VTSS_IOREG(VTSS_TO_GPV,0x10c42)

/**
 * \details
 * Field: ::VTSS_GPV_EXT_INITIATOR_IB_FN_MOD . EXT_INITIATOR_IB_FN_MOD_FN_MOD
 */
#define  VTSS_F_GPV_EXT_INITIATOR_IB_FN_MOD_EXT_INITIATOR_IB_FN_MOD_FN_MOD(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_EXT_INITIATOR_IB_FN_MOD_EXT_INITIATOR_IB_FN_MOD_FN_MOD     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_EXT_INITIATOR_IB_FN_MOD_EXT_INITIATOR_IB_FN_MOD_FN_MOD(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:FDMA_IB_FN_MOD2
 */
#define VTSS_GPV_FDMA_IB_FN_MOD2             VTSS_IOREG(VTSS_TO_GPV,0x11009)

/**
 * \details
 * Field: ::VTSS_GPV_FDMA_IB_FN_MOD2 . FDMA_IB_FN_MOD2_BYPASS_MERGE
 */
#define  VTSS_F_GPV_FDMA_IB_FN_MOD2_FDMA_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_FDMA_IB_FN_MOD2_FDMA_IB_FN_MOD2_BYPASS_MERGE  VTSS_BIT(0)
#define  VTSS_X_GPV_FDMA_IB_FN_MOD2_FDMA_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_EXTRACT_BITFIELD(x,0,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:FDMA_IB_FN_MOD
 */
#define VTSS_GPV_FDMA_IB_FN_MOD              VTSS_IOREG(VTSS_TO_GPV,0x11042)

/**
 * \details
 * Field: ::VTSS_GPV_FDMA_IB_FN_MOD . FDMA_IB_FN_MOD_FN_MOD
 */
#define  VTSS_F_GPV_FDMA_IB_FN_MOD_FDMA_IB_FN_MOD_FN_MOD(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_FDMA_IB_FN_MOD_FDMA_IB_FN_MOD_FN_MOD     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_FDMA_IB_FN_MOD_FDMA_IB_FN_MOD_FN_MOD(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:PCIE_IB_FN_MOD
 */
#define VTSS_GPV_PCIE_IB_FN_MOD              VTSS_IOREG(VTSS_TO_GPV,0x11442)

/**
 * \details
 * Field: ::VTSS_GPV_PCIE_IB_FN_MOD . PCIE_IB_FN_MOD_FN_MOD
 */
#define  VTSS_F_GPV_PCIE_IB_FN_MOD_PCIE_IB_FN_MOD_FN_MOD(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_PCIE_IB_FN_MOD_PCIE_IB_FN_MOD_FN_MOD     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_PCIE_IB_FN_MOD_PCIE_IB_FN_MOD_FN_MOD(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:XDMAC_FN_MOD
 */
#define VTSS_GPV_XDMAC_FN_MOD                VTSS_IOREG(VTSS_TO_GPV,0x11842)

/**
 * \details
 * Field: ::VTSS_GPV_XDMAC_FN_MOD . XDMAC_FN_MOD_FN_MOD
 */
#define  VTSS_F_GPV_XDMAC_FN_MOD_XDMAC_FN_MOD_FN_MOD(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_XDMAC_FN_MOD_XDMAC_FN_MOD_FN_MOD     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_XDMAC_FN_MOD_XDMAC_FN_MOD_FN_MOD(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:APB_CSS_AHB_CNTL
 */
#define VTSS_GPV_APB_CSS_AHB_CNTL            VTSS_IOREG(VTSS_TO_GPV,0x811)

/**
 * \details
 * Field: ::VTSS_GPV_APB_CSS_AHB_CNTL . APB_CSS_AHB_CNTL_DECERR_EN
 */
#define  VTSS_F_GPV_APB_CSS_AHB_CNTL_APB_CSS_AHB_CNTL_DECERR_EN(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_APB_CSS_AHB_CNTL_APB_CSS_AHB_CNTL_DECERR_EN  VTSS_BIT(0)
#define  VTSS_X_GPV_APB_CSS_AHB_CNTL_APB_CSS_AHB_CNTL_DECERR_EN(x)  VTSS_EXTRACT_BITFIELD(x,0,1)

/**
 * \details
 * Field: ::VTSS_GPV_APB_CSS_AHB_CNTL . APB_CSS_AHB_CNTL_FORCE_INCR
 */
#define  VTSS_F_GPV_APB_CSS_AHB_CNTL_APB_CSS_AHB_CNTL_FORCE_INCR(x)  VTSS_ENCODE_BITFIELD(!!(x),1,1)
#define  VTSS_M_GPV_APB_CSS_AHB_CNTL_APB_CSS_AHB_CNTL_FORCE_INCR  VTSS_BIT(1)
#define  VTSS_X_GPV_APB_CSS_AHB_CNTL_APB_CSS_AHB_CNTL_FORCE_INCR(x)  VTSS_EXTRACT_BITFIELD(x,1,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:APB_CSS_IB_FN_MOD2
 */
#define VTSS_GPV_APB_CSS_IB_FN_MOD2          VTSS_IOREG(VTSS_TO_GPV,0x809)

/**
 * \details
 * Field: ::VTSS_GPV_APB_CSS_IB_FN_MOD2 . APB_CSS_IB_FN_MOD2_BYPASS_MERGE
 */
#define  VTSS_F_GPV_APB_CSS_IB_FN_MOD2_APB_CSS_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_APB_CSS_IB_FN_MOD2_APB_CSS_IB_FN_MOD2_BYPASS_MERGE  VTSS_BIT(0)
#define  VTSS_X_GPV_APB_CSS_IB_FN_MOD2_APB_CSS_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_EXTRACT_BITFIELD(x,0,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:APB_CSS_IB_FN_MOD_ISS_BM
 */
#define VTSS_GPV_APB_CSS_IB_FN_MOD_ISS_BM    VTSS_IOREG(VTSS_TO_GPV,0x802)

/**
 * \details
 * Field: ::VTSS_GPV_APB_CSS_IB_FN_MOD_ISS_BM . APB_CSS_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM
 */
#define  VTSS_F_GPV_APB_CSS_IB_FN_MOD_ISS_BM_APB_CSS_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_APB_CSS_IB_FN_MOD_ISS_BM_APB_CSS_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_APB_CSS_IB_FN_MOD_ISS_BM_APB_CSS_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:BOOT_RAM_FN_MOD_ISS_BM
 */
#define VTSS_GPV_BOOT_RAM_FN_MOD_ISS_BM      VTSS_IOREG(VTSS_TO_GPV,0xc02)

/**
 * \details
 * Field: ::VTSS_GPV_BOOT_RAM_FN_MOD_ISS_BM . BOOT_RAM_FN_MOD_ISS_BM_FN_MOD_ISS_BM
 */
#define  VTSS_F_GPV_BOOT_RAM_FN_MOD_ISS_BM_BOOT_RAM_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_BOOT_RAM_FN_MOD_ISS_BM_BOOT_RAM_FN_MOD_ISS_BM_FN_MOD_ISS_BM     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_BOOT_RAM_FN_MOD_ISS_BM_BOOT_RAM_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:BOOT_RAM_AHB_CNTL
 */
#define VTSS_GPV_BOOT_RAM_AHB_CNTL           VTSS_IOREG(VTSS_TO_GPV,0xc11)

/**
 * \details
 * Field: ::VTSS_GPV_BOOT_RAM_AHB_CNTL . BOOT_RAM_AHB_CNTL_DECERR_EN
 */
#define  VTSS_F_GPV_BOOT_RAM_AHB_CNTL_BOOT_RAM_AHB_CNTL_DECERR_EN(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_BOOT_RAM_AHB_CNTL_BOOT_RAM_AHB_CNTL_DECERR_EN  VTSS_BIT(0)
#define  VTSS_X_GPV_BOOT_RAM_AHB_CNTL_BOOT_RAM_AHB_CNTL_DECERR_EN(x)  VTSS_EXTRACT_BITFIELD(x,0,1)

/**
 * \details
 * Field: ::VTSS_GPV_BOOT_RAM_AHB_CNTL . BOOT_RAM_AHB_CNTL_FORCE_INCR
 */
#define  VTSS_F_GPV_BOOT_RAM_AHB_CNTL_BOOT_RAM_AHB_CNTL_FORCE_INCR(x)  VTSS_ENCODE_BITFIELD(!!(x),1,1)
#define  VTSS_M_GPV_BOOT_RAM_AHB_CNTL_BOOT_RAM_AHB_CNTL_FORCE_INCR  VTSS_BIT(1)
#define  VTSS_X_GPV_BOOT_RAM_AHB_CNTL_BOOT_RAM_AHB_CNTL_FORCE_INCR(x)  VTSS_EXTRACT_BITFIELD(x,1,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:PKE_AHB_CNTL
 */
#define VTSS_GPV_PKE_AHB_CNTL                VTSS_IOREG(VTSS_TO_GPV,0x1011)

/**
 * \details
 * Field: ::VTSS_GPV_PKE_AHB_CNTL . PKE_AHB_CNTL_DECERR_EN
 */
#define  VTSS_F_GPV_PKE_AHB_CNTL_PKE_AHB_CNTL_DECERR_EN(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_PKE_AHB_CNTL_PKE_AHB_CNTL_DECERR_EN  VTSS_BIT(0)
#define  VTSS_X_GPV_PKE_AHB_CNTL_PKE_AHB_CNTL_DECERR_EN(x)  VTSS_EXTRACT_BITFIELD(x,0,1)

/**
 * \details
 * Field: ::VTSS_GPV_PKE_AHB_CNTL . PKE_AHB_CNTL_FORCE_INCR
 */
#define  VTSS_F_GPV_PKE_AHB_CNTL_PKE_AHB_CNTL_FORCE_INCR(x)  VTSS_ENCODE_BITFIELD(!!(x),1,1)
#define  VTSS_M_GPV_PKE_AHB_CNTL_PKE_AHB_CNTL_FORCE_INCR  VTSS_BIT(1)
#define  VTSS_X_GPV_PKE_AHB_CNTL_PKE_AHB_CNTL_FORCE_INCR(x)  VTSS_EXTRACT_BITFIELD(x,1,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:PKE_IB_FN_MOD2
 */
#define VTSS_GPV_PKE_IB_FN_MOD2              VTSS_IOREG(VTSS_TO_GPV,0x1009)

/**
 * \details
 * Field: ::VTSS_GPV_PKE_IB_FN_MOD2 . PKE_IB_FN_MOD2_BYPASS_MERGE
 */
#define  VTSS_F_GPV_PKE_IB_FN_MOD2_PKE_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_PKE_IB_FN_MOD2_PKE_IB_FN_MOD2_BYPASS_MERGE  VTSS_BIT(0)
#define  VTSS_X_GPV_PKE_IB_FN_MOD2_PKE_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_EXTRACT_BITFIELD(x,0,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:PKE_IB_FN_MOD_ISS_BM
 */
#define VTSS_GPV_PKE_IB_FN_MOD_ISS_BM        VTSS_IOREG(VTSS_TO_GPV,0x1002)

/**
 * \details
 * Field: ::VTSS_GPV_PKE_IB_FN_MOD_ISS_BM . PKE_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM
 */
#define  VTSS_F_GPV_PKE_IB_FN_MOD_ISS_BM_PKE_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_PKE_IB_FN_MOD_ISS_BM_PKE_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_PKE_IB_FN_MOD_ISS_BM_PKE_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:DDR_CSS_FN_MOD_ISS_BM
 */
#define VTSS_GPV_DDR_CSS_FN_MOD_ISS_BM       VTSS_IOREG(VTSS_TO_GPV,0x1402)

/**
 * \details
 * Field: ::VTSS_GPV_DDR_CSS_FN_MOD_ISS_BM . DDR_CSS_FN_MOD_ISS_BM_FN_MOD_ISS_BM
 */
#define  VTSS_F_GPV_DDR_CSS_FN_MOD_ISS_BM_DDR_CSS_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_DDR_CSS_FN_MOD_ISS_BM_DDR_CSS_FN_MOD_ISS_BM_FN_MOD_ISS_BM     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_DDR_CSS_FN_MOD_ISS_BM_DDR_CSS_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:CSS2HSS_IB_FN_MOD2
 */
#define VTSS_GPV_CSS2HSS_IB_FN_MOD2          VTSS_IOREG(VTSS_TO_GPV,0x1809)

/**
 * \details
 * Field: ::VTSS_GPV_CSS2HSS_IB_FN_MOD2 . CSS2HSS_IB_FN_MOD2_BYPASS_MERGE
 */
#define  VTSS_F_GPV_CSS2HSS_IB_FN_MOD2_CSS2HSS_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_CSS2HSS_IB_FN_MOD2_CSS2HSS_IB_FN_MOD2_BYPASS_MERGE  VTSS_BIT(0)
#define  VTSS_X_GPV_CSS2HSS_IB_FN_MOD2_CSS2HSS_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_EXTRACT_BITFIELD(x,0,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:CSS2HSS_IB_FN_MOD_LB
 */
#define VTSS_GPV_CSS2HSS_IB_FN_MOD_LB        VTSS_IOREG(VTSS_TO_GPV,0x180b)

/**
 * \details
 * Field: ::VTSS_GPV_CSS2HSS_IB_FN_MOD_LB . CSS2HSS_IB_FN_MOD_LB_FN_MOD_LB
 */
#define  VTSS_F_GPV_CSS2HSS_IB_FN_MOD_LB_CSS2HSS_IB_FN_MOD_LB_FN_MOD_LB(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_CSS2HSS_IB_FN_MOD_LB_CSS2HSS_IB_FN_MOD_LB_FN_MOD_LB  VTSS_BIT(0)
#define  VTSS_X_GPV_CSS2HSS_IB_FN_MOD_LB_CSS2HSS_IB_FN_MOD_LB_FN_MOD_LB(x)  VTSS_EXTRACT_BITFIELD(x,0,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:CSS2HSS_IB_FN_MOD_ISS_BM
 */
#define VTSS_GPV_CSS2HSS_IB_FN_MOD_ISS_BM    VTSS_IOREG(VTSS_TO_GPV,0x1802)

/**
 * \details
 * Field: ::VTSS_GPV_CSS2HSS_IB_FN_MOD_ISS_BM . CSS2HSS_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM
 */
#define  VTSS_F_GPV_CSS2HSS_IB_FN_MOD_ISS_BM_CSS2HSS_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_CSS2HSS_IB_FN_MOD_ISS_BM_CSS2HSS_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_CSS2HSS_IB_FN_MOD_ISS_BM_CSS2HSS_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:CSR_REGS_AHB_CNTL
 */
#define VTSS_GPV_CSR_REGS_AHB_CNTL           VTSS_IOREG(VTSS_TO_GPV,0x1c11)

/**
 * \details
 * Field: ::VTSS_GPV_CSR_REGS_AHB_CNTL . CSR_REGS_AHB_CNTL_DECERR_EN
 */
#define  VTSS_F_GPV_CSR_REGS_AHB_CNTL_CSR_REGS_AHB_CNTL_DECERR_EN(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_CSR_REGS_AHB_CNTL_CSR_REGS_AHB_CNTL_DECERR_EN  VTSS_BIT(0)
#define  VTSS_X_GPV_CSR_REGS_AHB_CNTL_CSR_REGS_AHB_CNTL_DECERR_EN(x)  VTSS_EXTRACT_BITFIELD(x,0,1)

/**
 * \details
 * Field: ::VTSS_GPV_CSR_REGS_AHB_CNTL . CSR_REGS_AHB_CNTL_FORCE_INCR
 */
#define  VTSS_F_GPV_CSR_REGS_AHB_CNTL_CSR_REGS_AHB_CNTL_FORCE_INCR(x)  VTSS_ENCODE_BITFIELD(!!(x),1,1)
#define  VTSS_M_GPV_CSR_REGS_AHB_CNTL_CSR_REGS_AHB_CNTL_FORCE_INCR  VTSS_BIT(1)
#define  VTSS_X_GPV_CSR_REGS_AHB_CNTL_CSR_REGS_AHB_CNTL_FORCE_INCR(x)  VTSS_EXTRACT_BITFIELD(x,1,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:CSR_REGS_IB_FN_MOD2
 */
#define VTSS_GPV_CSR_REGS_IB_FN_MOD2         VTSS_IOREG(VTSS_TO_GPV,0x1c09)

/**
 * \details
 * Field: ::VTSS_GPV_CSR_REGS_IB_FN_MOD2 . CSR_REGS_IB_FN_MOD2_BYPASS_MERGE
 */
#define  VTSS_F_GPV_CSR_REGS_IB_FN_MOD2_CSR_REGS_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_CSR_REGS_IB_FN_MOD2_CSR_REGS_IB_FN_MOD2_BYPASS_MERGE  VTSS_BIT(0)
#define  VTSS_X_GPV_CSR_REGS_IB_FN_MOD2_CSR_REGS_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_EXTRACT_BITFIELD(x,0,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:CSR_REGS_IB_FN_MOD_ISS_BM
 */
#define VTSS_GPV_CSR_REGS_IB_FN_MOD_ISS_BM   VTSS_IOREG(VTSS_TO_GPV,0x1c02)

/**
 * \details
 * Field: ::VTSS_GPV_CSR_REGS_IB_FN_MOD_ISS_BM . CSR_REGS_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM
 */
#define  VTSS_F_GPV_CSR_REGS_IB_FN_MOD_ISS_BM_CSR_REGS_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_CSR_REGS_IB_FN_MOD_ISS_BM_CSR_REGS_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_CSR_REGS_IB_FN_MOD_ISS_BM_CSR_REGS_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:CPU_REGS_AHB_CNTL
 */
#define VTSS_GPV_CPU_REGS_AHB_CNTL           VTSS_IOREG(VTSS_TO_GPV,0x2011)

/**
 * \details
 * Field: ::VTSS_GPV_CPU_REGS_AHB_CNTL . CPU_REGS_AHB_CNTL_DECERR_EN
 */
#define  VTSS_F_GPV_CPU_REGS_AHB_CNTL_CPU_REGS_AHB_CNTL_DECERR_EN(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_CPU_REGS_AHB_CNTL_CPU_REGS_AHB_CNTL_DECERR_EN  VTSS_BIT(0)
#define  VTSS_X_GPV_CPU_REGS_AHB_CNTL_CPU_REGS_AHB_CNTL_DECERR_EN(x)  VTSS_EXTRACT_BITFIELD(x,0,1)

/**
 * \details
 * Field: ::VTSS_GPV_CPU_REGS_AHB_CNTL . CPU_REGS_AHB_CNTL_FORCE_INCR
 */
#define  VTSS_F_GPV_CPU_REGS_AHB_CNTL_CPU_REGS_AHB_CNTL_FORCE_INCR(x)  VTSS_ENCODE_BITFIELD(!!(x),1,1)
#define  VTSS_M_GPV_CPU_REGS_AHB_CNTL_CPU_REGS_AHB_CNTL_FORCE_INCR  VTSS_BIT(1)
#define  VTSS_X_GPV_CPU_REGS_AHB_CNTL_CPU_REGS_AHB_CNTL_FORCE_INCR(x)  VTSS_EXTRACT_BITFIELD(x,1,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:CPU_REGS_IB_FN_MOD2
 */
#define VTSS_GPV_CPU_REGS_IB_FN_MOD2         VTSS_IOREG(VTSS_TO_GPV,0x2009)

/**
 * \details
 * Field: ::VTSS_GPV_CPU_REGS_IB_FN_MOD2 . CPU_REGS_IB_FN_MOD2_BYPASS_MERGE
 */
#define  VTSS_F_GPV_CPU_REGS_IB_FN_MOD2_CPU_REGS_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_CPU_REGS_IB_FN_MOD2_CPU_REGS_IB_FN_MOD2_BYPASS_MERGE  VTSS_BIT(0)
#define  VTSS_X_GPV_CPU_REGS_IB_FN_MOD2_CPU_REGS_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_EXTRACT_BITFIELD(x,0,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:CPU_REGS_IB_FN_MOD_ISS_BM
 */
#define VTSS_GPV_CPU_REGS_IB_FN_MOD_ISS_BM   VTSS_IOREG(VTSS_TO_GPV,0x2002)

/**
 * \details
 * Field: ::VTSS_GPV_CPU_REGS_IB_FN_MOD_ISS_BM . CPU_REGS_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM
 */
#define  VTSS_F_GPV_CPU_REGS_IB_FN_MOD_ISS_BM_CPU_REGS_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_CPU_REGS_IB_FN_MOD_ISS_BM_CPU_REGS_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_CPU_REGS_IB_FN_MOD_ISS_BM_CPU_REGS_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:APB_MAIN1_FN_MOD_ISS_BM
 */
#define VTSS_GPV_APB_MAIN1_FN_MOD_ISS_BM     VTSS_IOREG(VTSS_TO_GPV,0x2402)

/**
 * \details
 * Field: ::VTSS_GPV_APB_MAIN1_FN_MOD_ISS_BM . APB_MAIN1_FN_MOD_ISS_BM_FN_MOD_ISS_BM
 */
#define  VTSS_F_GPV_APB_MAIN1_FN_MOD_ISS_BM_APB_MAIN1_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_APB_MAIN1_FN_MOD_ISS_BM_APB_MAIN1_FN_MOD_ISS_BM_FN_MOD_ISS_BM     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_APB_MAIN1_FN_MOD_ISS_BM_APB_MAIN1_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:APB_MAIN1_AHB_CNTL
 */
#define VTSS_GPV_APB_MAIN1_AHB_CNTL          VTSS_IOREG(VTSS_TO_GPV,0x2411)

/**
 * \details
 * Field: ::VTSS_GPV_APB_MAIN1_AHB_CNTL . APB_MAIN1_AHB_CNTL_DECERR_EN
 */
#define  VTSS_F_GPV_APB_MAIN1_AHB_CNTL_APB_MAIN1_AHB_CNTL_DECERR_EN(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_APB_MAIN1_AHB_CNTL_APB_MAIN1_AHB_CNTL_DECERR_EN  VTSS_BIT(0)
#define  VTSS_X_GPV_APB_MAIN1_AHB_CNTL_APB_MAIN1_AHB_CNTL_DECERR_EN(x)  VTSS_EXTRACT_BITFIELD(x,0,1)

/**
 * \details
 * Field: ::VTSS_GPV_APB_MAIN1_AHB_CNTL . APB_MAIN1_AHB_CNTL_FORCE_INCR
 */
#define  VTSS_F_GPV_APB_MAIN1_AHB_CNTL_APB_MAIN1_AHB_CNTL_FORCE_INCR(x)  VTSS_ENCODE_BITFIELD(!!(x),1,1)
#define  VTSS_M_GPV_APB_MAIN1_AHB_CNTL_APB_MAIN1_AHB_CNTL_FORCE_INCR  VTSS_BIT(1)
#define  VTSS_X_GPV_APB_MAIN1_AHB_CNTL_APB_MAIN1_AHB_CNTL_FORCE_INCR(x)  VTSS_EXTRACT_BITFIELD(x,1,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:APB_MAIN2_FN_MOD_ISS_BM
 */
#define VTSS_GPV_APB_MAIN2_FN_MOD_ISS_BM     VTSS_IOREG(VTSS_TO_GPV,0x2802)

/**
 * \details
 * Field: ::VTSS_GPV_APB_MAIN2_FN_MOD_ISS_BM . APB_MAIN2_FN_MOD_ISS_BM_FN_MOD_ISS_BM
 */
#define  VTSS_F_GPV_APB_MAIN2_FN_MOD_ISS_BM_APB_MAIN2_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_APB_MAIN2_FN_MOD_ISS_BM_APB_MAIN2_FN_MOD_ISS_BM_FN_MOD_ISS_BM     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_APB_MAIN2_FN_MOD_ISS_BM_APB_MAIN2_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:APB_MAIN2_AHB_CNTL
 */
#define VTSS_GPV_APB_MAIN2_AHB_CNTL          VTSS_IOREG(VTSS_TO_GPV,0x2811)

/**
 * \details
 * Field: ::VTSS_GPV_APB_MAIN2_AHB_CNTL . APB_MAIN2_AHB_CNTL_DECERR_EN
 */
#define  VTSS_F_GPV_APB_MAIN2_AHB_CNTL_APB_MAIN2_AHB_CNTL_DECERR_EN(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_APB_MAIN2_AHB_CNTL_APB_MAIN2_AHB_CNTL_DECERR_EN  VTSS_BIT(0)
#define  VTSS_X_GPV_APB_MAIN2_AHB_CNTL_APB_MAIN2_AHB_CNTL_DECERR_EN(x)  VTSS_EXTRACT_BITFIELD(x,0,1)

/**
 * \details
 * Field: ::VTSS_GPV_APB_MAIN2_AHB_CNTL . APB_MAIN2_AHB_CNTL_FORCE_INCR
 */
#define  VTSS_F_GPV_APB_MAIN2_AHB_CNTL_APB_MAIN2_AHB_CNTL_FORCE_INCR(x)  VTSS_ENCODE_BITFIELD(!!(x),1,1)
#define  VTSS_M_GPV_APB_MAIN2_AHB_CNTL_APB_MAIN2_AHB_CNTL_FORCE_INCR  VTSS_BIT(1)
#define  VTSS_X_GPV_APB_MAIN2_AHB_CNTL_APB_MAIN2_AHB_CNTL_FORCE_INCR(x)  VTSS_EXTRACT_BITFIELD(x,1,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:DDR_MAIN_FN_MOD_ISS_BM
 */
#define VTSS_GPV_DDR_MAIN_FN_MOD_ISS_BM      VTSS_IOREG(VTSS_TO_GPV,0x2c02)

/**
 * \details
 * Field: ::VTSS_GPV_DDR_MAIN_FN_MOD_ISS_BM . DDR_MAIN_FN_MOD_ISS_BM_FN_MOD_ISS_BM
 */
#define  VTSS_F_GPV_DDR_MAIN_FN_MOD_ISS_BM_DDR_MAIN_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_DDR_MAIN_FN_MOD_ISS_BM_DDR_MAIN_FN_MOD_ISS_BM_FN_MOD_ISS_BM     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_DDR_MAIN_FN_MOD_ISS_BM_DDR_MAIN_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:MAIN2HSS_FN_MOD_ISS_BM
 */
#define VTSS_GPV_MAIN2HSS_FN_MOD_ISS_BM      VTSS_IOREG(VTSS_TO_GPV,0x3002)

/**
 * \details
 * Field: ::VTSS_GPV_MAIN2HSS_FN_MOD_ISS_BM . MAIN2HSS_FN_MOD_ISS_BM_FN_MOD_ISS_BM
 */
#define  VTSS_F_GPV_MAIN2HSS_FN_MOD_ISS_BM_MAIN2HSS_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_MAIN2HSS_FN_MOD_ISS_BM_MAIN2HSS_FN_MOD_ISS_BM_FN_MOD_ISS_BM     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_MAIN2HSS_FN_MOD_ISS_BM_MAIN2HSS_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:PCIE_DBI_IB_FN_MOD2
 */
#define VTSS_GPV_PCIE_DBI_IB_FN_MOD2         VTSS_IOREG(VTSS_TO_GPV,0x3409)

/**
 * \details
 * Field: ::VTSS_GPV_PCIE_DBI_IB_FN_MOD2 . PCIE_DBI_IB_FN_MOD2_BYPASS_MERGE
 */
#define  VTSS_F_GPV_PCIE_DBI_IB_FN_MOD2_PCIE_DBI_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_PCIE_DBI_IB_FN_MOD2_PCIE_DBI_IB_FN_MOD2_BYPASS_MERGE  VTSS_BIT(0)
#define  VTSS_X_GPV_PCIE_DBI_IB_FN_MOD2_PCIE_DBI_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_EXTRACT_BITFIELD(x,0,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:PCIE_DBI_IB_FN_MOD_ISS_BM
 */
#define VTSS_GPV_PCIE_DBI_IB_FN_MOD_ISS_BM   VTSS_IOREG(VTSS_TO_GPV,0x3402)

/**
 * \details
 * Field: ::VTSS_GPV_PCIE_DBI_IB_FN_MOD_ISS_BM . PCIE_DBI_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM
 */
#define  VTSS_F_GPV_PCIE_DBI_IB_FN_MOD_ISS_BM_PCIE_DBI_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_PCIE_DBI_IB_FN_MOD_ISS_BM_PCIE_DBI_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_PCIE_DBI_IB_FN_MOD_ISS_BM_PCIE_DBI_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:PCIE_OB_FN_MOD_ISS_BM
 */
#define VTSS_GPV_PCIE_OB_FN_MOD_ISS_BM       VTSS_IOREG(VTSS_TO_GPV,0x3802)

/**
 * \details
 * Field: ::VTSS_GPV_PCIE_OB_FN_MOD_ISS_BM . PCIE_OB_FN_MOD_ISS_BM_FN_MOD_ISS_BM
 */
#define  VTSS_F_GPV_PCIE_OB_FN_MOD_ISS_BM_PCIE_OB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_PCIE_OB_FN_MOD_ISS_BM_PCIE_OB_FN_MOD_ISS_BM_FN_MOD_ISS_BM     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_PCIE_OB_FN_MOD_ISS_BM_PCIE_OB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:PCIE_CFG_AHB_CNTL
 */
#define VTSS_GPV_PCIE_CFG_AHB_CNTL           VTSS_IOREG(VTSS_TO_GPV,0x3c11)

/**
 * \details
 * Field: ::VTSS_GPV_PCIE_CFG_AHB_CNTL . PCIE_CFG_AHB_CNTL_DECERR_EN
 */
#define  VTSS_F_GPV_PCIE_CFG_AHB_CNTL_PCIE_CFG_AHB_CNTL_DECERR_EN(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_PCIE_CFG_AHB_CNTL_PCIE_CFG_AHB_CNTL_DECERR_EN  VTSS_BIT(0)
#define  VTSS_X_GPV_PCIE_CFG_AHB_CNTL_PCIE_CFG_AHB_CNTL_DECERR_EN(x)  VTSS_EXTRACT_BITFIELD(x,0,1)

/**
 * \details
 * Field: ::VTSS_GPV_PCIE_CFG_AHB_CNTL . PCIE_CFG_AHB_CNTL_FORCE_INCR
 */
#define  VTSS_F_GPV_PCIE_CFG_AHB_CNTL_PCIE_CFG_AHB_CNTL_FORCE_INCR(x)  VTSS_ENCODE_BITFIELD(!!(x),1,1)
#define  VTSS_M_GPV_PCIE_CFG_AHB_CNTL_PCIE_CFG_AHB_CNTL_FORCE_INCR  VTSS_BIT(1)
#define  VTSS_X_GPV_PCIE_CFG_AHB_CNTL_PCIE_CFG_AHB_CNTL_FORCE_INCR(x)  VTSS_EXTRACT_BITFIELD(x,1,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:PCIE_CFG_IB_FN_MOD2
 */
#define VTSS_GPV_PCIE_CFG_IB_FN_MOD2         VTSS_IOREG(VTSS_TO_GPV,0x3c09)

/**
 * \details
 * Field: ::VTSS_GPV_PCIE_CFG_IB_FN_MOD2 . PCIE_CFG_IB_FN_MOD2_BYPASS_MERGE
 */
#define  VTSS_F_GPV_PCIE_CFG_IB_FN_MOD2_PCIE_CFG_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_PCIE_CFG_IB_FN_MOD2_PCIE_CFG_IB_FN_MOD2_BYPASS_MERGE  VTSS_BIT(0)
#define  VTSS_X_GPV_PCIE_CFG_IB_FN_MOD2_PCIE_CFG_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_EXTRACT_BITFIELD(x,0,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:PCIE_CFG_IB_FN_MOD_ISS_BM
 */
#define VTSS_GPV_PCIE_CFG_IB_FN_MOD_ISS_BM   VTSS_IOREG(VTSS_TO_GPV,0x3c02)

/**
 * \details
 * Field: ::VTSS_GPV_PCIE_CFG_IB_FN_MOD_ISS_BM . PCIE_CFG_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM
 */
#define  VTSS_F_GPV_PCIE_CFG_IB_FN_MOD_ISS_BM_PCIE_CFG_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_PCIE_CFG_IB_FN_MOD_ISS_BM_PCIE_CFG_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_PCIE_CFG_IB_FN_MOD_ISS_BM_PCIE_CFG_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:GIC400_CFG_IB_FN_MOD2
 */
#define VTSS_GPV_GIC400_CFG_IB_FN_MOD2       VTSS_IOREG(VTSS_TO_GPV,0x4009)

/**
 * \details
 * Field: ::VTSS_GPV_GIC400_CFG_IB_FN_MOD2 . GIC400_CFG_IB_FN_MOD2_BYPASS_MERGE
 */
#define  VTSS_F_GPV_GIC400_CFG_IB_FN_MOD2_GIC400_CFG_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_GIC400_CFG_IB_FN_MOD2_GIC400_CFG_IB_FN_MOD2_BYPASS_MERGE  VTSS_BIT(0)
#define  VTSS_X_GPV_GIC400_CFG_IB_FN_MOD2_GIC400_CFG_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_EXTRACT_BITFIELD(x,0,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:GIC400_CFG_IB_FN_MOD_LB
 */
#define VTSS_GPV_GIC400_CFG_IB_FN_MOD_LB     VTSS_IOREG(VTSS_TO_GPV,0x400b)

/**
 * \details
 * Field: ::VTSS_GPV_GIC400_CFG_IB_FN_MOD_LB . GIC400_CFG_IB_FN_MOD_LB_FN_MOD_LB
 */
#define  VTSS_F_GPV_GIC400_CFG_IB_FN_MOD_LB_GIC400_CFG_IB_FN_MOD_LB_FN_MOD_LB(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_GIC400_CFG_IB_FN_MOD_LB_GIC400_CFG_IB_FN_MOD_LB_FN_MOD_LB  VTSS_BIT(0)
#define  VTSS_X_GPV_GIC400_CFG_IB_FN_MOD_LB_GIC400_CFG_IB_FN_MOD_LB_FN_MOD_LB(x)  VTSS_EXTRACT_BITFIELD(x,0,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:GIC400_CFG_IB_FN_MOD_ISS_BM
 */
#define VTSS_GPV_GIC400_CFG_IB_FN_MOD_ISS_BM  VTSS_IOREG(VTSS_TO_GPV,0x4002)

/**
 * \details
 * Field: ::VTSS_GPV_GIC400_CFG_IB_FN_MOD_ISS_BM . GIC400_CFG_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM
 */
#define  VTSS_F_GPV_GIC400_CFG_IB_FN_MOD_ISS_BM_GIC400_CFG_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_GIC400_CFG_IB_FN_MOD_ISS_BM_GIC400_CFG_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_GIC400_CFG_IB_FN_MOD_ISS_BM_GIC400_CFG_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:APB_CSS3_IB_FN_MOD2
 */
#define VTSS_GPV_APB_CSS3_IB_FN_MOD2         VTSS_IOREG(VTSS_TO_GPV,0x4409)

/**
 * \details
 * Field: ::VTSS_GPV_APB_CSS3_IB_FN_MOD2 . APB_CSS3_IB_FN_MOD2_BYPASS_MERGE
 */
#define  VTSS_F_GPV_APB_CSS3_IB_FN_MOD2_APB_CSS3_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_APB_CSS3_IB_FN_MOD2_APB_CSS3_IB_FN_MOD2_BYPASS_MERGE  VTSS_BIT(0)
#define  VTSS_X_GPV_APB_CSS3_IB_FN_MOD2_APB_CSS3_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_EXTRACT_BITFIELD(x,0,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:APB_CSS3_IB_FN_MOD_ISS_BM
 */
#define VTSS_GPV_APB_CSS3_IB_FN_MOD_ISS_BM   VTSS_IOREG(VTSS_TO_GPV,0x4402)

/**
 * \details
 * Field: ::VTSS_GPV_APB_CSS3_IB_FN_MOD_ISS_BM . APB_CSS3_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM
 */
#define  VTSS_F_GPV_APB_CSS3_IB_FN_MOD_ISS_BM_APB_CSS3_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_APB_CSS3_IB_FN_MOD_ISS_BM_APB_CSS3_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_APB_CSS3_IB_FN_MOD_ISS_BM_APB_CSS3_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:APB_MAIN3_IB_FN_MOD2
 */
#define VTSS_GPV_APB_MAIN3_IB_FN_MOD2        VTSS_IOREG(VTSS_TO_GPV,0x4809)

/**
 * \details
 * Field: ::VTSS_GPV_APB_MAIN3_IB_FN_MOD2 . APB_MAIN3_IB_FN_MOD2_BYPASS_MERGE
 */
#define  VTSS_F_GPV_APB_MAIN3_IB_FN_MOD2_APB_MAIN3_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_APB_MAIN3_IB_FN_MOD2_APB_MAIN3_IB_FN_MOD2_BYPASS_MERGE  VTSS_BIT(0)
#define  VTSS_X_GPV_APB_MAIN3_IB_FN_MOD2_APB_MAIN3_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_EXTRACT_BITFIELD(x,0,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:APB_MAIN3_IB_FN_MOD_ISS_BM
 */
#define VTSS_GPV_APB_MAIN3_IB_FN_MOD_ISS_BM  VTSS_IOREG(VTSS_TO_GPV,0x4802)

/**
 * \details
 * Field: ::VTSS_GPV_APB_MAIN3_IB_FN_MOD_ISS_BM . APB_MAIN3_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM
 */
#define  VTSS_F_GPV_APB_MAIN3_IB_FN_MOD_ISS_BM_APB_MAIN3_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_APB_MAIN3_IB_FN_MOD_ISS_BM_APB_MAIN3_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_APB_MAIN3_IB_FN_MOD_ISS_BM_APB_MAIN3_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:APB_CSS2_IB_FN_MOD2
 */
#define VTSS_GPV_APB_CSS2_IB_FN_MOD2         VTSS_IOREG(VTSS_TO_GPV,0x4c09)

/**
 * \details
 * Field: ::VTSS_GPV_APB_CSS2_IB_FN_MOD2 . APB_CSS2_IB_FN_MOD2_BYPASS_MERGE
 */
#define  VTSS_F_GPV_APB_CSS2_IB_FN_MOD2_APB_CSS2_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_GPV_APB_CSS2_IB_FN_MOD2_APB_CSS2_IB_FN_MOD2_BYPASS_MERGE  VTSS_BIT(0)
#define  VTSS_X_GPV_APB_CSS2_IB_FN_MOD2_APB_CSS2_IB_FN_MOD2_BYPASS_MERGE(x)  VTSS_EXTRACT_BITFIELD(x,0,1)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:APB_CSS2_IB_FN_MOD_ISS_BM
 */
#define VTSS_GPV_APB_CSS2_IB_FN_MOD_ISS_BM   VTSS_IOREG(VTSS_TO_GPV,0x4c02)

/**
 * \details
 * Field: ::VTSS_GPV_APB_CSS2_IB_FN_MOD_ISS_BM . APB_CSS2_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM
 */
#define  VTSS_F_GPV_APB_CSS2_IB_FN_MOD_ISS_BM_APB_CSS2_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_APB_CSS2_IB_FN_MOD_ISS_BM_APB_CSS2_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_APB_CSS2_IB_FN_MOD_ISS_BM_APB_CSS2_IB_FN_MOD_ISS_BM_FN_MOD_ISS_BM(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:CSS2HSS_IB_FN_MOD
 */
#define VTSS_GPV_CSS2HSS_IB_FN_MOD           VTSS_IOREG(VTSS_TO_GPV,0x1842)

/**
 * \details
 * Field: ::VTSS_GPV_CSS2HSS_IB_FN_MOD . CSS2HSS_IB_FN_MOD_FN_MOD
 */
#define  VTSS_F_GPV_CSS2HSS_IB_FN_MOD_CSS2HSS_IB_FN_MOD_FN_MOD(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_CSS2HSS_IB_FN_MOD_CSS2HSS_IB_FN_MOD_FN_MOD     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_CSS2HSS_IB_FN_MOD_CSS2HSS_IB_FN_MOD_FN_MOD(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:PCIE_DBI_IB_FN_MOD
 */
#define VTSS_GPV_PCIE_DBI_IB_FN_MOD          VTSS_IOREG(VTSS_TO_GPV,0x3442)

/**
 * \details
 * Field: ::VTSS_GPV_PCIE_DBI_IB_FN_MOD . PCIE_DBI_IB_FN_MOD_FN_MOD
 */
#define  VTSS_F_GPV_PCIE_DBI_IB_FN_MOD_PCIE_DBI_IB_FN_MOD_FN_MOD(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_PCIE_DBI_IB_FN_MOD_PCIE_DBI_IB_FN_MOD_FN_MOD     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_PCIE_DBI_IB_FN_MOD_PCIE_DBI_IB_FN_MOD_FN_MOD(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


/**
 * \details
 * Register: \a GPV:ADDRESSBLOCK_DEFAULT_0XE8B00000_CA53:GIC400_CFG_IB_FN_MOD
 */
#define VTSS_GPV_GIC400_CFG_IB_FN_MOD        VTSS_IOREG(VTSS_TO_GPV,0x4042)

/**
 * \details
 * Field: ::VTSS_GPV_GIC400_CFG_IB_FN_MOD . GIC400_CFG_IB_FN_MOD_FN_MOD
 */
#define  VTSS_F_GPV_GIC400_CFG_IB_FN_MOD_GIC400_CFG_IB_FN_MOD_FN_MOD(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_GPV_GIC400_CFG_IB_FN_MOD_GIC400_CFG_IB_FN_MOD_FN_MOD     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_GPV_GIC400_CFG_IB_FN_MOD_GIC400_CFG_IB_FN_MOD_FN_MOD(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


#endif /* _VTSS_LAGUNA_REGS_GPV_H_ */
