#! /bin/sh

# Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
# SPDX-License-Identifier: MIT

set -e

MTD=$(cat /proc/mtd | grep Data | sed -r 's/^mtd([0-9]+).*/\1/')
MMC=$(sgdisk -p /dev/mmcblk0 | grep "Data" | sed -r 's/^\s*([0-9]+).*Data/\1/')

if [ -e "/dev/mmcblk0p$MMC" ]; then
    case "$1" in
        start|"")
            if mount /dev/mmcblk0p$MMC /mnt; then
                echo "/dev/mmcblk0p$MMC mounted at /mnt"
            else
                echo "FAILED to mount /dev/mmcblk0p$MMC at /mnt"
            fi
            ;;

        stop)
            umount /mnt
            ;;

        *)
            echo "Usage: S20ubi {start|stop}" >&2
            exit 1
            ;;
    esac

    # Prioritize eMMC over nand/nor
    exit 0
fi


if [ -e "/dev/mtd$MTD" ]; then
    case "$1" in
        start|"")
            if [ -e "/dev/ubi0" ]; then
                echo "UBIFS attached already"
                exit 1
            fi

            ubiattach /dev/ubi_ctrl -m $MTD
            mount -t ubifs ubi0 /mnt
            echo "UBIFS (/dev/mtd$MTD via /dev/ubi0) mounted at /mnt"
            ;;

        stop)
            if [ ! -e "/dev/ubi0" ]; then
                echo "UBIFS not attached"
                exit 1
            fi

            umount /mnt
            ubidetach -p /dev/mtd$MTD
            ;;


        *)
            echo "Usage: S20ubi {start|stop}" >&2
            exit 1
            ;;
    esac

    exit 0
fi

