#! /bin/sh
# Copyright (c) 2004-2019 Microsemi Corporation "Microsemi".
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

MTD=$(cat /proc/mtd | grep Data | sed -r 's/^mtd([0-9]+).*/\1/')
MMC=$(sgdisk -p /dev/mmcblk0 | grep "Data" | sed -r 's/^\s*([0-9]+).*Data/\1/')

if [ -e "/dev/mmcblk0p$MMC" ]; then
    case "$1" in
        start|"")
            if mount /dev/mmcblk0p$MMC /mnt; then
                echo "/dev/mmcblk0p$MMC mounted at /mnt"
            else
                echo "FAILED to mount /dev/mmcblk0p$MMC at /mnt"
            fi
            ;;

        stop)
            umount /mnt
            ;;

        *)
            echo "Usage: S20ubi {start|stop}" >&2
            exit 1
            ;;
    esac

    # Prioritize eMMC over nand/nor
    exit 0
fi


if [ -e "/dev/mtd$MTD" ]; then
    case "$1" in
        start|"")
            if [ -e "/dev/ubi0" ]; then
                echo "UBIFS attached already"
                exit 1
            fi

            ubiattach /dev/ubi_ctrl -m $MTD
            mount -t ubifs ubi0 /mnt
            echo "UBIFS (/dev/mtd$MTD via /dev/ubi0) mounted at /mnt"
            ;;

        stop)
            if [ ! -e "/dev/ubi0" ]; then
                echo "UBIFS not attached"
                exit 1
            fi

            umount /mnt
            ubidetach -p /dev/mtd$MTD
            ;;


        *)
            echo "Usage: S20ubi {start|stop}" >&2
            exit 1
            ;;
    esac

    exit 0
fi

