#! /bin/sh

# Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
# SPDX-License-Identifier: MIT

set -e

case "$1" in
    start|"")
        if [ -x "/mnt/mesa_demo_start" ]; then
            echo "Running: /mnt/mesa_demo_start"
            /mnt/mesa_demo_start
        fi
        ;;

    stop)
        if [ -x "/mnt/mesa_demo_stop" ]; then
            echo "Running: /mnt/mesa_demo_stop"
            /mnt/mesa_demo_stop
        fi
        ;;

    *)
        echo "Usage: 50user {start|stop}" >&2
        exit 1
        ;;
esac


