#! /bin/sh
# Copyright (c) 2004-2019 Microsemi Corporation "Microsemi".
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

case "$1" in
    start|"")
        if [ -x "/mnt/mesa_demo_start" ]; then
            echo "Running: /mnt/mesa_demo_start"
            /mnt/mesa_demo_start
        fi
        ;;

    stop)
        if [ -x "/mnt/mesa_demo_stop" ]; then
            echo "Running: /mnt/mesa_demo_stop"
            /mnt/mesa_demo_stop
        fi
        ;;

    *)
        echo "Usage: 50user {start|stop}" >&2
        exit 1
        ;;
esac


