//-----------------------------------------------------------------------------
// LSD Generator
//-----------------------------------------------------------------------------
// Perl Package        : LSD::generator::targetC (v1.1)
// LSD Source          : /home/p34x/p34x_chip/v_emouchel.priv.p34x_chip.registers/ipg_lsd/lsd_sys/source_32b/xml/reg_files/chip_control/GPHYCDB_FCSI.xml
// Register File Name  : GPHYCDB_FCSI
// Register File Title : CDB FCSI-Interface
// Register Width      : 32
// Note                : Doxygen compliant comments
//-----------------------------------------------------------------------------

#ifndef _GPHYCDB_FCSI_H
#define _GPHYCDB_FCSI_H

//! \defgroup GPHYCDB_FCSI Register File GPHYCDB_FCSI - CDB FCSI-Interface
//! @{

//! Base Address of GPHYCDB_FCSI
#define GPHYCDB_FCSI_MODULE_BASE 0x00D20080u

//! \defgroup GPHYCDB_FCSI_PLLCFG1 Register GPHYCDB_FCSI_PLLCFG1 - PLL Config 1
//! @{

//! Register Offset (relative)
#define GPHYCDB_FCSI_PLLCFG1 0x0
//! Register Offset (absolute) for 1st Instance GPHYCDB_FCSI
#define GPHYCDB_FCSI_GPHYCDB_FCSI_PLLCFG1 0x00D20080u

//! Register Reset Value
#define GPHYCDB_FCSI_PLLCFG1_RST 0x000001FCu

//! Field POSTDIV4 - Post Divider 4
#define GPHYCDB_FCSI_PLLCFG1_POSTDIV4_POS 0
//! Field POSTDIV4 - Post Divider 4
#define GPHYCDB_FCSI_PLLCFG1_POSTDIV4_MASK 0x3u
//! Constant DIV4 - DIVIDE-BY-4
#define CONST_GPHYCDB_FCSI_PLLCFG1_POSTDIV4_DIV4 0x0
//! Constant DIV6 - DIVIDE-BY-6
#define CONST_GPHYCDB_FCSI_PLLCFG1_POSTDIV4_DIV6 0x1
//! Constant DIV8 - DIVIDE-BY-8
#define CONST_GPHYCDB_FCSI_PLLCFG1_POSTDIV4_DIV8 0x2
//! Constant DIV12 - DIVIDE-BY-12
#define CONST_GPHYCDB_FCSI_PLLCFG1_POSTDIV4_DIV12 0x3

//! Field FOUTEN - Frequency Output Enable
#define GPHYCDB_FCSI_PLLCFG1_FOUTEN_POS 2
//! Field FOUTEN - Frequency Output Enable
#define GPHYCDB_FCSI_PLLCFG1_FOUTEN_MASK 0x3Cu
//! Constant FOUT0 - ENABLES OUTPUT FOUT0
#define CONST_GPHYCDB_FCSI_PLLCFG1_FOUTEN_FOUT0 0x1
//! Constant FOUT1 - ENABLES OUTPUT FOUT1
#define CONST_GPHYCDB_FCSI_PLLCFG1_FOUTEN_FOUT1 0x2
//! Constant FOUT2 - ENABLES OUTPUT FOUT2
#define CONST_GPHYCDB_FCSI_PLLCFG1_FOUTEN_FOUT2 0x4
//! Constant FOUT3 - ENABLES OUTPUT FOUT3
#define CONST_GPHYCDB_FCSI_PLLCFG1_FOUTEN_FOUT3 0x8

//! Field FOUTVCOEN - Frequency Output VCO.
#define GPHYCDB_FCSI_PLLCFG1_FOUTVCOEN_POS 6
//! Field FOUTVCOEN - Frequency Output VCO.
#define GPHYCDB_FCSI_PLLCFG1_FOUTVCOEN_MASK 0x40u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_PLLCFG1_FOUTVCOEN_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_PLLCFG1_FOUTVCOEN_ENABLE 0x1

//! Field FOUTDIFFEN - Frequency Output Differential Enable
#define GPHYCDB_FCSI_PLLCFG1_FOUTDIFFEN_POS 7
//! Field FOUTDIFFEN - Frequency Output Differential Enable
#define GPHYCDB_FCSI_PLLCFG1_FOUTDIFFEN_MASK 0x80u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_PLLCFG1_FOUTDIFFEN_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_PLLCFG1_FOUTDIFFEN_ENABLE 0x1

//! Field FOUTCMLEN - Frequency Output CML Enable
#define GPHYCDB_FCSI_PLLCFG1_FOUTCMLEN_POS 8
//! Field FOUTCMLEN - Frequency Output CML Enable
#define GPHYCDB_FCSI_PLLCFG1_FOUTCMLEN_MASK 0x100u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_PLLCFG1_FOUTCMLEN_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_PLLCFG1_FOUTCMLEN_ENABLE 0x1

//! Field FOUTVCOBYP - Frequency Output VCO Bypass
#define GPHYCDB_FCSI_PLLCFG1_FOUTVCOBYP_POS 9
//! Field FOUTVCOBYP - Frequency Output VCO Bypass
#define GPHYCDB_FCSI_PLLCFG1_FOUTVCOBYP_MASK 0x3E00u

//! Field DSMEN - Enable Delta Sigma Modulator
#define GPHYCDB_FCSI_PLLCFG1_DSMEN_POS 14
//! Field DSMEN - Enable Delta Sigma Modulator
#define GPHYCDB_FCSI_PLLCFG1_DSMEN_MASK 0x4000u
//! Constant DISABLE - DSM IS POWERED DOWN (INTEGER MODE)
#define CONST_GPHYCDB_FCSI_PLLCFG1_DSMEN_DISABLE 0x0
//! Constant ENABLE - DSM IS ACTIVE (FRACTIONAL MODE)
#define CONST_GPHYCDB_FCSI_PLLCFG1_DSMEN_ENABLE 0x1

//! Field DACEN - DAC Enable
#define GPHYCDB_FCSI_PLLCFG1_DACEN_POS 15
//! Field DACEN - DAC Enable
#define GPHYCDB_FCSI_PLLCFG1_DACEN_MASK 0x8000u
//! Constant DISABLE - FRACTIONAL NOISE CANCELING DAC IS NOT ACTIVE (TEST MODE ONLY)
#define CONST_GPHYCDB_FCSI_PLLCFG1_DACEN_DISABLE 0x0
//! Constant ENABLE - FRACTIONAL NOISE CANCELING DAC IS ACTIVE (DEFAULT MODE)
#define CONST_GPHYCDB_FCSI_PLLCFG1_DACEN_ENABLE 0x1

//! @}

//! \defgroup GPHYCDB_FCSI_PLLCFG2 Register GPHYCDB_FCSI_PLLCFG2 - PLL Config 2
//! @{

//! Register Offset (relative)
#define GPHYCDB_FCSI_PLLCFG2 0x4
//! Register Offset (absolute) for 1st Instance GPHYCDB_FCSI
#define GPHYCDB_FCSI_GPHYCDB_FCSI_PLLCFG2 0x00D20084u

//! Register Reset Value
#define GPHYCDB_FCSI_PLLCFG2_RST 0x0000068Cu

//! Field POSTDIV0 - Post Divider 0
#define GPHYCDB_FCSI_PLLCFG2_POSTDIV0_POS 0
//! Field POSTDIV0 - Post Divider 0
#define GPHYCDB_FCSI_PLLCFG2_POSTDIV0_MASK 0xFu
//! Constant BYPASS - FREF BYPASSED TO OUTPUT
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV0_BYPASS 0x0
//! Constant DIV2 - DIVIDE BY 2
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV0_DIV2 0x1
//! Constant DIV3 - DIVIDE BY 3
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV0_DIV3 0x2
//! Constant DIV4 - DIVIDE BY 4
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV0_DIV4 0x3
//! Constant DIV5 - DIVIDE BY 5
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV0_DIV5 0x4
//! Constant DIV6 - DIVIDE BY 6
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV0_DIV6 0x5
//! Constant DIV8 - DIVIDE BY 8
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV0_DIV8 0x6
//! Constant DIV10 - DIVIDE BY 10
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV0_DIV10 0x7
//! Constant DIV12 - DIVIDE BY 12
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV0_DIV12 0x8
//! Constant DIV16 - DIVIDE BY 16
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV0_DIV16 0x9
//! Constant DIV20 - DIVIDE BY 20
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV0_DIV20 0xA
//! Constant DIV24 - DIVIDE BY 24
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV0_DIV24 0xB
//! Constant DIV32 - DIVIDE BY 32
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV0_DIV32 0xC
//! Constant DIV40 - DIVIDE BY 40
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV0_DIV40 0xD
//! Constant DIV48 - DIVIDE BY 48
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV0_DIV48 0xE
//! Constant DIV64 - DIVIDE BY 64
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV0_DIV64 0xF

//! Field POSTDIV1 - Post Divider 1
#define GPHYCDB_FCSI_PLLCFG2_POSTDIV1_POS 4
//! Field POSTDIV1 - Post Divider 1
#define GPHYCDB_FCSI_PLLCFG2_POSTDIV1_MASK 0xF0u
//! Constant BYPASS - FREF BYPASSED TO OUTPUT
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV1_BYPASS 0x0
//! Constant DIV2 - DIVIDE BY 2
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV1_DIV2 0x1
//! Constant DIV3 - DIVIDE BY 3
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV1_DIV3 0x2
//! Constant DIV4 - DIVIDE BY 4
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV1_DIV4 0x3
//! Constant DIV5 - DIVIDE BY 5
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV1_DIV5 0x4
//! Constant DIV6 - DIVIDE BY 6
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV1_DIV6 0x5
//! Constant DIV8 - DIVIDE BY 8
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV1_DIV8 0x6
//! Constant DIV10 - DIVIDE BY 10
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV1_DIV10 0x7
//! Constant DIV12 - DIVIDE BY 12
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV1_DIV12 0x8
//! Constant DIV16 - DIVIDE BY 16
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV1_DIV16 0x9
//! Constant DIV20 - DIVIDE BY 20
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV1_DIV20 0xA
//! Constant DIV24 - DIVIDE BY 24
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV1_DIV24 0xB
//! Constant DIV32 - DIVIDE BY 32
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV1_DIV32 0xC
//! Constant DIV40 - DIVIDE BY 40
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV1_DIV40 0xD
//! Constant DIV48 - DIVIDE BY 48
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV1_DIV48 0xE
//! Constant DIV64 - DIVIDE BY 64
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV1_DIV64 0xF

//! Field POSTDIV2 - Post Divider 2
#define GPHYCDB_FCSI_PLLCFG2_POSTDIV2_POS 8
//! Field POSTDIV2 - Post Divider 2
#define GPHYCDB_FCSI_PLLCFG2_POSTDIV2_MASK 0xF00u
//! Constant BYPASS - FREF BYPASSED TO OUTPUT
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV2_BYPASS 0x0
//! Constant DIV2 - DIVIDE BY 2
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV2_DIV2 0x1
//! Constant DIV3 - DIVIDE BY 3
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV2_DIV3 0x2
//! Constant DIV4 - DIVIDE BY 4
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV2_DIV4 0x3
//! Constant DIV5 - DIVIDE BY 5
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV2_DIV5 0x4
//! Constant DIV6 - DIVIDE BY 6
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV2_DIV6 0x5
//! Constant DIV8 - DIVIDE BY 8
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV2_DIV8 0x6
//! Constant DIV10 - DIVIDE BY 10
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV2_DIV10 0x7
//! Constant DIV12 - DIVIDE BY 12
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV2_DIV12 0x8
//! Constant DIV16 - DIVIDE BY 16
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV2_DIV16 0x9
//! Constant DIV20 - DIVIDE BY 20
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV2_DIV20 0xA
//! Constant DIV24 - DIVIDE BY 24
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV2_DIV24 0xB
//! Constant DIV32 - DIVIDE BY 32
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV2_DIV32 0xC
//! Constant DIV40 - DIVIDE BY 40
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV2_DIV40 0xD
//! Constant DIV48 - DIVIDE BY 48
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV2_DIV48 0xE
//! Constant DIV64 - DIVIDE BY 64
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV2_DIV64 0xF

//! Field POSTDIV3 - Post Divider 3
#define GPHYCDB_FCSI_PLLCFG2_POSTDIV3_POS 12
//! Field POSTDIV3 - Post Divider 3
#define GPHYCDB_FCSI_PLLCFG2_POSTDIV3_MASK 0xF000u
//! Constant BYPASS - FREF BYPASSED TO OUTPUT
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV3_BYPASS 0x0
//! Constant DIV2 - DIVIDE BY 2
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV3_DIV2 0x1
//! Constant DIV3 - DIVIDE BY 3
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV3_DIV3 0x2
//! Constant DIV4 - DIVIDE BY 4
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV3_DIV4 0x3
//! Constant DIV5 - DIVIDE BY 5
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV3_DIV5 0x4
//! Constant DIV6 - DIVIDE BY 6
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV3_DIV6 0x5
//! Constant DIV8 - DIVIDE BY 8
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV3_DIV8 0x6
//! Constant DIV10 - DIVIDE BY 10
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV3_DIV10 0x7
//! Constant DIV12 - DIVIDE BY 12
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV3_DIV12 0x8
//! Constant DIV16 - DIVIDE BY 16
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV3_DIV16 0x9
//! Constant DIV20 - DIVIDE BY 20
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV3_DIV20 0xA
//! Constant DIV24 - DIVIDE BY 24
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV3_DIV24 0xB
//! Constant DIV32 - DIVIDE BY 32
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV3_DIV32 0xC
//! Constant DIV40 - DIVIDE BY 40
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV3_DIV40 0xD
//! Constant DIV48 - DIVIDE BY 48
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV3_DIV48 0xE
//! Constant DIV64 - DIVIDE BY 64
#define CONST_GPHYCDB_FCSI_PLLCFG2_POSTDIV3_DIV64 0xF

//! @}

//! \defgroup GPHYCDB_FCSI_PLLCFG3 Register GPHYCDB_FCSI_PLLCFG3 - PLL Config 3
//! @{

//! Register Offset (relative)
#define GPHYCDB_FCSI_PLLCFG3 0x8
//! Register Offset (absolute) for 1st Instance GPHYCDB_FCSI
#define GPHYCDB_FCSI_GPHYCDB_FCSI_PLLCFG3 0x00D20088u

//! Register Reset Value
#define GPHYCDB_FCSI_PLLCFG3_RST 0x00000007u

//! Field CLKOUTREN - Clock output right side enable
#define GPHYCDB_FCSI_PLLCFG3_CLKOUTREN_POS 0
//! Field CLKOUTREN - Clock output right side enable
#define GPHYCDB_FCSI_PLLCFG3_CLKOUTREN_MASK 0x1u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_PLLCFG3_CLKOUTREN_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_PLLCFG3_CLKOUTREN_ENABLE 0x1

//! Field CLKOUTLEN - Clock output left side enable
#define GPHYCDB_FCSI_PLLCFG3_CLKOUTLEN_POS 1
//! Field CLKOUTLEN - Clock output left side enable
#define GPHYCDB_FCSI_PLLCFG3_CLKOUTLEN_MASK 0x2u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_PLLCFG3_CLKOUTLEN_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_PLLCFG3_CLKOUTLEN_ENABLE 0x1

//! Field CLKOUTBEN - Clock output bottom side enable
#define GPHYCDB_FCSI_PLLCFG3_CLKOUTBEN_POS 2
//! Field CLKOUTBEN - Clock output bottom side enable
#define GPHYCDB_FCSI_PLLCFG3_CLKOUTBEN_MASK 0x4u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_PLLCFG3_CLKOUTBEN_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_PLLCFG3_CLKOUTBEN_ENABLE 0x1

//! Field DSKEWCALEN - Deskew calibration enable
#define GPHYCDB_FCSI_PLLCFG3_DSKEWCALEN_POS 3
//! Field DSKEWCALEN - Deskew calibration enable
#define GPHYCDB_FCSI_PLLCFG3_DSKEWCALEN_MASK 0x8u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_PLLCFG3_DSKEWCALEN_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_PLLCFG3_DSKEWCALEN_ENABLE 0x1

//! Field DSKEWCALBYP - Deskew calibration bypass
#define GPHYCDB_FCSI_PLLCFG3_DSKEWCALBYP_POS 4
//! Field DSKEWCALBYP - Deskew calibration bypass
#define GPHYCDB_FCSI_PLLCFG3_DSKEWCALBYP_MASK 0x10u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_PLLCFG3_DSKEWCALBYP_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_PLLCFG3_DSKEWCALBYP_ENABLE 0x1

//! Field DSKEWFASTCAL - Deskew fast calibration enable
#define GPHYCDB_FCSI_PLLCFG3_DSKEWFASTCAL_POS 5
//! Field DSKEWFASTCAL - Deskew fast calibration enable
#define GPHYCDB_FCSI_PLLCFG3_DSKEWFASTCAL_MASK 0x20u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_PLLCFG3_DSKEWFASTCAL_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_PLLCFG3_DSKEWFASTCAL_ENABLE 0x1

//! Field RES0 - Reserved ReadWrite
#define GPHYCDB_FCSI_PLLCFG3_RES0_POS 6
//! Field RES0 - Reserved ReadWrite
#define GPHYCDB_FCSI_PLLCFG3_RES0_MASK 0xFFC0u

//! @}

//! \defgroup GPHYCDB_FCSI_DSKEWCFG Register GPHYCDB_FCSI_DSKEWCFG - Deskew configuration register
//! @{

//! Register Offset (relative)
#define GPHYCDB_FCSI_DSKEWCFG 0xC
//! Register Offset (absolute) for 1st Instance GPHYCDB_FCSI
#define GPHYCDB_FCSI_GPHYCDB_FCSI_DSKEWCFG 0x00D2008Cu

//! Register Reset Value
#define GPHYCDB_FCSI_DSKEWCFG_RST 0x00000000u

//! Field DSKEWCALIN - Deskew calibration input value
#define GPHYCDB_FCSI_DSKEWCFG_DSKEWCALIN_POS 0
//! Field DSKEWCALIN - Deskew calibration input value
#define GPHYCDB_FCSI_DSKEWCFG_DSKEWCALIN_MASK 0xFFFu

//! Field DSKEWCALCNT - Deskew calibration counter.
#define GPHYCDB_FCSI_DSKEWCFG_DSKEWCALCNT_POS 12
//! Field DSKEWCALCNT - Deskew calibration counter.
#define GPHYCDB_FCSI_DSKEWCFG_DSKEWCALCNT_MASK 0x7000u

//! Field RES0 - Reserved ReadWrite
#define GPHYCDB_FCSI_DSKEWCFG_RES0_POS 15
//! Field RES0 - Reserved ReadWrite
#define GPHYCDB_FCSI_DSKEWCFG_RES0_MASK 0x8000u

//! @}

//! \defgroup GPHYCDB_FCSI_DSKEWSTAT Register GPHYCDB_FCSI_DSKEWSTAT - Deskew status register
//! @{

//! Register Offset (relative)
#define GPHYCDB_FCSI_DSKEWSTAT 0x10
//! Register Offset (absolute) for 1st Instance GPHYCDB_FCSI
#define GPHYCDB_FCSI_GPHYCDB_FCSI_DSKEWSTAT 0x00D20090u

//! Register Reset Value
#define GPHYCDB_FCSI_DSKEWSTAT_RST 0x00000000u

//! Field DSKEWCALOUT - Deskew calibration output value
#define GPHYCDB_FCSI_DSKEWSTAT_DSKEWCALOUT_POS 0
//! Field DSKEWCALOUT - Deskew calibration output value
#define GPHYCDB_FCSI_DSKEWSTAT_DSKEWCALOUT_MASK 0xFFFu

//! Field RES0 - Reserved ReadWrite
#define GPHYCDB_FCSI_DSKEWSTAT_RES0_POS 12
//! Field RES0 - Reserved ReadWrite
#define GPHYCDB_FCSI_DSKEWSTAT_RES0_MASK 0xF000u

//! @}

//! \defgroup GPHYCDB_FCSI_VERSION Register GPHYCDB_FCSI_VERSION - Version Register
//! @{

//! Register Offset (relative)
#define GPHYCDB_FCSI_VERSION 0x14
//! Register Offset (absolute) for 1st Instance GPHYCDB_FCSI
#define GPHYCDB_FCSI_GPHYCDB_FCSI_VERSION 0x00D20094u

//! Register Reset Value
#define GPHYCDB_FCSI_VERSION_RST 0x00000100u

//! Field MIN - Minor Version
#define GPHYCDB_FCSI_VERSION_MIN_POS 0
//! Field MIN - Minor Version
#define GPHYCDB_FCSI_VERSION_MIN_MASK 0xFFu

//! Field MAJ - Major Version
#define GPHYCDB_FCSI_VERSION_MAJ_POS 8
//! Field MAJ - Major Version
#define GPHYCDB_FCSI_VERSION_MAJ_MASK 0xFF00u

//! @}

//! \defgroup GPHYCDB_FCSI_RCALSTAT Register GPHYCDB_FCSI_RCALSTAT - RCAL status register
//! @{

//! Register Offset (relative)
#define GPHYCDB_FCSI_RCALSTAT 0x20
//! Register Offset (absolute) for 1st Instance GPHYCDB_FCSI
#define GPHYCDB_FCSI_GPHYCDB_FCSI_RCALSTAT 0x00D200A0u

//! Register Reset Value
#define GPHYCDB_FCSI_RCALSTAT_RST 0x0000000Fu

//! Field RCAL - Rcal resistor calibration output value
#define GPHYCDB_FCSI_RCALSTAT_RCAL_POS 0
//! Field RCAL - Rcal resistor calibration output value
#define GPHYCDB_FCSI_RCALSTAT_RCAL_MASK 0xFu

//! Field FINISHED - Finished bit of resistor calibration
#define GPHYCDB_FCSI_RCALSTAT_FINISHED_POS 4
//! Field FINISHED - Finished bit of resistor calibration
#define GPHYCDB_FCSI_RCALSTAT_FINISHED_MASK 0x10u

//! Field RUNNING - RCAL is running
#define GPHYCDB_FCSI_RCALSTAT_RUNNING_POS 5
//! Field RUNNING - RCAL is running
#define GPHYCDB_FCSI_RCALSTAT_RUNNING_MASK 0x20u

//! Field RES0 - Reserved ReadWrite
#define GPHYCDB_FCSI_RCALSTAT_RES0_POS 6
//! Field RES0 - Reserved ReadWrite
#define GPHYCDB_FCSI_RCALSTAT_RES0_MASK 0xFFC0u

//! @}

//! \defgroup GPHYCDB_FCSI_RCALCFG Register GPHYCDB_FCSI_RCALCFG - RCAL Configuration Register
//! @{

//! Register Offset (relative)
#define GPHYCDB_FCSI_RCALCFG 0x24
//! Register Offset (absolute) for 1st Instance GPHYCDB_FCSI
#define GPHYCDB_FCSI_GPHYCDB_FCSI_RCALCFG 0x00D200A4u

//! Register Reset Value
#define GPHYCDB_FCSI_RCALCFG_RST 0x00000497u

//! Field ICALEN - Calibration Current enable
#define GPHYCDB_FCSI_RCALCFG_ICALEN_POS 0
//! Field ICALEN - Calibration Current enable
#define GPHYCDB_FCSI_RCALCFG_ICALEN_MASK 0x1u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_RCALCFG_ICALEN_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_RCALCFG_ICALEN_ENABLE 0x1

//! Field RCALCLKEN - RCAL clock enable
#define GPHYCDB_FCSI_RCALCFG_RCALCLKEN_POS 1
//! Field RCALCLKEN - RCAL clock enable
#define GPHYCDB_FCSI_RCALCFG_RCALCLKEN_MASK 0x2u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_RCALCFG_RCALCLKEN_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_RCALCFG_RCALCLKEN_ENABLE 0x1

//! Field COMPEN - Comparator enable
#define GPHYCDB_FCSI_RCALCFG_COMPEN_POS 2
//! Field COMPEN - Comparator enable
#define GPHYCDB_FCSI_RCALCFG_COMPEN_MASK 0x4u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_RCALCFG_COMPEN_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_RCALCFG_COMPEN_ENABLE 0x1

//! Field RESET - Reset RCAL
#define GPHYCDB_FCSI_RCALCFG_RESET_POS 3
//! Field RESET - Reset RCAL
#define GPHYCDB_FCSI_RCALCFG_RESET_MASK 0x8u

//! Field START - Start RCAL
#define GPHYCDB_FCSI_RCALCFG_START_POS 4
//! Field START - Start RCAL
#define GPHYCDB_FCSI_RCALCFG_START_MASK 0x10u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_RCALCFG_START_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_RCALCFG_START_ENABLE 0x1

//! Field CLKDIV - Clock divider bits
#define GPHYCDB_FCSI_RCALCFG_CLKDIV_POS 5
//! Field CLKDIV - Clock divider bits
#define GPHYCDB_FCSI_RCALCFG_CLKDIV_MASK 0xE0u
//! Constant DIV1 - DIVIDE-BY-1
#define CONST_GPHYCDB_FCSI_RCALCFG_CLKDIV_DIV1 0x0
//! Constant DIV2 - DIVIDE-BY-2
#define CONST_GPHYCDB_FCSI_RCALCFG_CLKDIV_DIV2 0x1
//! Constant DIV4 - DIVIDE-BY-4
#define CONST_GPHYCDB_FCSI_RCALCFG_CLKDIV_DIV4 0x2
//! Constant DIV8 - DIVIDE-BY-8
#define CONST_GPHYCDB_FCSI_RCALCFG_CLKDIV_DIV8 0x3
//! Constant DIV16 - DIVIDE-BY-16
#define CONST_GPHYCDB_FCSI_RCALCFG_CLKDIV_DIV16 0x4
//! Constant DIV32 - DIVIDE-BY-32
#define CONST_GPHYCDB_FCSI_RCALCFG_CLKDIV_DIV32 0x5
//! Constant DIV64 - DIVIDE-BY-64
#define CONST_GPHYCDB_FCSI_RCALCFG_CLKDIV_DIV64 0x6
//! Constant DIV128 - DIVIDE-BY-128
#define CONST_GPHYCDB_FCSI_RCALCFG_CLKDIV_DIV128 0x7

//! Field INITCNT - Initial counter value
#define GPHYCDB_FCSI_RCALCFG_INITCNT_POS 8
//! Field INITCNT - Initial counter value
#define GPHYCDB_FCSI_RCALCFG_INITCNT_MASK 0xF00u

//! Field RES0 - Reserved ReadWrite
#define GPHYCDB_FCSI_RCALCFG_RES0_POS 12
//! Field RES0 - Reserved ReadWrite
#define GPHYCDB_FCSI_RCALCFG_RES0_MASK 0xF000u

//! @}

//! \defgroup GPHYCDB_FCSI_RCMSTAT Register GPHYCDB_FCSI_RCMSTAT - RC measurement status register
//! @{

//! Register Offset (relative)
#define GPHYCDB_FCSI_RCMSTAT 0x28
//! Register Offset (absolute) for 1st Instance GPHYCDB_FCSI
#define GPHYCDB_FCSI_GPHYCDB_FCSI_RCMSTAT 0x00D200A8u

//! Register Reset Value
#define GPHYCDB_FCSI_RCMSTAT_RST 0x00000000u

//! Field COUNTER - RC measurement counter value.
#define GPHYCDB_FCSI_RCMSTAT_COUNTER_POS 0
//! Field COUNTER - RC measurement counter value.
#define GPHYCDB_FCSI_RCMSTAT_COUNTER_MASK 0x3FFu

//! Field FINISHED - Finished bit of the RC measurement.
#define GPHYCDB_FCSI_RCMSTAT_FINISHED_POS 10
//! Field FINISHED - Finished bit of the RC measurement.
#define GPHYCDB_FCSI_RCMSTAT_FINISHED_MASK 0x400u

//! Field RUNNING - RC measurement is running
#define GPHYCDB_FCSI_RCMSTAT_RUNNING_POS 11
//! Field RUNNING - RC measurement is running
#define GPHYCDB_FCSI_RCMSTAT_RUNNING_MASK 0x800u

//! Field RES0 - Reserved ReadWrite
#define GPHYCDB_FCSI_RCMSTAT_RES0_POS 12
//! Field RES0 - Reserved ReadWrite
#define GPHYCDB_FCSI_RCMSTAT_RES0_MASK 0xF000u

//! @}

//! \defgroup GPHYCDB_FCSI_RCMCFG Register GPHYCDB_FCSI_RCMCFG - RC Measurement Configuration Register
//! @{

//! Register Offset (relative)
#define GPHYCDB_FCSI_RCMCFG 0x2C
//! Register Offset (absolute) for 1st Instance GPHYCDB_FCSI
#define GPHYCDB_FCSI_GPHYCDB_FCSI_RCMCFG 0x00D200ACu

//! Register Reset Value
#define GPHYCDB_FCSI_RCMCFG_RST 0x00000002u

//! Field COMPEN - Comparator enable
#define GPHYCDB_FCSI_RCMCFG_COMPEN_POS 0
//! Field COMPEN - Comparator enable
#define GPHYCDB_FCSI_RCMCFG_COMPEN_MASK 0x1u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_RCMCFG_COMPEN_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_RCMCFG_COMPEN_ENABLE 0x1

//! Field RESET - Reset RC measurement
#define GPHYCDB_FCSI_RCMCFG_RESET_POS 1
//! Field RESET - Reset RC measurement
#define GPHYCDB_FCSI_RCMCFG_RESET_MASK 0x2u
//! Constant NORMAL - NORMAL OPERATION
#define CONST_GPHYCDB_FCSI_RCMCFG_RESET_NORMAL 0x0
//! Constant RESET - RESET FSM.
#define CONST_GPHYCDB_FCSI_RCMCFG_RESET_RESET 0x1

//! Field START - Start RCAL
#define GPHYCDB_FCSI_RCMCFG_START_POS 2
//! Field START - Start RCAL
#define GPHYCDB_FCSI_RCMCFG_START_MASK 0x4u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_RCMCFG_START_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_RCMCFG_START_ENABLE 0x1

//! Field POL - Polarity RC measurement
#define GPHYCDB_FCSI_RCMCFG_POL_POS 3
//! Field POL - Polarity RC measurement
#define GPHYCDB_FCSI_RCMCFG_POL_MASK 0x8u
//! Constant NORMAL - NORMAL POLARITY.
#define CONST_GPHYCDB_FCSI_RCMCFG_POL_NORMAL 0x0
//! Constant REVERSE - REVERSE POLARITY.
#define CONST_GPHYCDB_FCSI_RCMCFG_POL_REVERSE 0x1

//! Field DSMSEL - Digital Speed Monitor Selection
#define GPHYCDB_FCSI_RCMCFG_DSMSEL_POS 4
//! Field DSMSEL - Digital Speed Monitor Selection
#define GPHYCDB_FCSI_RCMCFG_DSMSEL_MASK 0x10u
//! Constant NORMAL - RC MEASUREMENT IS ENABLED.
#define CONST_GPHYCDB_FCSI_RCMCFG_DSMSEL_NORMAL 0x0
//! Constant DSM - DIGITAL SPEED MONITOR IS ENABLED.
#define CONST_GPHYCDB_FCSI_RCMCFG_DSMSEL_DSM 0x1

//! Field RES0 - Reserved ReadWrite
#define GPHYCDB_FCSI_RCMCFG_RES0_POS 5
//! Field RES0 - Reserved ReadWrite
#define GPHYCDB_FCSI_RCMCFG_RES0_MASK 0xFFE0u

//! @}

//! \defgroup GPHYCDB_FCSI_OBSCDB Register GPHYCDB_FCSI_OBSCDB - Configuration Register for the Observation
//! @{

//! Register Offset (relative)
#define GPHYCDB_FCSI_OBSCDB 0x30
//! Register Offset (absolute) for 1st Instance GPHYCDB_FCSI
#define GPHYCDB_FCSI_GPHYCDB_FCSI_OBSCDB 0x00D200B0u

//! Register Reset Value
#define GPHYCDB_FCSI_OBSCDB_RST 0x00000010u

//! Field OTAEN - Operational Tranconductance Amplifier (Buffer) enable
#define GPHYCDB_FCSI_OBSCDB_OTAEN_POS 0
//! Field OTAEN - Operational Tranconductance Amplifier (Buffer) enable
#define GPHYCDB_FCSI_OBSCDB_OTAEN_MASK 0x1u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_OBSCDB_OTAEN_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_OBSCDB_OTAEN_ENABLE 0x1

//! Field BYPASSEN - Bypass the OTA to have a Direct Observation path
#define GPHYCDB_FCSI_OBSCDB_BYPASSEN_POS 1
//! Field BYPASSEN - Bypass the OTA to have a Direct Observation path
#define GPHYCDB_FCSI_OBSCDB_BYPASSEN_MASK 0x2u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_OBSCDB_BYPASSEN_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_OBSCDB_BYPASSEN_ENABLE 0x1

//! Field IPTATSEL - Select the CDB IPTAT 25uA for Observation tests through a direct path (OTA b
#define GPHYCDB_FCSI_OBSCDB_IPTATSEL_POS 2
//! Field IPTATSEL - Select the CDB IPTAT 25uA for Observation tests through a direct path (OTA b
#define GPHYCDB_FCSI_OBSCDB_IPTATSEL_MASK 0x4u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_OBSCDB_IPTATSEL_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_OBSCDB_IPTATSEL_ENABLE 0x1

//! Field IREF50SEL - Select the CDB IREF 50uA for Observation tests through a direct path
#define GPHYCDB_FCSI_OBSCDB_IREF50SEL_POS 3
//! Field IREF50SEL - Select the CDB IREF 50uA for Observation tests through a direct path
#define GPHYCDB_FCSI_OBSCDB_IREF50SEL_MASK 0x8u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_OBSCDB_IREF50SEL_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_OBSCDB_IREF50SEL_ENABLE 0x1

//! Field RESDIVEN - Enables the resistance divider's switch to GND for 1V8 observation, no matte
#define GPHYCDB_FCSI_OBSCDB_RESDIVEN_POS 4
//! Field RESDIVEN - Enables the resistance divider's switch to GND for 1V8 observation, no matte
#define GPHYCDB_FCSI_OBSCDB_RESDIVEN_MASK 0x10u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_OBSCDB_RESDIVEN_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_OBSCDB_RESDIVEN_ENABLE 0x1

//! Field BGPSEL - Select the CDB BGP0V45 for Observation tests
#define GPHYCDB_FCSI_OBSCDB_BGPSEL_POS 5
//! Field BGPSEL - Select the CDB BGP0V45 for Observation tests
#define GPHYCDB_FCSI_OBSCDB_BGPSEL_MASK 0x20u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_OBSCDB_BGPSEL_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_OBSCDB_BGPSEL_ENABLE 0x1

//! Field OBSPEN - Closes the switch on the OBS_P bus before the OTA (buffer)
#define GPHYCDB_FCSI_OBSCDB_OBSPEN_POS 6
//! Field OBSPEN - Closes the switch on the OBS_P bus before the OTA (buffer)
#define GPHYCDB_FCSI_OBSCDB_OBSPEN_MASK 0x40u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_OBSCDB_OBSPEN_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_OBSCDB_OBSPEN_ENABLE 0x1

//! Field VREGSEL - Select the CDB VREG1V8 voltage for Observation tests
#define GPHYCDB_FCSI_OBSCDB_VREGSEL_POS 7
//! Field VREGSEL - Select the CDB VREG1V8 voltage for Observation tests
#define GPHYCDB_FCSI_OBSCDB_VREGSEL_MASK 0x80u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_OBSCDB_VREGSEL_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_OBSCDB_VREGSEL_ENABLE 0x1

//! Field RES0 - Reserved ReadWrite
#define GPHYCDB_FCSI_OBSCDB_RES0_POS 8
//! Field RES0 - Reserved ReadWrite
#define GPHYCDB_FCSI_OBSCDB_RES0_MASK 0xFF00u

//! @}

//! \defgroup GPHYCDB_FCSI_BIASCFG Register GPHYCDB_FCSI_BIASCFG - Bias Configuration Register
//! @{

//! Register Offset (relative)
#define GPHYCDB_FCSI_BIASCFG 0x34
//! Register Offset (absolute) for 1st Instance GPHYCDB_FCSI
#define GPHYCDB_FCSI_GPHYCDB_FCSI_BIASCFG 0x00D200B4u

//! Register Reset Value
#define GPHYCDB_FCSI_BIASCFG_RST 0x00000406u

//! Field RES0 - Reserved ReadWrite
#define GPHYCDB_FCSI_BIASCFG_RES0_POS 0
//! Field RES0 - Reserved ReadWrite
#define GPHYCDB_FCSI_BIASCFG_RES0_MASK 0x1u

//! Field IREFEN - Reference Current Enable
#define GPHYCDB_FCSI_BIASCFG_IREFEN_POS 1
//! Field IREFEN - Reference Current Enable
#define GPHYCDB_FCSI_BIASCFG_IREFEN_MASK 0x2u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_BIASCFG_IREFEN_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_BIASCFG_IREFEN_ENABLE 0x1

//! Field IPTATEN - Iptat Current Enable
#define GPHYCDB_FCSI_BIASCFG_IPTATEN_POS 2
//! Field IPTATEN - Iptat Current Enable
#define GPHYCDB_FCSI_BIASCFG_IPTATEN_MASK 0x4u
//! Constant DISABLE - FUNCTION IS DISABLED
#define CONST_GPHYCDB_FCSI_BIASCFG_IPTATEN_DISABLE 0x0
//! Constant ENABLE - FUNCTION IS ENABLED
#define CONST_GPHYCDB_FCSI_BIASCFG_IPTATEN_ENABLE 0x1

//! Field VREFTRIM - Vref Trimming
#define GPHYCDB_FCSI_BIASCFG_VREFTRIM_POS 3
//! Field VREFTRIM - Vref Trimming
#define GPHYCDB_FCSI_BIASCFG_VREFTRIM_MASK 0x78u
//! Constant V449MV6 - 449.6 MV VREF OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_BIASCFG_VREFTRIM_V449MV6 0x0
//! Constant V448MV2 - 448.2 MV VREF OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_BIASCFG_VREFTRIM_V448MV2 0x1
//! Constant V446MV8 - 446.8 MV VREF OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_BIASCFG_VREFTRIM_V446MV8 0x2
//! Constant V445MV4 - 445.4 MV VREF OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_BIASCFG_VREFTRIM_V445MV4 0x3
//! Constant V444MV0 - 444.0 MV VREF OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_BIASCFG_VREFTRIM_V444MV0 0x4
//! Constant V442MV6 - 442.6 MV VREF OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_BIASCFG_VREFTRIM_V442MV6 0x5
//! Constant V441MV2 - 441.2 MV VREF OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_BIASCFG_VREFTRIM_V441MV2 0x6
//! Constant V439MV8 - 439.8 MV VREF OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_BIASCFG_VREFTRIM_V439MV8 0x7
//! Constant V460MV8 - 460.8 MV VREF OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_BIASCFG_VREFTRIM_V460MV8 0x8
//! Constant V459MV4 - 459.4 MV VREF OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_BIASCFG_VREFTRIM_V459MV4 0x9
//! Constant V458MV0 - 458.0 MV VREF OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_BIASCFG_VREFTRIM_V458MV0 0xA
//! Constant V456MV6 - 456.6 MV VREF OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_BIASCFG_VREFTRIM_V456MV6 0xB
//! Constant V455MV2 - 455.2 MV VREF OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_BIASCFG_VREFTRIM_V455MV2 0xC
//! Constant V453MV8 - 453.8 MV VREF OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_BIASCFG_VREFTRIM_V453MV8 0xD
//! Constant V452MV4 - 452.4 MV VREF OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_BIASCFG_VREFTRIM_V452MV4 0xE
//! Constant V451MV0 - 451.0 MV VREF OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_BIASCFG_VREFTRIM_V451MV0 0xF

//! Field IPTATPROG - Iptat Programming
#define GPHYCDB_FCSI_BIASCFG_IPTATPROG_POS 7
//! Field IPTATPROG - Iptat Programming
#define GPHYCDB_FCSI_BIASCFG_IPTATPROG_MASK 0x780u

//! Field RES1 - Reserved ReadWrite
#define GPHYCDB_FCSI_BIASCFG_RES1_POS 11
//! Field RES1 - Reserved ReadWrite
#define GPHYCDB_FCSI_BIASCFG_RES1_MASK 0xF800u

//! @}

//! \defgroup GPHYCDB_FCSI_VREGCFG Register GPHYCDB_FCSI_VREGCFG - Voltage regulator configuration register
//! @{

//! Register Offset (relative)
#define GPHYCDB_FCSI_VREGCFG 0x38
//! Register Offset (absolute) for 1st Instance GPHYCDB_FCSI
#define GPHYCDB_FCSI_GPHYCDB_FCSI_VREGCFG 0x00D200B8u

//! Register Reset Value
#define GPHYCDB_FCSI_VREGCFG_RST 0x00000000u

//! Field RES0 - Reserved ReadWrite
#define GPHYCDB_FCSI_VREGCFG_RES0_POS 0
//! Field RES0 - Reserved ReadWrite
#define GPHYCDB_FCSI_VREGCFG_RES0_MASK 0x1u

//! Field VREGLP - Vreg Low Power Enable
#define GPHYCDB_FCSI_VREGCFG_VREGLP_POS 1
//! Field VREGLP - Vreg Low Power Enable
#define GPHYCDB_FCSI_VREGCFG_VREGLP_MASK 0x2u
//! Constant NORMAL - NORMAL OPERATION.
#define CONST_GPHYCDB_FCSI_VREGCFG_VREGLP_NORMAL 0x0
//! Constant LOWPOWER - LOW POWER OPERATION.
#define CONST_GPHYCDB_FCSI_VREGCFG_VREGLP_LOWPOWER 0x1

//! Field VREGPROG - Vreg Voltage Programming
#define GPHYCDB_FCSI_VREGCFG_VREGPROG_POS 2
//! Field VREGPROG - Vreg Voltage Programming
#define GPHYCDB_FCSI_VREGCFG_VREGPROG_MASK 0x1Cu
//! Constant V1V80 - 1.80 V REG. OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_VREGCFG_VREGPROG_V1V80 0x0
//! Constant V1V83 - 1.83 V REG. OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_VREGCFG_VREGPROG_V1V83 0x1
//! Constant V1V86 - 1.86 V REG. OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_VREGCFG_VREGPROG_V1V86 0x2
//! Constant V1V89 - 1.89 V REG. OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_VREGCFG_VREGPROG_V1V89 0x3
//! Constant V1V68 - 1.68 V REG. OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_VREGCFG_VREGPROG_V1V68 0x4
//! Constant V1V71 - 1.71 V REG. OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_VREGCFG_VREGPROG_V1V71 0x5
//! Constant V1V74 - 1.74 V REG. OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_VREGCFG_VREGPROG_V1V74 0x6
//! Constant V1V77 - 1.77 V REG. OUTPUT VOLTAGE
#define CONST_GPHYCDB_FCSI_VREGCFG_VREGPROG_V1V77 0x7

//! Field RES1 - Reserved ReadWrite
#define GPHYCDB_FCSI_VREGCFG_RES1_POS 5
//! Field RES1 - Reserved ReadWrite
#define GPHYCDB_FCSI_VREGCFG_RES1_MASK 0xFFE0u

//! @}

//! @}

#endif
