:sectnums:
== Trace

The API provides a trace system, which may be controlled and mapped into the
trace system of the application software. Trace macros inside the API have these
properties:

* Trace layer (`mesa_trace_layer_t`)
* Trace group (`mesa_trace_group_t`)
* Trace level (`mesa_trace_level_t`)

The current trace level can be controlled per group and layer
(`mesa_trace_conf_t`). Trace levels may be changed before initialization for
debugging the startup. The application software must implement functions, which
are called for enabled trace macros in the API (`mesa_callout_trace_printf()`
and `mesa_callout_trace_hex_dump()`).

== Debug Print

The API offers a tool for printing the internal state of the API and the device.
The output may be limited to a specific layer, group and other filtering options
(`mesa_debug_info_t`). The application software must provide a function for
printing the output (`mesa_debug_printf_t`). To allow other API calls during
printing, this function may unlock the API (`mesa_debug_unlock()`) before
printing and then lock the API again (`mesa_debug_lock()`).

== Register Access

For debug purposes, device registers can be accessed (`mesa_reg_read()` and
`mesa_reg_write()`). For register access using symbolic names, a database of the
register set is available (`mesa_symreg_data_get()`).

== Interrupts, Events and Polling
TBD

== GPIOs

The mode of each GPIO on the device can be controlled (`mesa_gpio_mode_t`). It
is possible to read from a input GPIOs (`mesa_gpio_read()`) and write to output
GPIOs (`mesa_gpio_write()`).

The function of Serial GPIOs (SGPIOs) can also be controlled (`mesa_sgpio_conf_t`).
SGPIO data can be read (`mesa_sgpio_read()`).

== Fan Control

For temperature control, the temperature can be read (`mesa_temp_sensor_get()`)
and a fan controller connected to GPIO pins can be setup (`mesa_fan_conf_t`).

== Energy Efficient Ethernet

Energy Efficient Ethernet (EEE) can enabled per port to reduce power consumption (`mesa_eee_port_conf_t`).

== API Functions

// AWN: I'm not sure I see the value of mention functions that does not even
// relates to something which is explained.

`mesa_trace_conf_get()` +
`mesa_trace_conf_set()` +
`mesa_debug_info_get()` +
`mesa_debug_info_print()` +
`mesa_debug_lock()` +
`mesa_debug_unlock()` +
`mesa_reg_read()` +
`mesa_reg_write()` +
`mesa_reg_write_masked()` +
`mesa_intr_sticky_clear()` +
`mesa_chip_id_get()` +
`mesa_poll_1sec()` +
`mesa_ptp_event_poll()` +
`mesa_ptp_event_enable()` +
`mesa_dev_all_event_poll()` +
`mesa_dev_all_event_enable()` +
`mesa_gpio_mode_set()` +
`mesa_gpio_direction_set()` +
`mesa_gpio_read()` +
`mesa_gpio_write()` +
`mesa_gpio_event_poll()` +
`mesa_gpio_event_enable()` +
`mesa_sgpio_conf_get()` +
`mesa_sgpio_conf_set()` +
`mesa_sgpio_read()` +
`mesa_sgpio_event_poll()` +
`mesa_sgpio_event_enable()` +
`mesa_intr_cfg()` +
`mesa_intr_mask_set()` +
`mesa_intr_status_get()` +
`mesa_intr_pol_negation()` +
`mesa_irq_conf_get()` +
`mesa_irq_conf_set()` +
`mesa_irq_status_get_and_mask()` +
`mesa_irq_enable()` +
`mesa_temp_sensor_init()` +
`mesa_temp_sensor_get()` +
`mesa_fan_rotation_get()` +
`mesa_fan_cool_lvl_set()` +
`mesa_fan_controller_init()` +
`mesa_fan_cool_lvl_get()` +
`mesa_eee_port_conf_set()` +
`mesa_symreg_data_get()`
