// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

:sectnums:
Frames can be transferred to/from the CPU in one of the following ways:

* Frame DMA: The FDMA engine of the device is used to transfer frames via the DDR/PCIe interface.
* NPI Port: One of the Ethernet ports of the device is used for CPU frame transfers.
* Manual: Frame transfers are done using device register accesses.

Transferred frames include an Internal Frame Header (IFH):

* CPU Rx: The IFH is called an extraction header (size `MESA_CAP_PACKET_RX_IFH_SIZE`).
* CPU Tx: The IFH is called an injection header (size `MESA_CAP_PACKET_TX_IFH_SIZE`).

The IFH includes additional information such as ingress/egress port and classified VID.

// AWN: What are the pros/cons? How to choose?
// CPJ: This is a system archictecture decision, not sure it belongs here.

== Frame DMA
Frame DMA is provided via a Linux driver, which always places the IFH at offset 16.

== NPI Port
One of the Ethernet ports can be enabled as NPI port (`mesa_npi_conf_t`).
The placement of the IFH depends on the device:

* The IFH is at offset 0 if the capability `MESA_CAP_PACKET_RX_IFH_SIZE` is 8.
* The IFH if at offset 16 if the capability `MESA_CAP_PACKET_RX_IFH_SIZE` is not 8.

When setting up the CPU Rx queue system of the device, each queue can be enabled
for NPI port redirection (`mesa_packet_rx_queue_npi_conf_t`).

== Manual Transfers
The API provides functions for manual transfers:

* Rx frame (`mesa_packet_rx_frame()`)
* Tx frame (`mesa_packet_tx_frame()`).

== CPU Rx Registration
Received frames can be sent to the CPU in multiple ways:

* Via MAC address table entries (`mesa_mac_table_entry_t`).
* Via learn mode (`mesa_learn_mode_t`).
* Via sFlow sampling (`mesa_sflow_port_conf_t`).
* Via ACL actions (`mesa_acl_action_t`).
* Via router legs (`mesa_l3_rleg_conf_t`) and routing setup.
* Via the Versatile OAM Processor (`mesa_vop_conf_t`).
* Via packet registrations (`mesa_packet_rx_reg_t` and `mesa_packet_rx_port_conf_t`).

Mapping to CPU Rx queue is done via the functions above or the CPU Rx queue mapping (`mesa_packet_rx_queue_map_t`).
The CPU Rx queue system is setup with strict priority using queue 0 as lowest priority and queue 7 as highest priority.
This can be used to prioritize between frames to the CPU.

== CPU Rx/Tx Processing
API functions are available for Rx/Tx frame processing:

* Decode extraction header (`mesa_packet_rx_hdr_decode()`).
* Encode injection header (`mesa_packet_tx_hdr_encode()`).
* Ingress and/or egress filtering information for one egress port (`mesa_packet_frame_filter()`).
* Ingress and/or egress filtering information for all egress ports (`mesa_packet_port_filter_get()`).

The ingress/egress filtering functions can for example be used for IGMP snooping.
IGMP frames may be redirected to the CPU by the device even though the ingress
port is in STP discarding state. In that case, `mesa_packet_frame_filter()` can
be used to determine if the frame must be discarded by the CPU.
When forwarding IGMP frames to other ports, (`mesa_packet_port_filter_get()`)
can be used to avoid forwarding back to ports in the same aggregation.
It is also possible to determine whether to add a VLAN tag for each egress port.

== Automatic Frame Injection
The Automatic Frame Injection (AFI) feature allows for periodic transmission of frames from within the switch core.

=== AFIv1
This section describes the AFI functionality for devices with a non-zero `MESA_CAP_AFI_V1` capability.
The flow for setting up a frame to be periodically transmitted is as follows:

* Allocate resources for AFI frame using `mesa_afi_alloc()`, which returns an AFI ID.
* From the CPU, transmit the frame with the AFI ID encoded in the IFH (`mesa_packet_tx_info_t::afi_id`).
* Optionally, call `mesa_afi_hijack()` to check whether the frame was actually captured by the AFI in the device.
* To cancel the frame transmission, call `mesa_afi_free()`.
* If the egress port for the frame transmissions goes down, transmissions will be stopped.
When the port comes up again, the CPU must transmit the frame again to restart transmissions.

=== AFIv2
This section describes the AFI functionality for devices with a non-zero `MESA_CAP_AFI_V2` capability.
Two types of AFI injections are supported:

* Fast injections: Injection of a sequence of frames consisting of one or more frames with rates of up
to several Gbps.
* Slow injections: Typically used for injecting single frames with an interval of approximately 3.3ms or slower.

Fast injections are used as follows:

* Allocate resources for AFI using `mesa_afi_fast_inj_alloc()`, which returns an AFI ID.
* For each frame in the sequence do the following:
** From the CPU, transmit the frame with the AFI ID encoded in the IFH (`mesa_packet_tx_info_t::afi_id`).
** Call `mesa_afi_fast_inj_frm_hijack()` to configure the frame for injection.
* Call `mesa_afi_fast_inj_start()` to select bandwidth and start injection.
* Call `mesa_afi_fast_inj_stop()` to stop injection.
* Call `mesa_afi_fast_inj_free()` to free allocated resources.

Slow injections are used as follows:

* Allocate resources for AFI using `mesa_afi_slow_inj_alloc()`, which returns an AFI ID.
* From the CPU, transmit the frame with the AFI ID encoded in the IFH (`mesa_packet_tx_info_t::afi_id`).
* Call `mesa_afi_slow_inj_frm_hijack()` to configure the frame for injection.
* Call `mesa_afi_slow_inj_start()` to start injection.
* Call `mesa_afi_slow_inj_stop()` to stop injection.
* Call `mesa_afi_slow_inj_free()` to free allocated resources.

If the egress port goes down, all injections (slow as well as fast) are automatically stopped.
When the port comes up again, injections are restarted.

== API Functions
`mesa_npi_conf_get()` +
`mesa_npi_conf_set()` +
`mesa_packet_rx_conf_get()` +
`mesa_packet_rx_conf_set()` +
`mesa_packet_rx_port_conf_get()` +
`mesa_packet_rx_port_conf_set()` +
`mesa_packet_frame_filter()` +
`mesa_packet_port_info_init()` +
`mesa_packet_port_filter_get()` +
`mesa_packet_vlan_filter_get()` +
`mesa_packet_vlan_status_get()` +
`mesa_packet_rx_hdr_decode()` +
`mesa_packet_tx_hdr_encode()` +
`mesa_packet_tx_info_init()` +
`mesa_packet_tx_frame()` +
`mesa_packet_rx_frame()` +
`mesa_packet_phy_cnt_to_ts_cnt()` +
`mesa_packet_ns_to_ts_cnt()` +
`mesa_ptp_get_timestamp()` +
`mesa_afi_alloc()` +
`mesa_afi_free()` +
`mesa_afi_hijack()` +
`mesa_afi_fast_inj_alloc()` +
`mesa_afi_fast_inj_free()` +
`mesa_afi_fast_inj_frm_hijack()` +
`mesa_afi_fast_inj_start()` +
`mesa_afi_fast_inj_stop()` +
`mesa_afi_fast_inj_seq_cnt_get()` +
`mesa_afi_slow_inj_alloc()` +
`mesa_afi_slow_inj_free()` +
`mesa_afi_slow_inj_frm_hijack()` +
`mesa_afi_slow_inj_start()` +
`mesa_afi_slow_inj_stop()` +
`mesa_afi_port_start()` +
`mesa_afi_port_stop()`
