// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

#include "vtss_fa_cil.h"
#if defined(VTSS_ARCH_FA)
// Run time constants
static unsigned int fa_chip_const[] = {
    [__RT_CHIP_PORTS] = 65,
    [__RT_SERDES_10G_START] = 13,
    [__RT_SERDES_25G_START] = 25,
    [__RT_SERDES_CNT] = 33,
    [__RT_CMU_CNT] = 14,
    [__RT_BUFFER_MEMORY] = 4194280,
    [__RT_BUFFER_REFERENCE] = 22795,
    [__RT_RES_CFG_MAX_PORT_IDX] = 560,
    [__RT_RES_CFG_MAX_PRIO_IDX] = 630,
    [__RT_RES_CFG_MAX_COLOUR_IDX] = 638,
    [__RT_CORE_QUEUE_CNT] = 40460,
    [__RT_TAS_NUMBER_OF_LISTS] = (0x7F+1),
    [__RT_TAS_NUMBER_OF_PROFILES] = 100,
    [__RT_TAS_NUMBER_OF_ENTRIES] = (0x3FFF+1),
    [__RT_EVC_POL_CNT] = 4096,
    [__RT_EVC_STAT_CNT] = 8192,
    [__RT_SDX_CNT] = 4095,
    [__RT_HSCH_LAYERS] = 4,
    [__RT_HSCH_L0_SES] = 5040,
    [__RT_HSCH_L1_SES] = 64,
    [__RT_HSCH_L2_SES] = 70,
    [__RT_HSCH_L3_QSHPS] = 5040 * 2,
    [__RT_HSCH_MAX_RATE_GROUP_0] = 1048568,
    [__RT_HSCH_MAX_RATE_GROUP_1] = 2621420,
    [__RT_HSCH_MAX_RATE_GROUP_2] = 10485680,
    [__RT_HSCH_MAX_RATE_GROUP_3] = 26214200,
    [__RT_HSCH_MAX_RATE_QSHP_GROUP_0] = 0,
    [__RT_HSCH_MAX_RATE_QSHP_GROUP_1] = 0,
    [__RT_HSCH_MAX_RATE_QSHP_GROUP_2] = 0,
    [__RT_HSCH_MAX_RATE_QSHP_GROUP_3] = 0,
    [__RT_LB_GROUP_CNT] = 10,
    [__RT_LB_SET_CNT] = 4615,
    [__RT_MSTREAM_CNT] = 1024,
    [__RT_CSTREAM_CNT] = 512,
    [__RT_AFI_SLOW_INJ_CNT] = 4096,
    [__RT_MAC_ADDRS] = 8192,
    [__RT_PATH_SERVICE_VOE_CNT] = 1024,
    [__RT_PORT_VOE_BASE_IDX] = 1024,
    [__RT_PORT_VOE_CNT] = 65,
    [__RT_DOWN_VOI_CNT] = 1024,
    [__RT_UP_VOI_CNT] = 1023,
    [__RT_ACL_CNT_SIZE] = 4096,
    [__RT_ES2_CNT_SIZE] = 2048,
    [__RT_ES0_CNT] = 4096,
    [__RT_ES2_CNT] = 2048,
    [__RT_FA_ES2_CNT] = 1024,
    [__RT_IP6PFX_CNT] = 512,
    [__RT_VCAP_SUPER_BLK_CNT] = 10,
    [__RT_QOS_INGRESS_MAP_IDS] = 256,
    [__RT_QOS_EGRESS_MAP_IDS] = 512,
    [__RT_PGID_FA] = (2048 + 65),
    [__RT_MAC_INDEX_CNT] = 2048,
    [__RT_DSM_CAL_MAX_DEVS_PER_TAXI] = 13,
    [__RT_DSM_CAL_TAXIS] = 8,
    [__RT_EXT_CLK_PIN] = 1,
    [__RT_ALT_LDST_PIN] = 2,
    [__RT_ALT_PPS_PIN] = 3,
    [__RT_TOD_ACC_PIN] = 4,
};


static unsigned int la_chip_const[] = {
    [__RT_CHIP_PORTS] = 30,
    [__RT_SERDES_10G_START] = 0,
    [__RT_SERDES_25G_START] = 0,
    [__RT_SERDES_CNT] = 10,
    [__RT_CMU_CNT] = 6,
    [__RT_BUFFER_MEMORY] = 1572864,
    [__RT_BUFFER_REFERENCE] = 8548,
    [__RT_RES_CFG_MAX_PORT_IDX] = 280,
    [__RT_RES_CFG_MAX_PRIO_IDX] = 315,
    [__RT_RES_CFG_MAX_COLOUR_IDX] = 323,
    [__RT_CORE_QUEUE_CNT] = 9030,
    [__RT_TAS_NUMBER_OF_LISTS] = 60,
    [__RT_TAS_NUMBER_OF_PROFILES] = 60,
    [__RT_TAS_NUMBER_OF_ENTRIES] = (0x1FFF+1),
    [__RT_EVC_POL_CNT] = 256,
    [__RT_EVC_STAT_CNT] = 1024,
    [__RT_SDX_CNT] = 1023,
    [__RT_HSCH_LAYERS] = 4,
    [__RT_HSCH_L0_SES] = 1120,
    [__RT_HSCH_L1_SES] = 32,
    [__RT_HSCH_L2_SES] = 35,
    [__RT_HSCH_L3_QSHPS] = 1120,
    [__RT_HSCH_MAX_RATE_GROUP_0] = 655355,
    [__RT_HSCH_MAX_RATE_GROUP_1] = 1048568,
    [__RT_HSCH_MAX_RATE_GROUP_2] = 6553550,
    [__RT_HSCH_MAX_RATE_GROUP_3] = 10485680,
    [__RT_HSCH_MAX_RATE_QSHP_GROUP_0] = 1048568,
    [__RT_HSCH_MAX_RATE_QSHP_GROUP_1] = 2621420,
    [__RT_HSCH_MAX_RATE_QSHP_GROUP_2] = 6553550,
    [__RT_HSCH_MAX_RATE_QSHP_GROUP_3] = 10485680,
    [__RT_LB_GROUP_CNT] = 5,
    [__RT_LB_SET_CNT] = 496,
    [__RT_MSTREAM_CNT] = 256,
    [__RT_CSTREAM_CNT] = 128,
    [__RT_AFI_SLOW_INJ_CNT] = 512,
    [__RT_MAC_ADDRS] = 16384,
    [__RT_PATH_SERVICE_VOE_CNT] = 32,
    [__RT_PORT_VOE_BASE_IDX] = 32,
    [__RT_PORT_VOE_CNT] = 30,
    [__RT_DOWN_VOI_CNT] = 32,
    [__RT_UP_VOI_CNT] = 31,
    [__RT_ACL_CNT_SIZE] = 1024,
    [__RT_ES2_CNT_SIZE] = 512,
    [__RT_ES0_CNT] = 1536,
    [__RT_ES2_CNT] = 512,
    [__RT_FA_ES2_CNT] = 256,
    [__RT_IP6PFX_CNT] = 256,
    [__RT_VCAP_SUPER_BLK_CNT] = 6,
    [__RT_QOS_INGRESS_MAP_IDS] = 64,
    [__RT_QOS_EGRESS_MAP_IDS] = 128,
    [__RT_PGID_FA] = (1024 + 30),
    [__RT_MAC_INDEX_CNT] = 4096,
    [__RT_DSM_CAL_MAX_DEVS_PER_TAXI] = 10,
    [__RT_DSM_CAL_TAXIS] = 5,
    [__RT_EXT_CLK_PIN] = 4,
    [__RT_ALT_LDST_PIN] = 5,
    [__RT_ALT_PPS_PIN] = 4,
    [__RT_TOD_ACC_PIN] = 7,
};

// Register assignment _END_
void fla_init_const(vtss_state_t *vtss_state, BOOL fa)
{
    vtss_state->chip_const = fa ? fa_chip_const : la_chip_const;
}

#endif // defined(VTSS_ARCH_FA)
