// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT


#ifndef _VTSS_FA_REGS_H_
#define _VTSS_FA_REGS_H_

#include "vtss_fa_regs_afi.h"
#include "vtss_fa_regs_ana_ac.h"
#include "vtss_fa_regs_ana_ac_oam_mod.h"
#include "vtss_fa_regs_ana_ac_pol.h"
#include "vtss_fa_regs_ana_ac_sdlb.h"
#include "vtss_fa_regs_ana_acl.h"
#include "vtss_fa_regs_ana_cl.h"
#include "vtss_fa_regs_ana_l2.h"
#include "vtss_fa_regs_ana_l3.h"
#include "vtss_fa_regs_asm.h"
#include "vtss_fa_regs_chip_top.h"
#include "vtss_fa_regs_clkgen.h"
#include "vtss_fa_regs_dev10g.h"
#include "vtss_fa_regs_dev1g.h"
#include "vtss_fa_regs_devcpu_gcb.h"
#include "vtss_fa_regs_devcpu_org.h"
#include "vtss_fa_regs_devcpu_ptp.h"
#include "vtss_fa_regs_devcpu_qs.h"
#include "vtss_fa_regs_dsm.h"
#include "vtss_fa_regs_eacl.h"
#include "vtss_fa_regs_hsch.h"
#include "vtss_fa_regs_hsiowrap.h"
#include "vtss_fa_regs_lcpll28.h"
#include "vtss_fa_regs_lrn.h"
#include "vtss_fa_regs_pciephywrap.h"
#include "vtss_fa_regs_pcs_10gbase_r.h"
#include "vtss_fa_regs_pcs25g_rsfec.h"
#include "vtss_fa_regs_port_conf.h"
#include "vtss_fa_regs_qfwd.h"
#include "vtss_fa_regs_qres.h"
#include "vtss_fa_regs_qsys.h"
#include "vtss_fa_regs_rew.h"
#include "vtss_fa_regs_sd10g_cmu_target.h"
#include "vtss_fa_regs_sd_cmu_nonterm_target.h"
#include "vtss_fa_regs_sd_cmu_term_target.h"
#include "vtss_fa_regs_sd10g_lane_target.h"
#include "vtss_fa_regs_ip_kraneg_notr.h"
#include "vtss_fa_regs_ip_kraneg.h"
#include "vtss_fa_regs_sd_lane_target.h"
#include "vtss_fa_regs_sd25g_target.h"
#include "vtss_fa_regs_sd25g_cfg_target.h"
#include "vtss_fa_regs_sdpcie_pma.h"
#include "vtss_fa_regs_vcap_es0.h"
#include "vtss_fa_regs_vcap_es2.h"
#include "vtss_fa_regs_vcap_ip6pfx.h"
#include "vtss_fa_regs_vcap_super.h"
#include "vtss_fa_regs_vop.h"
#include "vtss_fa_regs_vop_l3.h"
#include "vtss_fa_regs_vop_mpls.h"
#include "vtss_fa_regs_xqs.h"

#endif /* _VTSS_FA_REGS_H_ */
