// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

#ifndef _VTSS_FA_TS_H_
#define _VTSS_FA_TS_H_

#if defined(VTSS_ARCH_LAN969X)

/* Convert SPARX5 PTP register defines to Laguna defines */

#define VTSS_DEVCPU_PTP_PTP_PIN_CFG(x)                           VTSS_PTP_PTP_PIN_CFG(x)
#define VTSS_F_DEVCPU_PTP_PTP_PIN_CFG_PTP_PIN_ACTION(x)          VTSS_F_PTP_PTP_PIN_CFG_PTP_PIN_ACTION(x)
#define VTSS_F_DEVCPU_PTP_PTP_PIN_CFG_PTP_PIN_SYNC(x)            VTSS_F_PTP_PTP_PIN_CFG_PTP_PIN_SYNC(x)
#define VTSS_F_DEVCPU_PTP_PTP_PIN_CFG_PTP_PIN_DOM(x)             VTSS_F_PTP_PTP_PIN_CFG_PTP_PIN_DOM(x)
#define VTSS_M_DEVCPU_PTP_PTP_PIN_CFG_PTP_PIN_ACTION             VTSS_M_PTP_PTP_PIN_CFG_PTP_PIN_ACTION
#define VTSS_M_DEVCPU_PTP_PTP_PIN_CFG_PTP_PIN_SYNC               VTSS_M_PTP_PTP_PIN_CFG_PTP_PIN_SYNC
#define VTSS_M_DEVCPU_PTP_PTP_PIN_CFG_PTP_PIN_DOM                VTSS_M_PTP_PTP_PIN_CFG_PTP_PIN_DOM
#define VTSS_DEVCPU_PTP_PTP_TOD_SEC_MSB(x)                       VTSS_PTP_PTP_TOD_SEC_MSB(x)
#define VTSS_DEVCPU_PTP_PTP_TOD_SEC_LSB(x)                       VTSS_PTP_PTP_TOD_SEC_LSB(x)
#define VTSS_DEVCPU_PTP_PTP_TOD_NSEC(x)                          VTSS_PTP_PTP_TOD_NSEC(x)
#define VTSS_F_DEVCPU_PTP_PTP_TOD_SEC_MSB_PTP_TOD_SEC_MSB(x)     VTSS_F_PTP_PTP_TOD_SEC_MSB_PTP_TOD_SEC_MSB(x)
#define VTSS_X_DEVCPU_PTP_PTP_TOD_NSEC_PTP_TOD_NSEC(x)           VTSS_X_PTP_PTP_TOD_NSEC_PTP_TOD_NSEC(x)
#define VTSS_DEVCPU_PTP_PTP_TOD_SEC_MSB(x)                       VTSS_PTP_PTP_TOD_SEC_MSB(x)
#define VTSS_DEVCPU_PTP_PTP_TOD_NSEC_FRAC(x)                     VTSS_PTP_PTP_TOD_NSEC_FRAC(x)
#define VTSS_F_DEVCPU_PTP_PTP_TOD_NSEC_FRAC_PTP_TOD_NSEC_FRAC(x) VTSS_F_PTP_PTP_TOD_NSEC_FRAC_PTP_TOD_NSEC_FRAC(x)
#define VTSS_X_DEVCPU_PTP_PTP_TOD_NSEC_FRAC_PTP_TOD_NSEC_FRAC(x) VTSS_X_PTP_PTP_TOD_NSEC_FRAC_PTP_TOD_NSEC_FRAC(x)
#define VTSS_DEVCPU_PTP_PTP_DOM_CFG                              VTSS_PTP_PTP_DOM_CFG
#define VTSS_F_DEVCPU_PTP_PTP_DOM_CFG_PTP_CLKCFG_DIS(x)          VTSS_F_PTP_PTP_DOM_CFG_PTP_CLKCFG_DIS(x)
#define VTSS_M_DEVCPU_PTP_PTP_DOM_CFG_PTP_CLKCFG_DIS             VTSS_M_PTP_PTP_DOM_CFG_PTP_CLKCFG_DIS
#define VTSS_DEVCPU_PTP_CLK_PER_CFG(x, y)                        VTSS_PTP_CLK_PER_CFG(x, y)
#define VTSS_F_DEVCPU_PTP_PTP_DOM_CFG_PTP_CLKCFG_DIS(x)          VTSS_F_PTP_PTP_DOM_CFG_PTP_CLKCFG_DIS(x)
#define VTSS_DEVCPU_PTP_PIN_WF_HIGH_PERIOD(x)                    VTSS_PTP_PIN_WF_HIGH_PERIOD(x)
#define VTSS_F_DEVCPU_PTP_PIN_WF_HIGH_PERIOD_PIN_WFH(x)          VTSS_F_PTP_PIN_WF_HIGH_PERIOD_PIN_WFH(x)
#define VTSS_DEVCPU_PTP_PIN_WF_LOW_PERIOD(x)                     VTSS_PTP_PIN_WF_LOW_PERIOD(x)
#define VTSS_F_DEVCPU_PTP_PIN_WF_LOW_PERIOD_PIN_WFL(x)           VTSS_F_PTP_PIN_WF_LOW_PERIOD_PIN_WFL(x)
#define VTSS_F_DEVCPU_PTP_PTP_TOD_NSEC_PTP_TOD_NSEC(x)           VTSS_F_PTP_PTP_TOD_NSEC_PTP_TOD_NSEC(x)
#define VTSS_X_DEVCPU_PTP_PTP_TOD_SEC_MSB_PTP_TOD_SEC_MSB(x)     VTSS_X_PTP_PTP_TOD_SEC_MSB_PTP_TOD_SEC_MSB(x)
#define VTSS_F_DEVCPU_PTP_PTP_DOM_CFG_PTP_ENA(x)                 VTSS_F_PTP_PTP_DOM_CFG_PTP_ENA(x)
#define VTSS_REW_PTP_TWOSTEP_STAMP                               VTSS_PTP_PTP_TWOSTEP_STAMP_NSEC
#define VTSS_X_REW_PTP_TWOSTEP_CTRL_STAMP_PORT(x)                VTSS_X_PTP_PTP_TWOSTEP_CTRL_STAMP_PORT(x)
#define VTSS_REW_PTP_TWOSTEP_STAMP_SUBNS                         VTSS_PTP_PTP_TWOSTEP_STAMP_SUBNS
#define VTSS_X_DEVCPU_PTP_PTP_PIN_CFG_PTP_PIN_OUTP_OFS(x)        VTSS_X_PTP_PTP_PIN_CFG_PTP_PIN_OUTP_OFS(x)
#define VTSS_DEVCPU_PTP_PTP_PIN_INTR                             VTSS_PTP_PTP_PIN_INTR
#define VTSS_DEVCPU_PTP_PTP_PIN_INTR_ENA                         VTSS_PTP_PTP_PIN_INTR_ENA
#define VTSS_DEVCPU_PTP_PTP_INTR_IDENT                           VTSS_PTP_PTP_INTR_IDENT
#define VTSS_DEVCPU_PTP_NTP_NSEC                                 VTSS_PTP_NTP_NSEC
#define VTSS_DEVCPU_PTP_PIN_IOBOUNCH_DELAY(x)                    VTSS_PTP_PIN_IOBOUNCH_DELAY(x)
#define VTSS_F_DEVCPU_PTP_PTP_PIN_CFG_PTP_PIN_SELECT(x)          VTSS_F_PTP_PTP_PIN_CFG_PTP_PIN_SELECT(x)
#define VTSS_M_DEVCPU_PTP_PTP_PIN_CFG_PTP_PIN_SELECT             VTSS_M_PTP_PTP_PIN_CFG_PTP_PIN_SELECT
#define VTSS_REW_PTP_TWOSTEP_CTRL                                VTSS_PTP_PTP_TWOSTEP_CTRL
#define VTSS_X_REW_PTP_TWOSTEP_CTRL_PTP_VLD(x)                   VTSS_X_PTP_PTP_TWOSTEP_CTRL_PTP_VLD(x)
#define VTSS_F_REW_PTP_TWOSTEP_CTRL_PTP_VLD(x)                   VTSS_F_PTP_PTP_TWOSTEP_CTRL_PTP_VLD(x)
#define VTSS_X_REW_PTP_TWOSTEP_CTRL_STAMP_TX(x)                  VTSS_X_PTP_PTP_TWOSTEP_CTRL_STAMP_TX(x)
#define VTSS_F_REW_PTP_TWOSTEP_CTRL_PTP_NXT(x)                   VTSS_F_PTP_PTP_TWOSTEP_CTRL_PTP_NXT(x)
#define VTSS_X_REW_PTP_TWOSTEP_CTRL_PTP_OVFL(x)                  VTSS_X_PTP_PTP_TWOSTEP_CTRL_PTP_OVFL(x)

#endif /* VTSS_ARCH_LAN969X */
#endif /* _VTSS_FA_TS_H_ */

/*****************************************************************************/
//
// End of file
//
//****************************************************************************/
