// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

/* Generation Tag is temp */

/* ================================================================= *
 *               Note: This code is autogenerated from the
 *                     Universal Tcl Environment (UTE) which provides
 *                     consistent setup functions for
 *       ^             - Verification
 *      / \            - Validation
 *     /   \           - Test Pattern Generation and
 *    /  |  \          - Software
 *   /   !   \         It should not be modified manually.
 *  /_________\
 * ================================================================= */

#ifndef _VTSS_ANT__API_SD10G28_H_UTE
#define _VTSS_ANT__API_SD10G28_H_UTE

#include <vtss/api/options.h>  // To get the ARCH define
#if defined(VTSS_ARCH_SPARX5) || defined(VTSS_ARCH_LAN969X)
#include "vtss_fa_inc.h"
vtss_rc vtss_ant_sd10g28_setup_lane(vtss_state_t *vtss_state, const vtss_sd10g28_setup_args_t config, vtss_port_no_t port_no);

#endif
#endif
