#!/usr/bin/env bash

# Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
# SPDX-License-Identifier: MIT

set -e

if (( $# < 2 )); then
   echo "Usage: $0 all|fam|ca1/ca2/oc/st/j2/mr/mc/m8/fa/la [<test_server>] <test_script> [brief|clean|short|skip]"
   exit
fi

platform=$1
cnt=$#
suffix=""
last=${!#}
brief=0
clean=0
skip=0

# Build list and platform list
build_list="mipsel arm arm64"
platform_list=$platform
case $platform in
    all)
        # All platforms
        platform_list="ca1 ca2 oc st j2 mr mc m8 fa la"
        ;;

    fam)
        # All families
        platform_list="ca oc st mc fa la"
        ;;

    ca|ca1|ca2|oc|st|j2)
        build_list="mipsel"
        ;;

    mr|mc|m8)
        build_list="arm"
        ;;

    fa|la)
        build_list="arm64"
        ;;

    *)
        echo "Illegal platform: $platform"
        exit
        ;;
esac

# Parse options
while true ; do
    case ${!cnt} in
        brief)
            # Brief output may be used for test suites or multiple platforms
            brief=1
            suffix+="--brief "
            ;;

        clean)
            # Clean build may be nice if external interfaces have changed
            clean=1
            ;;

        short)
            # Short output may be used for pasting into Jira
            suffix+="--short "
            ;;

        skip)
            # Skip test, just build
            skip=1
            ;;

        *)
            break
            ;;
    esac
    ((cnt--))
done

if [ $skip != 1 ]; then
    ts2=0
    case $cnt in
        1)
            echo "Test script not specified"
            exit
            ;;

        2)
            file=$2
            ;;

        *)
            ts2=$2
            file=$3
            ;;
    esac

    if [ ! -f $file ]; then
        echo "Test script not found: $file"
        exit
    fi
fi

# Build
for build in $build_list; do
    cd ../../../build-$build
    echo "=== Build: $build"
    if [ $clean == 1 ]; then
        dr make clean
    fi
    dr make -j 10
    cd -
done

if [ $skip == 1 ]; then
    exit
fi

# Reserve/upload/test/release
for platform in $platform_list; do
    dir=build-mipsel
    case $platform in
        ca|ca2)
            ts=dk-t35-3
            img=mipsel_vsc7429.mfi
            ;;

        ca1)
            ts=dk-t35-4
            img=mipsel_vsc7428.mfi
            ;;

        oc)
            ts=dk-t35-1
            img=mipsel_vsc7514_pcb123.mfi
            ;;

        st)
            ts=dk-t35-2
            img=mipsel_vsc7437.mfi
            ;;

        j2)
            ts=dk-t34-0
            img=mipsel_vsc7468_pcb110.mfi
            ;;

        mr)
            ts=dk-t34-6
            img=armv7_lan9662.itb
            dir=build-arm
            ;;

        mc)
            ts=dk-t36-1
            img=armv7_lan966x.itb
            dir=build-arm
            ;;

        me|m8)
            ts=dk-t35-0
            img=armv7_lan966x.itb
            dir=build-arm
            ;;

        fa)
            ts=dk-t34-4
            img=arm64_vsc7558TSN.itb # 625MHz
            dir=build-arm64
            ;;

        la)
            ts=dk-t36-2
            img=arm64_lan9698RED.itb
            dir=build-arm64
            ;;

        *)
            echo "Illegal platform: $platform"
            exit
            ;;
    esac

    rel=1
    if [ -f $HOME/.mscc-libeasy-topology.yaml ]; then
        et release
        rel=0
    fi
    if [ $ts2 != 0 ]; then
        ts=$ts2
    fi
    echo "=== Reserve: $ts"
    if [ $brief == 1 ]; then
        et reserve $ts > /dev/null
    else
        et reserve $ts
    fi

    echo "=== Upload: $img"
    cd ../../../$dir
    et upload mesa/demo/$img
    cd -

    echo "=== Run: $file"
    dr "./$file | libeasy/xml2console.rb $suffix"
    if [ $rel == 1 ]; then
        et release
    fi
done
