#!/usr/bin/env bash

# Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
# SPDX-License-Identifier: MIT

set -e

if (( $# < 2 )); then
   echo "Usage: $0 ca1/ca2/oc/st/j2/mr/mc/m8/fa/la [<test_server>] <test_script> [short]"
   exit
fi

list=$1
if [ $list == "all" ]; then
    # Run for all chips
    list="ca oc st mc fa la"
fi

cnt=$#
suffix=""
last=${!#}

# Brief output may be used for test suites or when 'all' chips are tested
if [ $last == "brief" ]; then
    suffix="--brief"
    ((cnt--))
fi

# Short output may be used for pasting into Jira
if [ $last == "short" ]; then
    suffix="--short"
    ((cnt--))
fi

if [ $cnt == 2 ]; then
  file=$2
else
  ts=$2
  file=$3
fi

if [ ! -f $file ]; then
   echo "Test script not found: $file"
   exit
fi

# Round 1: build
# Round 2: reserve/upload/test/release
for i in 1 2; do
    for chip in $list; do
        dir=build-mipsel
        case $chip in
            ca|ca2)
                ts=dk-t35-3
                img=mipsel_vsc7429.mfi
                ;;

            ca1)
                ts=dk-t35-4
                img=mipsel_vsc7428.mfi
                ;;

            oc)
                ts=dk-t35-1
                img=mipsel_vsc7514_pcb123.mfi
                ;;

            st)
                ts=dk-t35-2
                img=mipsel_vsc7437.mfi
                ;;

            j2)
                ts=dk-t34-0
                img=mipsel_vsc7468_pcb110.mfi
                ;;

            mr)
                ts=dk-t33-4
                img=armv7_lan9662.itb
                dir=build-arm
                ;;

            mc)
                ts=dk-t33-4
                img=armv7_lan966x.itb
                dir=build-arm
                ;;

            me|m8)
                ts=dk-t33-5
                img=armv7_lan966x.itb
                dir=build-arm
                ;;

            fa)
                ts=dk-t34-4
                img=arm64_vsc7558TSN.itb # 625MHz
                dir=build-arm64
                ;;

            la)
                ts=dk-t36-2
                img=arm64_lan9698RED.itb
                dir=build-arm64
                ;;

            *)
                echo "Illegal chip: $chip"
                exit
                ;;
        esac

        cd ../../../$dir
        if [ $i == "1" ]; then
            echo "--- Build: $dir"
            dr make -j 10
            cd -
        else
            rel=1
            if [ -f $HOME/.mscc-libeasy-topology.yaml ]; then
                et release
                rel=0
            fi
            echo "--- Reserve: $ts"
            if [ $last == "brief" ]; then
                et reserve $ts > /dev/null
            else
                et reserve $ts
            fi
            echo "--- Upload: $img"
            et upload mesa/demo/$img
            cd -

            echo "--- Run: $file"
            dr "./$file | libeasy/xml2console.rb $suffix"
            if [ $rel == 1 ]; then
                et release
            fi
        fi
    done
done
