// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

:sectnums:
== Access Control List

Advanced frame processing can be setup using the Access Control List (ACL) of the switch.
Each rule in the list is called an Access Control Entry (ACE). For each frame received on an ingress port,
the ACL is searched until an ACE matching the ingress port and frame properties is found.
The action of the first matching ACE determines the forwarding of the frame. If no matching ACE is found,
the default action of the ingress port is used.

=== ACL Rules
Each ACE (`mesa_ace_t`) consists of the following fields:

* ACE ID (`mesa_ace_id_t`) identifying the entry
* ACE action (`mesa_acl_action_t`) describing actions to be applied for frames matching the ACE, for example:
** Egress port filtering or redirect
** CPU copy options
** ACL policer mapping
** PTP timestamping
* ACE key fields used for matching received frames, such as:
** Ingress port list.
** Classified VLAN fields (`mesa_ace_vlan_t`).
** Frame type (`mesa_ace_type_t`) and extended ACE flag (`mesa_ace_t::type_ext`).
** Frame type specific fields, for example IPv4 SIP. 

Before adding an ACE (`mesa_ace_add()`), it should be initialized to default values (`mesa_ace_init()`). 
For each ACE, a hit counter is available (`mesa_ace_counter_t`).

=== ACL Port Configuration
For each ingress port, the default ACL action and ACL policy can be setup (`mesa_acl_port_conf_t`).
The ACL policy (`mesa_acl_policy_no_t`) can be used to indicate special processing for frames based on previous classifications:

* Default ACL policy for each ingress port is setup (`mesa_acl_port_conf_t`).
* VCL rules can override the default ACL policy (`mesa_vce_action_t`).
* QCL rules can again override the ACL policy (`mesa_qce_action_t`).
* ACL rules can match on the assigned ACL policy (`mesa_ace_t`).

For each ingress port, the generated key for ARP, IPv4 and IPv6 frames can also be setup (`mesa_acl_key_t`).
The default value `MESA_ACL_KEY_DEFAULT` indicates that a frame type matches an ACE of the same type.
If the key is set to `MESA_ACL_KEY_ETYPE` for a frame type, such frames will match ACEs of type `MESA_ACE_TYPE_ETYPE`.
This can be used to support matching DMAC/SMAC for a frame type.

Extended IPv4/IPv6 ACEs are added by setting the `mesa_ace_t::type_ext` flag.

If the key for IPv4 frames is set to `MESA_ACL_KEY_EXT` and the capability `MESA_CAP_ACL_EXT_MAC` is non-zero,
extended IPv4 ACEs with DMAC/SMAC address matching are supported.

If the key for IPv6 frames is set to `MESA_ACL_KEY_EXT`, extended IPv6 ACEs support the following:

* If the capability `MESA_CAP_ACL_EXT_MAC` is non-zero, DMAC/SMAC matching.
* SIP matching with all 128 bits.
* If the capability `MESA_CAP_ACL_EXT_DIP` is non-zero, DIP matching.
* If the capability `MESA_CAP_ACL_EXT_DIP` is zero, only the protocol and SIP fields are matched. All other IPv6 fields are ignored.

For each ingress port, a default ACL hit counter is available (`mesa_acl_port_counter_t`).

=== ACL Policers
The ACL action for an ACE or a port can map to an ACL policer. Each ACL policer can be setup to do bit rate or packet rate policing (`mesa_acl_policer_conf_t`).

=== Hierarchical ACLs
Hierarchical ACLs are available for devices with a non-zero `MESA_CAP_ACL_HACL` capability.
For such devices, six different ACLs are supported (`mesa_hace_add()`):

* I-PACL: Ingress Port ACL: This is equivalent to the ACL decribed in the previous sections.
** Filtering is based on ingress port list.
** Filtered frame types are ETYPE, LLC, SNAP, ARP, IPv4 and IPv6.
* I-VACL: Ingress VLAN ACL
** Filtering is based on ingress port list.
** Filtered frame types are ETYPE, LLC and SNAP (ARP/IPv4/IPv6 frames are seen as ETYPE).
* I-RACL: Ingress Router ACL
** Filtering is based on ingress router leg list.
** Filtered frame types are IPv4 and IPv6.
* E-RACL: Egress Router ACL
** Filtering is based on egress router leg list.
** Filtered frame types are IPv4 and IPv6.
* E-VACL: Egress VLAN ACL
** Filtering is based on egress port list.
** Filtered frame types are ETYPE, LLC and SNAP (ARP/IPv4/IPv6 frames are seen as ETYPE).
** Action is limited to pass/discard frame.
* E-PACL: Egress Port ACL
** Filtering is based on egress port list.
** Filtered frame types are ETYPE, LLC, SNAP, ARP, IPv4 and IPv6.
** Action is limited to pass/discard frame.

=== API Functions
`mesa_ace_init()` +
`mesa_ace_add()` +
`mesa_ace_del()` +
`mesa_ace_counter_get()` +
`mesa_ace_counter_clear()` +
`mesa_ace_status_get()` +
`mesa_acl_sip_conf_set()` +
`mesa_acl_port_conf_get()` +
`mesa_acl_port_conf_set()` +
`mesa_acl_port_counter_get()` +
`mesa_acl_port_counter_clear()` +
`mesa_acl_policer_conf_get()` +
`mesa_acl_policer_conf_set()` +
`mesa_hace_init()` +
`mesa_hace_add()` +
`mesa_hace_del()` +
`mesa_hace_counter_get()` +
`mesa_hace_counter_clear()`
