// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

#ifndef _VTSS_MALIBU_B__API_PLL5G_H_UTE
#define _VTSS_MALIBU_B__API_PLL5G_H_UTE


/* Generation Tag is  UTE_release_vts_ute_tcllib_20180312_trunk_bjo */

/* ================================================================= *
 *               Note: This code is autogenerated from the
 *                     Universal Tcl Environment (UTE) which provides
 *                     consistent setup functions for
 *       ^             - Verification
 *      / \            - Validation
 *     /   \           - Test Pattern Generation and
 *    /  |  \          - Software
 *   /   !   \         It should not be modified manually.
 *  /_________\        In case there is a need for modifications,
 *                     please contact
 *                       Patrick Urban <patrick.urban@microsemi.com> or
 *                       Alexander Koch <alexander.koch@microsemi.com> or
 *                       Mark Venneboerger <mark.venneboerger@microsemi.com>
 *                     Please use Bugzilla for reporting issues or requesting enhancements:
 *                     Bugzilla: Tools->Victoria
 *                     http://projissuetracker/bugzilla/enter_bug.cgi?product=Victoria
 * ================================================================= */

#include <vtss_phy_options.h>
#if defined(VTSS_ARCH_MALIBU_B)

vtss_rc vtss_malibu_b_line_pll5g_setup(vtss_state_t *vtss_state, const vtss_pll5g_setup_args_t config, const vtss_port_no_t port_no);
vtss_rc vtss_malibu_b_host_pll5g_setup(vtss_state_t *vtss_state, const vtss_pll5g_setup_args_t config, const vtss_port_no_t port_no);

#endif
#endif
