// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

= MEPA-2025.03

== MEPA-2025.03
|===
|Version:          |MEPA-2025.03
|Previous Version: |MEPA-2024.12
|Date:             |2025-03-27
|Description:      |Release Notes
|===

=== Release Status

==== Bugs Fixed:

  * MEPA-984: VSC 1G PHY unable to change MAC i/f ANEG Enable bit 7 in Reg16E3, ie. 16E3.7=serdes_aneg_ena
  * MEPA-999: M10G Reset breaks when booting up application
  * MEPA-891: VSC825x Link Broken when SPI Bus is used as Management

==== New features:

  * MEPA-627: EDS2 support in sw-mepa
  * MEPA-560: Cross Connect Sample Application in mepa-demo
  * MEPA-854: MEPA: Updated support for Malibu10G in Jr2
  * MEPA-880: Malibu10G MEBA Changes and Default Port config changes and remove unwanted GPIO Configurations
  * MEPA-889: Introduced a command to configure the Forced Speed of the PHY similar to that of MAC Ports
  * MEPA-930: Provide API to adjust LAN8814 QSGMII Tx Amplitude
  * MEPA-932: Auto downshift Application Support and ADOC

==== New MEPA API

  * MEPA-930: MEPA API to change to control the pre-emphasis level of transmitter output(`mepa_serdes_tx_conf_set`)

==== Known Bugs:

  * MEPA-966: LAN8814 QSGMII Serdes Loopback Broken
  * MEPA-124: [Viper] vtss_phy_sd6g_patch_private() corrections and enhancement - NOKIA QSGMII killer patterns
  * MEPA-506: BC/TC 1-step E2E: Reserved field, CF values and origin timestamp is not updating in some of the delay request and Sync packets
  * MEPA-794: 11-Port switch (VSC7514_VSC8504) issue sync-up on QSGMII
  * MEPA-644: SyncE Disable not working in Malibu10G
  * MEPA-793: When MACSec+1588 Enabled using VSC8584, after oos_mitigation there is very large PTP Offsets
  * MEPA-741: VSC8258 L1 Loopback Fails
