// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

= MEPA-2024.12

== MEPA-2024.12
|===
|Version:          |MEPA-2024.12
|Previous Version: |MEPA-2023.09
|Date:             |2024-12-20
|Description:      |Release Notes
|===

=== Support for Frame Preemption Enable/Disable

    * Introduced new MEPA API `mepa_framepreempt_set()` to Enable/Disable Frame Preemption in PHY,
Existing Argument `framepreempt_en` in API `mepa_reset()` will be removed in MEPA v2025.03 Release.

=== Release Status

==== Bugs Fixed:

  * MEPA-197: [Tesla] Atom12 missing LCPLL Reset Code in the API
  * MEPA-692: LAN8804 & LAN8814: phy_id are same
  * MEPA-715: CLONE - [Tesla] mepa_instantiation ADOC - mepa_reset() needs updating
  * MEPA-750: structure Linking issue in Chip specific ADOC
  * MEPA-873: arm64 build failed in pulling BSP and Toolchain

==== New features:

  * MEPA-594: LAN887X ASPICE final release merge
  * MEPA-625: Frame Preemption Sample Application Development for EDSx
  * MEPA-722: MEPA MACsec ADOC Modifications
  * MEPA-777: Introduce new MEPA API for Frame Preemption Configuration
  * MEPA-784: Change Channel Id Argument in mepa_conf_set API to ENUM to Avoid Confusion
  * MEPA-809: Rename All indy apis to lan8814
  * MEPA-827: Add support for Cable Diagnostics in Diagnostics sample Application
  * MEPA-848: ADOC for mepa_conf_set and Link Up Sequence
  * MEPA-849: Add PHY Support in the EDSx Build which allocated 25G Bandwidth to SFP Ports

==== New MEPA API

  * MEPA-777: MEPA API to Enable Frame Preemption in PHYs(`mepa_framepreempt_set()`)

==== Known Bugs:

  * MEPA-124: [Viper] vtss_phy_sd6g_patch_private() corrections and enhancement - NOKIA QSGMII killer patterns
  * MEPA-506: BC/TC 1-step E2E: Reserved field, CF values and origin timestamp is not updating in some of the delay request and Sync packets
  * MEPA-794: 11-Port switch (VSC7514_VSC8504) issue sync-up on QSGMII
  * MEPA-835: LAN8814 auto-downshift is changing port power-down bit
  * MEPA-644: SyncE Disable not working in Malibu10G
