---
apiVersion: v1
kind: Pod
metadata:
  name: ungsw-mesa-build-env
spec:
  containers:
  - name: pod-mesa-base
    image: artifacts-aws.devops.microchip.com:7996/ung/mesa/mesa-build-env@sha256:669f0da3adca587e977e0d267bfa0b6c87a486277d19e81107ca93101beef934
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: "2"
        memory: 4Gi
      limits:
        cpu: "2"
        memory: 4Gi

