---
apiVersion: v1
kind: Pod
metadata:
  name: ungsw-mesa-build-env
spec:
  containers:
  - name: pod-mesa-base
    image: artifacts-aws.devops.microchip.com:7996/ung/mesa/mesa-build-env@sha256:917a5dcb043e99771f68c1abdcde834b3f255fd88e3902c3a74e9ffd1855361a
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: '2'
        memory: 4Gi
      limits:
        cpu: '2'
        memory: 4Gi
