/*
 Copyright (c) 2004-2019 Microsemi Corporation "Microsemi".

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
*/

#ifndef _JAGUAR2_REG_H_
#define _JAGUAR2_REG_H_

#if defined(VTSS_ARCH_JAGUAR_2_B)
#include "vtss_jaguar2_regs.h"
#endif /* VTSS_ARCH_JAGUAR_2_B */
#if defined(VTSS_ARCH_JAGUAR_2_C)
#include "vtss_jaguar2c_regs.h"
#endif /* VTSS_ARCH_JAGUAR_2_C */
#if defined(VTSS_ARCH_SERVAL_T)
#include "vtss_servalt_regs.h"
#endif /* VTSS_ARCH_SERVAL_T */

/* Length of certain fields depend on platform */
#if defined(VTSS_ARCH_JAGUAR_2_B)
#define JR2_CLM_ISDX_LEN 12
#define JR2_CLM_MAP_LEN  9
#endif /* VTSS_ARCH_JAGUAR_2_B */

#if defined(VTSS_ARCH_JAGUAR_2_C)
#define JR2_CLM_ISDX_LEN 12
#define JR2_CLM_MAP_LEN  9
#endif /* VTSS_ARCH_JAGUAR_2_C */

#if defined(VTSS_ARCH_SERVAL_T)
#define JR2_CLM_ISDX_LEN 9
#define JR2_CLM_MAP_LEN  8
#endif /* VTSS_ARCH_SERVAL_T */

/* Commands for Mac Table Command register */
#define MAC_CMD_LEARN           0  /* Insert (Learn) 1 entry */
#define MAC_CMD_UNLEARN         1  /* Unlearn (Forget) 1 entry */
#define MAC_CMD_LOOKUP          2  /* Look up 1 entry */
#define MAC_CMD_READ            3  /* Read entry at Mac Table Index */
#define MAC_CMD_WRITE           4  /* Write entry at Mac Table Index */
#define MAC_CMD_SCAN            5  /* Scan (Age or find next) */
#define MAC_CMD_FIND_SMALLEST   6  /* Get next entry */
#define MAC_CMD_CLEAR_ALL       7  /* Delete all entries in table */

/* Commands for MAC_ENTRY_ADDR_TYPE */
#define  MAC_ENTRY_ADDR_TYPE_UPSID_PN           0
#define  MAC_ENTRY_ADDR_TYPE_UPSID_CPU_OR_INT   1
#define  MAC_ENTRY_ADDR_TYPE_GLAG               2
#define  MAC_ENTRY_ADDR_TYPE_MC_IDX             3

/* ================================================================= *
 *  VCAP CLM
 * ================================================================= */

/* CLM TPID values */
#define CLM_TPID_UNTAG    0
#define CLM_TPID_C_TAG    1
#define CLM_TPID_S_TAG    4
#define CLM_TPID_CUSTOM_1 5
#define CLM_TPID_CUSTOM_2 6
#define CLM_TPID_CUSTOM_3 7

/* CLM pipeline enable/mode */
#define CLM_PL_ENA_NONE 0
#define CLM_PL_ENA_XTR  1
#define CLM_PL_ENA_INJ  2
#define CLM_PL_ENA_LBK  3

/* CLM pipeline action selection */
#define CLM_PL_SEL_INJ_NORMAL 0
#define CLM_PL_SEL_INJ_MASQ   1
#define CLM_PL_SEL_LBK_QS     0
#define CLM_PL_SEL_LBK_ASM    1

/* IS2/CLM pipeline points */
#define JR2_PL_PT_NONE         0
#define JR2_PL_PT_ANA_VRAP     1
#define JR2_PL_PT_ANA_PORT_VOE 2
#define JR2_PL_PT_ANA_CL       3
#define JR2_PL_PT_ANA_CLM      4
#define JR2_PL_PT_ANA_IPT_PROT 5
#define JR2_PL_PT_ANA_OU_MIP   6
#define JR2_PL_PT_ANA_OU_SW    7
#define JR2_PL_PT_ANA_OU_PROT  8
#define JR2_PL_PT_ANA_OU_VOE   9
#define JR2_PL_PT_ANA_MID_PROT 10
#define JR2_PL_PT_ANA_IN_VOE   11
#define JR2_PL_PT_ANA_IN_PROT  12
#define JR2_PL_PT_ANA_IN_SW    13
#define JR2_PL_PT_ANA_IN_MIP   14
#define JR2_PL_PT_ANA_VLAN     15
#define JR2_PL_PT_ANA_DONE     16

/* CLM/rewriter reduced pipeline points (for MLBS_REDUCED only) */
#define JR2_PL_PT_RED_ANA_CLM      0
#define JR2_PL_PT_RED_ANA_OU_MIP   1
#define JR2_PL_PT_RED_ANA_IN_MIP   2
#define JR2_PL_PT_RED_ANA_PORT_VOE 3
#define JR2_PL_PT_RED_ANA_OU_VOE   4
#define JR2_PL_PT_RED_ANA_IN_VOE   5
#define JR2_PL_PT_RED_REW_IN_VOE   6
#define JR2_PL_PT_RED_REW_OU_VOE   7

/* CLM X1 key fields */
#define CLM_KO_X1_FIRST    0
#define CLM_KL_X1_FIRST    1
#define CLM_KO_X1_G_IDX    (CLM_KO_X1_FIRST + CLM_KL_X1_FIRST)
#define CLM_KL_X1_G_IDX    12
#define CLM_KO_X1_LBL0     (CLM_KO_X1_G_IDX + CLM_KL_X1_G_IDX)
#define CLM_KL_X1_LBL0     20
#define CLM_KO_X1_SBIT0    (CLM_KO_X1_LBL0 + CLM_KL_X1_LBL0)
#define CLM_KL_X1_SBIT0    1
#define CLM_KO_X1_TTL0_EXP (CLM_KO_X1_SBIT0 + CLM_KL_X1_SBIT0)
#define CLM_KL_X1_TTL0_EXP 1

/* CLM X2 key types */
#define CLM_X2_TYPE_TRI_VID     0
#define CLM_X2_TYPE_DBL_MLBS    1
#define CLM_X2_TYPE_TRI_VID_IDX 3

/* CLM X2 common key fields */
#define CLM_KO_X2_TYPE  0
#define CLM_KL_X2_TYPE  2
#define CLM_KO_X2_FIRST (CLM_KO_X2_TYPE + CLM_KL_X2_TYPE)
#define CLM_KL_X2_FIRST 1

/* CLM X2 TRI_VID key fields */
#define CLM_KO_TRI_VID_IGR_PORT (CLM_KO_X2_FIRST + CLM_KL_X2_FIRST)
#define CLM_KL_TRI_VID_IGR_PORT 6
#define CLM_KO_TRI_VID_TPID0    (CLM_KO_TRI_VID_IGR_PORT + CLM_KL_TRI_VID_IGR_PORT)
#define CLM_KL_TRI_VID_TPID0    3
#define CLM_KO_TRI_VID_PCP0     (CLM_KO_TRI_VID_TPID0 + CLM_KL_TRI_VID_TPID0)
#define CLM_KL_TRI_VID_PCP0     3
#define CLM_KO_TRI_VID_DEI0     (CLM_KO_TRI_VID_PCP0 + CLM_KL_TRI_VID_PCP0)
#define CLM_KL_TRI_VID_DEI0     1
#define CLM_KO_TRI_VID_VID0     (CLM_KO_TRI_VID_DEI0 + CLM_KL_TRI_VID_DEI0)
#define CLM_KL_TRI_VID_VID0     12
#define CLM_KO_TRI_VID_TPID1    (CLM_KO_TRI_VID_VID0 + CLM_KL_TRI_VID_VID0)
#define CLM_KL_TRI_VID_TPID1    3
#define CLM_KO_TRI_VID_PCP1     (CLM_KO_TRI_VID_TPID1 + CLM_KL_TRI_VID_TPID1)
#define CLM_KL_TRI_VID_PCP1     3
#define CLM_KO_TRI_VID_DEI1     (CLM_KO_TRI_VID_PCP1 + CLM_KL_TRI_VID_PCP1)
#define CLM_KL_TRI_VID_DEI1     1
#define CLM_KO_TRI_VID_VID1     (CLM_KO_TRI_VID_DEI1 + CLM_KL_TRI_VID_DEI1)
#define CLM_KL_TRI_VID_VID1     12
#define CLM_KO_TRI_VID_TPID2    (CLM_KO_TRI_VID_VID1 + CLM_KL_TRI_VID_VID1)
#define CLM_KL_TRI_VID_TPID2    3
#define CLM_KO_TRI_VID_PCP2     (CLM_KO_TRI_VID_TPID2 + CLM_KL_TRI_VID_TPID2)
#define CLM_KL_TRI_VID_PCP2     3
#define CLM_KO_TRI_VID_DEI2     (CLM_KO_TRI_VID_PCP2 + CLM_KL_TRI_VID_PCP2)
#define CLM_KL_TRI_VID_DEI2     1
#define CLM_KO_TRI_VID_VID2     (CLM_KO_TRI_VID_DEI2 + CLM_KL_TRI_VID_DEI2)
#define CLM_KL_TRI_VID_VID2     12
#define CLM_KO_TRI_VID_ETYPE    (CLM_KO_TRI_VID_VID2 + CLM_KL_TRI_VID_VID2)
#define CLM_KL_TRI_VID_ETYPE    3

/* CLM X2 TRI_VID_IDX key fields */
#define CLM_KO_TRI_VID_IDX_G_IDX_ISDX  (CLM_KO_X2_FIRST + CLM_KL_X2_FIRST)
#define CLM_KL_TRI_VID_IDX_G_IDX_ISDX  1
#define CLM_KO_TRI_VID_IDX_G_IDX       (CLM_KO_TRI_VID_IDX_G_IDX_ISDX + CLM_KL_TRI_VID_IDX_G_IDX_ISDX)
#define CLM_KL_TRI_VID_IDX_G_IDX       12
#define CLM_KO_TRI_VID_IDX_TPID0       (CLM_KO_TRI_VID_IDX_G_IDX + CLM_KL_TRI_VID_IDX_G_IDX)
#define CLM_KL_TRI_VID_IDX_TPID0       3
#define CLM_KO_TRI_VID_IDX_VID0        (CLM_KO_TRI_VID_IDX_TPID0 + CLM_KL_TRI_VID_IDX_TPID0)
#define CLM_KL_TRI_VID_IDX_VID0        12
#define CLM_KO_TRI_VID_IDX_TPID1       (CLM_KO_TRI_VID_IDX_VID0 + CLM_KL_TRI_VID_IDX_VID0)
#define CLM_KL_TRI_VID_IDX_TPID1       3
#define CLM_KO_TRI_VID_IDX_VID1        (CLM_KO_TRI_VID_IDX_TPID1 + CLM_KL_TRI_VID_IDX_TPID1)
#define CLM_KL_TRI_VID_IDX_VID1        12
#define CLM_KO_TRI_VID_IDX_TPID2       (CLM_KO_TRI_VID_IDX_VID1 + CLM_KL_TRI_VID_IDX_VID1)
#define CLM_KL_TRI_VID_IDX_TPID2       3
#define CLM_KO_TRI_VID_IDX_VID2        (CLM_KO_TRI_VID_IDX_TPID2 + CLM_KL_TRI_VID_IDX_TPID2)
#define CLM_KL_TRI_VID_IDX_VID2        12
#define CLM_KO_TRI_VID_IDX_Y1731       (CLM_KO_TRI_VID_IDX_VID2 + CLM_KL_TRI_VID_IDX_VID2)
#define CLM_KL_TRI_VID_IDX_Y1731       1
#define CLM_KO_TRI_VID_IDX_MEL_FLAG    (CLM_KO_TRI_VID_IDX_Y1731 + CLM_KL_TRI_VID_IDX_Y1731)
#define CLM_KL_TRI_VID_IDX_MEL_FLAG    7

/* CLM X2 DBL_MLBS key fields */
#define CLM_KO_DBL_MLBS_G_IDX    (CLM_KO_X2_FIRST + CLM_KL_X2_FIRST)
#define CLM_KL_DBL_MLBS_G_IDX    12
#define CLM_KO_DBL_MLBS_LBL0     (CLM_KO_DBL_MLBS_G_IDX + CLM_KL_DBL_MLBS_G_IDX)
#define CLM_KL_DBL_MLBS_LBL0     20
#define CLM_KO_DBL_MLBS_TC0      (CLM_KO_DBL_MLBS_LBL0 + CLM_KL_DBL_MLBS_LBL0)
#define CLM_KL_DBL_MLBS_TC0      3
#define CLM_KO_DBL_MLBS_SBIT0    (CLM_KO_DBL_MLBS_TC0 + CLM_KL_DBL_MLBS_TC0)
#define CLM_KL_DBL_MLBS_SBIT0    1
#define CLM_KO_DBL_MLBS_TTL0_EXP (CLM_KO_DBL_MLBS_SBIT0 + CLM_KL_DBL_MLBS_SBIT0)
#define CLM_KL_DBL_MLBS_TTL0_EXP 1
#define CLM_KO_DBL_MLBS_LBL1     (CLM_KO_DBL_MLBS_TTL0_EXP + CLM_KL_DBL_MLBS_TTL0_EXP)
#define CLM_KL_DBL_MLBS_LBL1     20
#define CLM_KO_DBL_MLBS_TC1      (CLM_KO_DBL_MLBS_LBL1 + CLM_KL_DBL_MLBS_LBL1)
#define CLM_KL_DBL_MLBS_TC1      3
#define CLM_KO_DBL_MLBS_SBIT1    (CLM_KO_DBL_MLBS_TC1 + CLM_KL_DBL_MLBS_TC1)
#define CLM_KL_DBL_MLBS_SBIT1    1
#define CLM_KO_DBL_MLBS_TTL1_EXP (CLM_KO_DBL_MLBS_SBIT1 + CLM_KL_DBL_MLBS_SBIT1)
#define CLM_KL_DBL_MLBS_TTL1_EXP 1
#define CLM_KO_DBL_MLBS_RSV_POS  (CLM_KO_DBL_MLBS_TTL1_EXP + CLM_KL_DBL_MLBS_TTL1_EXP)
#define CLM_KL_DBL_MLBS_RSV_POS  3

/* CLM X4 key types */
#define CLM_X4_TYPE_MLL        0
#define CLM_X4_TYPE_TRI_MLBS   1
#define CLM_X4_TYPE_5TUPLE_IP4 2
#define CLM_X4_TYPE_CUSTOM_4   3

/* CLM X4 common key fields */
#define CLM_KO_X4_TYPE  0
#define CLM_KL_X4_TYPE  2
#define CLM_KO_X4_FIRST (CLM_KO_X4_TYPE + CLM_KL_X4_TYPE)
#define CLM_KL_X4_FIRST 1

/* CLM X4 MLL key fields */
#define CLM_KO_MLL_IGR_PORT (CLM_KO_X4_TYPE + CLM_KL_X4_TYPE)
#define CLM_KL_MLL_IGR_PORT 6
#define CLM_KO_MLL_TPID0    (CLM_KO_MLL_IGR_PORT + CLM_KL_MLL_IGR_PORT)
#define CLM_KL_MLL_TPID0    3
#define CLM_KO_MLL_VID0     (CLM_KO_MLL_TPID0 + CLM_KL_MLL_TPID0)
#define CLM_KL_MLL_VID0     12
#define CLM_KO_MLL_TPID1    (CLM_KO_MLL_VID0 + CLM_KL_MLL_VID0)
#define CLM_KL_MLL_TPID1    3
#define CLM_KO_MLL_VID1     (CLM_KO_MLL_TPID1 + CLM_KL_MLL_TPID1)
#define CLM_KL_MLL_VID1     12
#define CLM_KO_MLL_DMAC     (CLM_KO_MLL_VID1 + CLM_KL_MLL_VID1)
#define CLM_KL_MLL_DMAC     48
#define CLM_KO_MLL_SMAC     (CLM_KO_MLL_DMAC + CLM_KL_MLL_DMAC)
#define CLM_KL_MLL_SMAC     48
#define CLM_KO_MLL_ETYPE    (CLM_KO_MLL_SMAC + CLM_KL_MLL_SMAC)
#define CLM_KL_MLL_ETYPE    2

/* CLM X4 TRI_MLBS key fields */
#define CLM_KO_TRI_MLBS_G_IDX    (CLM_KO_X4_FIRST + CLM_KL_X4_FIRST)
#define CLM_KL_TRI_MLBS_G_IDX    12
#define CLM_KO_TRI_MLBS_LBL0     (CLM_KO_TRI_MLBS_G_IDX + CLM_KL_TRI_MLBS_G_IDX)
#define CLM_KL_TRI_MLBS_LBL0     20
#define CLM_KO_TRI_MLBS_TC0      (CLM_KO_TRI_MLBS_LBL0 + CLM_KL_TRI_MLBS_LBL0)
#define CLM_KL_TRI_MLBS_TC0      3
#define CLM_KO_TRI_MLBS_SBIT0    (CLM_KO_TRI_MLBS_TC0 + CLM_KL_TRI_MLBS_TC0)
#define CLM_KL_TRI_MLBS_SBIT0    1
#define CLM_KO_TRI_MLBS_TTL0_EXP (CLM_KO_TRI_MLBS_SBIT0 + CLM_KL_TRI_MLBS_SBIT0)
#define CLM_KL_TRI_MLBS_TTL0_EXP 1
#define CLM_KO_TRI_MLBS_LBL1     (CLM_KO_TRI_MLBS_TTL0_EXP + CLM_KL_TRI_MLBS_TTL0_EXP)
#define CLM_KL_TRI_MLBS_LBL1     20
#define CLM_KO_TRI_MLBS_TC1      (CLM_KO_TRI_MLBS_LBL1 + CLM_KL_TRI_MLBS_LBL1)
#define CLM_KL_TRI_MLBS_TC1      3
#define CLM_KO_TRI_MLBS_SBIT1    (CLM_KO_TRI_MLBS_TC1 + CLM_KL_TRI_MLBS_TC1)
#define CLM_KL_TRI_MLBS_SBIT1    1
#define CLM_KO_TRI_MLBS_TTL1_EXP (CLM_KO_TRI_MLBS_SBIT1 + CLM_KL_TRI_MLBS_SBIT1)
#define CLM_KL_TRI_MLBS_TTL1_EXP 1
#define CLM_KO_TRI_MLBS_LBL2     (CLM_KO_TRI_MLBS_TTL1_EXP + CLM_KL_TRI_MLBS_TTL1_EXP)
#define CLM_KL_TRI_MLBS_LBL2     20
#define CLM_KO_TRI_MLBS_TC2      (CLM_KO_TRI_MLBS_LBL2 + CLM_KL_TRI_MLBS_LBL2)
#define CLM_KL_TRI_MLBS_TC2      3
#define CLM_KO_TRI_MLBS_SBIT2    (CLM_KO_TRI_MLBS_TC2 + CLM_KL_TRI_MLBS_TC2)
#define CLM_KL_TRI_MLBS_SBIT2    1
#define CLM_KO_TRI_MLBS_TTL2_EXP (CLM_KO_TRI_MLBS_SBIT2 + CLM_KL_TRI_MLBS_SBIT2)
#define CLM_KL_TRI_MLBS_TTL2_EXP 1
#define CLM_KO_TRI_MLBS_RSV_VAL  (CLM_KO_TRI_MLBS_TTL2_EXP + CLM_KL_TRI_MLBS_TTL2_EXP)
#define CLM_KL_TRI_MLBS_RSV_VAL  4
#define CLM_KO_TRI_MLBS_CW_ACH   (CLM_KO_TRI_MLBS_RSV_VAL + CLM_KL_TRI_MLBS_RSV_VAL)
#define CLM_KL_TRI_MLBS_CW_ACH   32
#define CLM_KO_TRI_MLBS_RSV_POS  (CLM_KO_TRI_MLBS_CW_ACH + CLM_KL_TRI_MLBS_CW_ACH)
#define CLM_KL_TRI_MLBS_RSV_POS  3

/* CLM X8 key types */
#define CLM_X8_TYPE_LL_FULL    0
#define CLM_X8_TYPE_NORMAL     1
#define CLM_X8_TYPE_5TUPLE_IP4 2
#define CLM_X8_TYPE_CUSTOM_2   3

/* CLM X8 common key fields */
#define CLM_KO_X8_TYPE       0
#define CLM_KL_X8_TYPE       2
#define CLM_KO_X8_FIRST      (CLM_KO_X8_TYPE + CLM_KL_X8_TYPE)
#define CLM_KL_X8_FIRST      1
#define CLM_KO_X8_G_IDX_ISDX (CLM_KO_X8_FIRST + CLM_KL_X8_FIRST)
#define CLM_KL_X8_G_IDX_ISDX 1
#define CLM_KO_X8_G_IDX      (CLM_KO_X8_G_IDX_ISDX + CLM_KL_X8_G_IDX_ISDX)
#define CLM_KL_X8_G_IDX      12
#define CLM_KO_X8_PORT_SEL   (CLM_KO_X8_G_IDX + CLM_KL_X8_G_IDX)
#define CLM_KL_X8_PORT_SEL   2
#define CLM_KO_X8_PORT_MASK  (CLM_KO_X8_PORT_SEL + CLM_KL_X8_PORT_SEL)
#define CLM_KL_X8_PORT_MASK  53
#define CLM_KO_X8_L2_MC      (CLM_KO_X8_PORT_MASK + CLM_KL_X8_PORT_MASK)
#define CLM_KL_X8_L2_MC      1
#define CLM_KO_X8_L2_BC      (CLM_KO_X8_L2_MC + CLM_KL_X8_L2_MC)
#define CLM_KL_X8_L2_BC      1
#define CLM_KO_X8_TPID0      (CLM_KO_X8_L2_BC + CLM_KL_X8_L2_BC)
#define CLM_KL_X8_TPID0      3
#define CLM_KO_X8_PCP0       (CLM_KO_X8_TPID0 + CLM_KL_X8_TPID0)
#define CLM_KL_X8_PCP0       3
#define CLM_KO_X8_DEI0       (CLM_KO_X8_PCP0 + CLM_KL_X8_PCP0)
#define CLM_KL_X8_DEI0       1
#define CLM_KO_X8_VID0       (CLM_KO_X8_DEI0 + CLM_KL_X8_DEI0)
#define CLM_KL_X8_VID0       12
#define CLM_KO_X8_TPID1      (CLM_KO_X8_VID0 + CLM_KL_X8_VID0)
#define CLM_KL_X8_TPID1      3
#define CLM_KO_X8_PCP1       (CLM_KO_X8_TPID1 + CLM_KL_X8_TPID1)
#define CLM_KL_X8_PCP1       3
#define CLM_KO_X8_DEI1       (CLM_KO_X8_PCP1 + CLM_KL_X8_PCP1)
#define CLM_KL_X8_DEI1       1
#define CLM_KO_X8_VID1       (CLM_KO_X8_DEI1 + CLM_KL_X8_DEI1)
#define CLM_KL_X8_VID1       12
#define CLM_KO_X8_TPID2      (CLM_KO_X8_VID1 + CLM_KL_X8_VID1)
#define CLM_KL_X8_TPID2      3
#define CLM_KO_X8_PCP2       (CLM_KO_X8_TPID2 + CLM_KL_X8_TPID2)
#define CLM_KL_X8_PCP2       3
#define CLM_KO_X8_DEI2       (CLM_KO_X8_PCP2 + CLM_KL_X8_PCP2)
#define CLM_KL_X8_DEI2       1
#define CLM_KO_X8_VID2       (CLM_KO_X8_DEI2 + CLM_KL_X8_DEI2)
#define CLM_KL_X8_VID2       12

/* CLM X8 LL_FULL key fields */
#define CLM_KO_LL_FULL_IGR_PORT  (CLM_KO_X8_FIRST + CLM_KL_X8_FIRST)
#define CLM_KL_LL_FULL_IGR_PORT  6
#define CLM_KO_LL_FULL_TPID0     (CLM_KO_LL_FULL_IGR_PORT + CLM_KL_LL_FULL_IGR_PORT)
#define CLM_KL_LL_FULL_TPID0     3
#define CLM_KO_LL_FULL_PCP0      (CLM_KO_LL_FULL_TPID0 + CLM_KL_LL_FULL_TPID0)
#define CLM_KL_LL_FULL_PCP0      3
#define CLM_KO_LL_FULL_DEI0      (CLM_KO_LL_FULL_PCP0 + CLM_KL_LL_FULL_PCP0)
#define CLM_KL_LL_FULL_DEI0      1
#define CLM_KO_LL_FULL_VID0      (CLM_KO_LL_FULL_DEI0 + CLM_KL_LL_FULL_DEI0)
#define CLM_KL_LL_FULL_VID0      12
#define CLM_KO_LL_FULL_TPID1     (CLM_KO_LL_FULL_VID0 + CLM_KL_LL_FULL_VID0)
#define CLM_KL_LL_FULL_TPID1     3
#define CLM_KO_LL_FULL_PCP1      (CLM_KO_LL_FULL_TPID1 + CLM_KL_LL_FULL_TPID1)
#define CLM_KL_LL_FULL_PCP1      3
#define CLM_KO_LL_FULL_DEI1      (CLM_KO_LL_FULL_PCP1 + CLM_KL_LL_FULL_PCP1)
#define CLM_KL_LL_FULL_DEI1      1
#define CLM_KO_LL_FULL_VID1      (CLM_KO_LL_FULL_DEI1 + CLM_KL_LL_FULL_DEI1)
#define CLM_KL_LL_FULL_VID1      12
#define CLM_KO_LL_FULL_TPID2     (CLM_KO_LL_FULL_VID1 + CLM_KL_LL_FULL_VID1)
#define CLM_KL_LL_FULL_TPID2     3
#define CLM_KO_LL_FULL_PCP2      (CLM_KO_LL_FULL_TPID2 + CLM_KL_LL_FULL_TPID2)
#define CLM_KL_LL_FULL_PCP2      3
#define CLM_KO_LL_FULL_DEI2      (CLM_KO_LL_FULL_PCP2 + CLM_KL_LL_FULL_PCP2)
#define CLM_KL_LL_FULL_DEI2      1
#define CLM_KO_LL_FULL_VID2      (CLM_KO_LL_FULL_DEI2 + CLM_KL_LL_FULL_DEI2)
#define CLM_KL_LL_FULL_VID2      12
#define CLM_KO_LL_FULL_DMAC      (CLM_KO_LL_FULL_VID2 + CLM_KL_LL_FULL_VID2)
#define CLM_KL_LL_FULL_DMAC      48
#define CLM_KO_LL_FULL_SMAC      (CLM_KO_LL_FULL_DMAC + CLM_KL_LL_FULL_DMAC)
#define CLM_KL_LL_FULL_SMAC      48
#define CLM_KO_LL_FULL_ETYPE_LEN (CLM_KO_LL_FULL_SMAC + CLM_KL_LL_FULL_SMAC)
#define CLM_KL_LL_FULL_ETYPE_LEN 1
#define CLM_KO_LL_FULL_ETYPE     (CLM_KO_LL_FULL_ETYPE_LEN + CLM_KL_LL_FULL_ETYPE_LEN)
#define CLM_KL_LL_FULL_ETYPE     16
#define CLM_KO_LL_FULL_IP_SNAP   (CLM_KO_LL_FULL_ETYPE + CLM_KL_LL_FULL_ETYPE)
#define CLM_KL_LL_FULL_IP_SNAP   1
#define CLM_KO_LL_FULL_IP4       (CLM_KO_LL_FULL_IP_SNAP + CLM_KL_LL_FULL_IP_SNAP)
#define CLM_KL_LL_FULL_IP4       1
#define CLM_KO_LL_FULL_FRAGMENT  (CLM_KO_LL_FULL_IP4 + CLM_KL_LL_FULL_IP4)
#define CLM_KL_LL_FULL_FRAGMENT  1
#define CLM_KO_LL_FULL_FRAG_OFFS (CLM_KO_LL_FULL_FRAGMENT + CLM_KL_LL_FULL_FRAGMENT)
#define CLM_KL_LL_FULL_FRAG_OFFS 1
#define CLM_KO_LL_FULL_OPTIONS   (CLM_KO_LL_FULL_FRAG_OFFS + CLM_KL_LL_FULL_FRAG_OFFS)
#define CLM_KL_LL_FULL_OPTIONS   1
#define CLM_KO_LL_FULL_DSCP      (CLM_KO_LL_FULL_OPTIONS + CLM_KL_LL_FULL_OPTIONS)
#define CLM_KL_LL_FULL_DSCP      6
#define CLM_KO_LL_FULL_DIP       (CLM_KO_LL_FULL_DSCP + CLM_KL_LL_FULL_DSCP)
#define CLM_KL_LL_FULL_DIP       32
#define CLM_KO_LL_FULL_SIP       (CLM_KO_LL_FULL_DIP + CLM_KL_LL_FULL_DIP)
#define CLM_KL_LL_FULL_SIP       32
#define CLM_KO_LL_FULL_TCP_UDP   (CLM_KO_LL_FULL_SIP + CLM_KL_LL_FULL_SIP)
#define CLM_KL_LL_FULL_TCP_UDP   1
#define CLM_KO_LL_FULL_TCP       (CLM_KO_LL_FULL_TCP_UDP + CLM_KL_LL_FULL_TCP_UDP)
#define CLM_KL_LL_FULL_TCP       1
#define CLM_KO_LL_FULL_SPORT     (CLM_KO_LL_FULL_TCP + CLM_KL_LL_FULL_TCP)
#define CLM_KL_LL_FULL_SPORT     16

/* CLM X8 NORMAL key fields */
#define CLM_KO_NORMAL_DST_ENTRY (CLM_KO_X8_VID2 + CLM_KL_X8_VID2)
#define CLM_KL_NORMAL_DST_ENTRY 1
#define CLM_KO_NORMAL_SMAC      (CLM_KO_NORMAL_DST_ENTRY + CLM_KL_NORMAL_DST_ENTRY)
#define CLM_KL_NORMAL_SMAC      48
#define CLM_KO_NORMAL_IP_MC     (CLM_KO_NORMAL_SMAC + CLM_KL_NORMAL_SMAC)
#define CLM_KL_NORMAL_IP_MC     1
#define CLM_KO_NORMAL_ETYPE_LEN (CLM_KO_NORMAL_IP_MC + CLM_KL_NORMAL_IP_MC)
#define CLM_KL_NORMAL_ETYPE_LEN 1
#define CLM_KO_NORMAL_ETYPE     (CLM_KO_NORMAL_ETYPE_LEN + CLM_KL_NORMAL_ETYPE_LEN)
#define CLM_KL_NORMAL_ETYPE     16
#define CLM_KO_NORMAL_IP_SNAP   (CLM_KO_NORMAL_ETYPE + CLM_KL_NORMAL_ETYPE)
#define CLM_KL_NORMAL_IP_SNAP   1
#define CLM_KO_NORMAL_IP4       (CLM_KO_NORMAL_IP_SNAP + CLM_KL_NORMAL_IP_SNAP)
#define CLM_KL_NORMAL_IP4       1
#define CLM_KO_NORMAL_FRAGMENT  (CLM_KO_NORMAL_IP4 + CLM_KL_NORMAL_IP4)
#define CLM_KL_NORMAL_FRAGMENT  1
#define CLM_KO_NORMAL_FRAG_OFFS (CLM_KO_NORMAL_FRAGMENT + CLM_KL_NORMAL_FRAGMENT)
#define CLM_KL_NORMAL_FRAG_OFFS 1
#define CLM_KO_NORMAL_OPTIONS   (CLM_KO_NORMAL_FRAG_OFFS + CLM_KL_NORMAL_FRAG_OFFS)
#define CLM_KL_NORMAL_OPTIONS   1
#define CLM_KO_NORMAL_DSCP      (CLM_KO_NORMAL_OPTIONS + CLM_KL_NORMAL_OPTIONS)
#define CLM_KL_NORMAL_DSCP      6
#define CLM_KO_NORMAL_SIP       (CLM_KO_NORMAL_DSCP + CLM_KL_NORMAL_DSCP)
#define CLM_KL_NORMAL_SIP       32
#define CLM_KO_NORMAL_TCP_UDP   (CLM_KO_NORMAL_SIP + CLM_KL_NORMAL_SIP)
#define CLM_KL_NORMAL_TCP_UDP   1
#define CLM_KO_NORMAL_TCP       (CLM_KO_NORMAL_TCP_UDP + CLM_KL_NORMAL_TCP_UDP)
#define CLM_KL_NORMAL_TCP       1
#define CLM_KO_NORMAL_SPORT     (CLM_KO_NORMAL_TCP + CLM_KL_NORMAL_TCP)
#define CLM_KL_NORMAL_SPORT     16
#define CLM_KO_NORMAL_RANGE     (CLM_KO_NORMAL_SPORT + CLM_KL_NORMAL_SPORT)
#define CLM_KL_NORMAL_RANGE     8

/* CLM X8 5TUPLE_IP4 key fields */
#define CLM_KO_5TUPLE_IP4_IP_MC     (CLM_KO_X8_VID2 + CLM_KL_X8_VID2)
#define CLM_KL_5TUPLE_IP4_IP_MC     1
#define CLM_KO_5TUPLE_IP4_IP4       (CLM_KO_5TUPLE_IP4_IP_MC + CLM_KL_5TUPLE_IP4_IP_MC)
#define CLM_KL_5TUPLE_IP4_IP4       1
#define CLM_KO_5TUPLE_IP4_FRAGMENT  (CLM_KO_5TUPLE_IP4_IP4 + CLM_KL_5TUPLE_IP4_IP4)
#define CLM_KL_5TUPLE_IP4_FRAGMENT  1
#define CLM_KO_5TUPLE_IP4_FRAG_OFFS (CLM_KO_5TUPLE_IP4_FRAGMENT + CLM_KL_5TUPLE_IP4_FRAGMENT)
#define CLM_KL_5TUPLE_IP4_FRAG_OFFS 1
#define CLM_KO_5TUPLE_IP4_OPTIONS   (CLM_KO_5TUPLE_IP4_FRAG_OFFS + CLM_KL_5TUPLE_IP4_FRAG_OFFS)
#define CLM_KL_5TUPLE_IP4_OPTIONS   1
#define CLM_KO_5TUPLE_IP4_DSCP      (CLM_KO_5TUPLE_IP4_OPTIONS + CLM_KL_5TUPLE_IP4_OPTIONS)
#define CLM_KL_5TUPLE_IP4_DSCP      6
#define CLM_KO_5TUPLE_IP4_DIP       (CLM_KO_5TUPLE_IP4_DSCP + CLM_KL_5TUPLE_IP4_DSCP)
#define CLM_KL_5TUPLE_IP4_DIP       32
#define CLM_KO_5TUPLE_IP4_SIP       (CLM_KO_5TUPLE_IP4_DIP + CLM_KL_5TUPLE_IP4_DIP)
#define CLM_KL_5TUPLE_IP4_SIP       32
#define CLM_KO_5TUPLE_IP4_PROTO     (CLM_KO_5TUPLE_IP4_SIP + CLM_KL_5TUPLE_IP4_SIP)
#define CLM_KL_5TUPLE_IP4_PROTO     8
#define CLM_KO_5TUPLE_IP4_TCP_UDP   (CLM_KO_5TUPLE_IP4_PROTO + CLM_KL_5TUPLE_IP4_PROTO)
#define CLM_KL_5TUPLE_IP4_TCP_UDP   1
#define CLM_KO_5TUPLE_IP4_TCP       (CLM_KO_5TUPLE_IP4_TCP_UDP + CLM_KL_5TUPLE_IP4_TCP_UDP)
#define CLM_KL_5TUPLE_IP4_TCP       1
#define CLM_KO_5TUPLE_IP4_RANGE     (CLM_KO_5TUPLE_IP4_TCP + CLM_KL_5TUPLE_IP4_TCP)
#define CLM_KL_5TUPLE_IP4_RANGE     8
#define CLM_KO_5TUPLE_IP4_PAYLOAD   (CLM_KO_5TUPLE_IP4_RANGE + CLM_KL_5TUPLE_IP4_RANGE)
#define CLM_KL_5TUPLE_IP4_PAYLOAD   32

/* CLM X16 key types */
#define CLM_X16_TYPE_7TUPLE   0
#define CLM_X16_TYPE_CUSTOM_1 1

/* CLM X16 common key fields */
#define CLM_KO_X16_TYPE       0
#define CLM_KL_X16_TYPE       1
#define CLM_KO_X16_FIRST      (CLM_KO_X16_TYPE + CLM_KL_X16_TYPE)
#define CLM_KL_X16_FIRST      1
#define CLM_KO_X16_G_IDX_ISDX (CLM_KO_X16_FIRST + CLM_KL_X16_FIRST)
#define CLM_KL_X16_G_IDX_ISDX 1
#define CLM_KO_X16_G_IDX      (CLM_KO_X16_G_IDX_ISDX + CLM_KL_X16_G_IDX_ISDX)
#define CLM_KL_X16_G_IDX      12
#define CLM_KO_X16_PORT_SEL   (CLM_KO_X16_G_IDX + CLM_KL_X16_G_IDX)
#define CLM_KL_X16_PORT_SEL   2
#define CLM_KO_X16_PORT_MASK  (CLM_KO_X16_PORT_SEL + CLM_KL_X16_PORT_SEL)
#define CLM_KL_X16_PORT_MASK  53
#define CLM_KO_X16_L2_MC      (CLM_KO_X16_PORT_MASK + CLM_KL_X16_PORT_MASK)
#define CLM_KL_X16_L2_MC      1
#define CLM_KO_X16_L2_BC      (CLM_KO_X16_L2_MC + CLM_KL_X16_L2_MC)
#define CLM_KL_X16_L2_BC      1
#define CLM_KO_X16_TPID0      (CLM_KO_X16_L2_BC + CLM_KL_X16_L2_BC)
#define CLM_KL_X16_TPID0      3
#define CLM_KO_X16_PCP0       (CLM_KO_X16_TPID0 + CLM_KL_X16_TPID0)
#define CLM_KL_X16_PCP0       3
#define CLM_KO_X16_DEI0       (CLM_KO_X16_PCP0 + CLM_KL_X16_PCP0)
#define CLM_KL_X16_DEI0       1
#define CLM_KO_X16_VID0       (CLM_KO_X16_DEI0 + CLM_KL_X16_DEI0)
#define CLM_KL_X16_VID0       12
#define CLM_KO_X16_TPID1      (CLM_KO_X16_VID0 + CLM_KL_X16_VID0)
#define CLM_KL_X16_TPID1      3
#define CLM_KO_X16_PCP1       (CLM_KO_X16_TPID1 + CLM_KL_X16_TPID1)
#define CLM_KL_X16_PCP1       3
#define CLM_KO_X16_DEI1       (CLM_KO_X16_PCP1 + CLM_KL_X16_PCP1)
#define CLM_KL_X16_DEI1       1
#define CLM_KO_X16_VID1       (CLM_KO_X16_DEI1 + CLM_KL_X16_DEI1)
#define CLM_KL_X16_VID1       12
#define CLM_KO_X16_TPID2      (CLM_KO_X16_VID1 + CLM_KL_X16_VID1)
#define CLM_KL_X16_TPID2      3
#define CLM_KO_X16_PCP2       (CLM_KO_X16_TPID2 + CLM_KL_X16_TPID2)
#define CLM_KL_X16_PCP2       3
#define CLM_KO_X16_DEI2       (CLM_KO_X16_PCP2 + CLM_KL_X16_PCP2)
#define CLM_KL_X16_DEI2       1
#define CLM_KO_X16_VID2       (CLM_KO_X16_DEI2 + CLM_KL_X16_DEI2)
#define CLM_KL_X16_VID2       12
#define CLM_KO_X16_DMAC       (CLM_KO_X16_VID2 + CLM_KL_X16_VID2)
#define CLM_KL_X16_DMAC       48
#define CLM_KO_X16_SMAC       (CLM_KO_X16_DMAC + CLM_KL_X16_DMAC)
#define CLM_KL_X16_SMAC       48
#define CLM_KO_X16_IP_MC      (CLM_KO_X16_SMAC + CLM_KL_X16_SMAC)
#define CLM_KL_X16_IP_MC      1
#define CLM_KO_X16_ETYPE_LEN  (CLM_KO_X16_IP_MC + CLM_KL_X16_IP_MC)
#define CLM_KL_X16_ETYPE_LEN  1
#define CLM_KO_X16_ETYPE      (CLM_KO_X16_ETYPE_LEN + CLM_KL_X16_ETYPE_LEN)
#define CLM_KL_X16_ETYPE      16
#define CLM_KO_X16_IP_SNAP    (CLM_KO_X16_ETYPE + CLM_KL_X16_ETYPE)
#define CLM_KL_X16_IP_SNAP    1
#define CLM_KO_X16_IP4        (CLM_KO_X16_IP_SNAP + CLM_KL_X16_IP_SNAP)
#define CLM_KL_X16_IP4        1
#define CLM_KO_X16_FRAGMENT   (CLM_KO_X16_IP4 + CLM_KL_X16_IP4)
#define CLM_KL_X16_FRAGMENT   1
#define CLM_KO_X16_FRAG_OFFS  (CLM_KO_X16_FRAGMENT + CLM_KL_X16_FRAGMENT)
#define CLM_KL_X16_FRAG_OFFS  1
#define CLM_KO_X16_OPTIONS    (CLM_KO_X16_FRAG_OFFS + CLM_KL_X16_FRAG_OFFS)
#define CLM_KL_X16_OPTIONS    1
#define CLM_KO_X16_DSCP       (CLM_KO_X16_OPTIONS + CLM_KL_X16_OPTIONS)
#define CLM_KL_X16_DSCP       6
#define CLM_KO_X16_DIP        (CLM_KO_X16_DSCP + CLM_KL_X16_DSCP)
#define CLM_KL_X16_DIP        128
#define CLM_KO_X16_SIP        (CLM_KO_X16_DIP + CLM_KL_X16_DIP)
#define CLM_KL_X16_SIP        128
#define CLM_KO_X16_TCP_UDP    (CLM_KO_X16_SIP + CLM_KL_X16_SIP)
#define CLM_KL_X16_TCP_UDP    1
#define CLM_KO_X16_TCP        (CLM_KO_X16_TCP_UDP + CLM_KL_X16_TCP_UDP)
#define CLM_KL_X16_TCP        1
#define CLM_KO_X16_SPORT      (CLM_KO_X16_TCP + CLM_KL_X16_TCP)
#define CLM_KL_X16_SPORT      16
#define CLM_KO_X16_RANGE      (CLM_KO_X16_SPORT + CLM_KL_X16_SPORT)
#define CLM_KL_X16_RANGE      8

/* CLM X1 MLBS_REDUCED action fields */
#define CLM_AO_X1_COSID_ENA     0
#define CLM_AL_X1_COSID_ENA     1
#define CLM_AO_X1_COSID_VAL     (CLM_AO_X1_COSID_ENA + CLM_AL_X1_COSID_ENA)
#define CLM_AL_X1_COSID_VAL     3
#define CLM_AO_X1_QOS_ENA       (CLM_AO_X1_COSID_VAL + CLM_AL_X1_COSID_VAL)
#define CLM_AL_X1_QOS_ENA       1
#define CLM_AO_X1_QOS_VAL       (CLM_AO_X1_QOS_ENA + CLM_AL_X1_QOS_ENA)
#define CLM_AL_X1_QOS_VAL       3
#define CLM_AO_X1_DP_ENA        (CLM_AO_X1_QOS_VAL + CLM_AL_X1_QOS_VAL)
#define CLM_AL_X1_DP_ENA        1
#define CLM_AO_X1_DP_VAL        (CLM_AO_X1_DP_ENA + CLM_AL_X1_DP_ENA)
#define CLM_AL_X1_DP_VAL        2
#define CLM_AO_X1_MAP_SEL       (CLM_AO_X1_DP_VAL + CLM_AL_X1_DP_VAL)
#define CLM_AL_X1_MAP_SEL       2
#if defined(VTSS_ARCH_JAGUAR_2_B)
#define CLM_AO_X1_FWD_DIS       (CLM_AO_X1_MAP_SEL + CLM_AL_X1_MAP_SEL)
#else
#define CLM_AO_X1_ISDX_ENA      (CLM_AO_X1_MAP_SEL + CLM_AL_X1_MAP_SEL)
#define CLM_AL_X1_ISDX_ENA      1
#define CLM_AO_X1_ISDX_VAL      (CLM_AO_X1_ISDX_ENA + CLM_AL_X1_ISDX_ENA)
#define CLM_AL_X1_ISDX_VAL      JR2_CLM_ISDX_LEN
#define CLM_AO_X1_FWD_DIS       (CLM_AO_X1_ISDX_VAL + CLM_AL_X1_ISDX_VAL)
#endif /* VTSS_ARCH_JAGUAR_2_B */
#define CLM_AL_X1_FWD_DIS       1
#define CLM_AO_X1_CPU_ENA       (CLM_AO_X1_FWD_DIS + CLM_AL_X1_FWD_DIS)
#define CLM_AL_X1_CPU_ENA       1
#define CLM_AO_X1_CPU_VAL       (CLM_AO_X1_CPU_ENA + CLM_AL_X1_CPU_ENA)
#define CLM_AL_X1_CPU_VAL       3
#if defined(VTSS_ARCH_JAGUAR_2_B)
#define CLM_AO_X1_OAM_SEL       (CLM_AO_X1_CPU_VAL + CLM_AL_X1_CPU_VAL)
#define CLM_AL_X1_OAM_SEL       3
#define CLM_AO_X1_TC_ENA        (CLM_AO_X1_OAM_SEL + CLM_AL_X1_OAM_SEL)
#else
#define CLM_AO_X1_TC_ENA        (CLM_AO_X1_CPU_VAL + CLM_AL_X1_CPU_VAL)
#endif /* VTSS_ARCH_JAGUAR_2_B */
#define CLM_AL_X1_TC_ENA        1
#define CLM_AO_X1_TTL_ENA       (CLM_AO_X1_TC_ENA + CLM_AL_X1_TC_ENA)
#define CLM_AL_X1_TTL_ENA       1
#define CLM_AO_X1_FWD_TYPE      (CLM_AO_X1_TTL_ENA + CLM_AL_X1_TTL_ENA)
#define CLM_AL_X1_FWD_TYPE      3
#define CLM_AO_X1_MPLS_OAM_TYPE (CLM_AO_X1_FWD_TYPE + CLM_AL_X1_FWD_TYPE)
#define CLM_AL_X1_MPLS_OAM_TYPE 3
#if defined(VTSS_ARCH_JAGUAR_2_B)
#define CLM_AO_X1_MPLS_TTL_CPU  (CLM_AO_X1_MPLS_OAM_TYPE + CLM_AL_X1_MPLS_OAM_TYPE)
#define CLM_AL_X1_MPLS_TTL_CPU  1
#define CLM_AO_X1_PL_ENA        (CLM_AO_X1_MPLS_TTL_CPU + CLM_AL_X1_MPLS_TTL_CPU)
#else
#define CLM_AO_X1_MPLS_MEP_ENA  (CLM_AO_X1_MPLS_OAM_TYPE + CLM_AL_X1_MPLS_OAM_TYPE)
#define CLM_AL_X1_MPLS_MEP_ENA  1
#define CLM_AO_X1_MPLS_MIP_ENA  (CLM_AO_X1_MPLS_MEP_ENA + CLM_AL_X1_MPLS_MEP_ENA)
#define CLM_AL_X1_MPLS_MIP_ENA  1
#define CLM_AO_X1_MPLS_OAM_FLVR (CLM_AO_X1_MPLS_MIP_ENA + CLM_AL_X1_MPLS_MIP_ENA)
#define CLM_AL_X1_MPLS_OAM_FLVR 1
#define CLM_AO_X1_MPLS_IP_CTRL  (CLM_AO_X1_MPLS_OAM_FLVR + CLM_AL_X1_MPLS_OAM_FLVR)
#define CLM_AL_X1_MPLS_IP_CTRL  1
#define CLM_AO_X1_PL_ENA        (CLM_AO_X1_MPLS_IP_CTRL + CLM_AL_X1_MPLS_IP_CTRL)
#endif /* VTSS_ARCH_JAGUAR_2_B */
#define CLM_AL_X1_PL_ENA        2
#define CLM_AO_X1_PL_PT         (CLM_AO_X1_PL_ENA + CLM_AL_X1_PL_ENA)
#if defined(VTSS_ARCH_JAGUAR_2_B)
#define CLM_AL_X1_PL_PT         2
#else
#define CLM_AL_X1_PL_PT         3
#endif /* VTSS_ARCH_JAGUAR_2_B */
#define CLM_AO_X1_NXT_KEY       (CLM_AO_X1_PL_PT + CLM_AL_X1_PL_PT)
#define CLM_AL_X1_NXT_KEY       4
#if defined(VTSS_ARCH_JAGUAR_2_B)
#define CLM_AO_X1_NXT_W16_OFFS  (CLM_AO_X1_NXT_KEY + CLM_AL_X1_NXT_KEY)
#define CLM_AL_X1_NXT_W16_OFFS  5
#define CLM_AO_X1_NXT_TYPE_OFFS (CLM_AO_X1_NXT_W16_OFFS + CLM_AL_X1_NXT_W16_OFFS)
#define CLM_AL_X1_NXT_TYPE_OFFS 2
#define CLM_AO_X1_NXT_PROT_OFFS (CLM_AO_X1_NXT_TYPE_OFFS + CLM_AL_X1_NXT_TYPE_OFFS)
#else
#define CLM_AO_X1_NXT_W32_OFFS  (CLM_AO_X1_NXT_KEY + CLM_AL_X1_NXT_KEY)
#define CLM_AL_X1_NXT_W32_OFFS  2
#define CLM_AO_X1_NXT_PROT_OFFS (CLM_AO_X1_NXT_W32_OFFS + CLM_AL_X1_NXT_W32_OFFS)
#endif /* VTSS_ARCH_JAGUAR_2_B */
#define CLM_AL_X1_NXT_PROT_OFFS 2
#define CLM_AO_X1_NXT_NORMALIZE (CLM_AO_X1_NXT_PROT_OFFS + CLM_AL_X1_NXT_PROT_OFFS)
#define CLM_AL_X1_NXT_NORMALIZE 1
#define CLM_AO_X1_NXT_IDX_CTRL  (CLM_AO_X1_NXT_NORMALIZE + CLM_AL_X1_NXT_NORMALIZE)
#define CLM_AL_X1_NXT_IDX_CTRL  3
#define CLM_AO_X1_NXT_IDX       (CLM_AO_X1_NXT_IDX_CTRL + CLM_AL_X1_NXT_IDX_CTRL)
#define CLM_AL_X1_NXT_IDX       12

/* CLM X2 action types */
#define CLM_X2_TYPE_MLBS  0
#define CLM_X2_TYPE_CLASS 1

/* CLM X2 common action fields */
#define CLM_AO_X2_TYPE      0
#define CLM_AL_X2_TYPE      1
#define CLM_AO_X2_COSID_ENA (CLM_AO_X2_TYPE + CLM_AL_X2_TYPE)
#define CLM_AL_X2_COSID_ENA 1
#define CLM_AO_X2_COSID_VAL (CLM_AO_X2_COSID_ENA + CLM_AL_X2_COSID_ENA)
#define CLM_AL_X2_COSID_VAL 3
#define CLM_AO_X2_QOS_ENA   (CLM_AO_X2_COSID_VAL + CLM_AL_X2_COSID_VAL)
#define CLM_AL_X2_QOS_ENA   1
#define CLM_AO_X2_QOS_VAL   (CLM_AO_X2_QOS_ENA + CLM_AL_X2_QOS_ENA)
#define CLM_AL_X2_QOS_VAL   3
#define CLM_AO_X2_DP_ENA    (CLM_AO_X2_QOS_VAL + CLM_AL_X2_QOS_VAL)
#define CLM_AL_X2_DP_ENA    1
#define CLM_AO_X2_DP_VAL    (CLM_AO_X2_DP_ENA + CLM_AL_X2_DP_ENA)
#define CLM_AL_X2_DP_VAL    2

/* CLM X2 MLBS action fields */
#define CLM_AO_MLBS_MAP_SEL       (CLM_AO_X2_DP_VAL + CLM_AL_X2_DP_VAL)
#define CLM_AL_MLBS_MAP_SEL       2
#define CLM_AO_MLBS_MAP_KEY       (CLM_AO_MLBS_MAP_SEL + CLM_AL_MLBS_MAP_SEL)
#define CLM_AL_MLBS_MAP_KEY       3
#define CLM_AO_MLBS_MAP_IDX       (CLM_AO_MLBS_MAP_KEY + CLM_AL_MLBS_MAP_KEY)
#define CLM_AL_MLBS_MAP_IDX       JR2_CLM_MAP_LEN
#if defined(VTSS_ARCH_JAGUAR_2_B)
#define CLM_AO_MLBS_VID_ENA       (CLM_AO_MLBS_MAP_IDX + CLM_AL_MLBS_MAP_IDX)
#define CLM_AL_MLBS_VID_ENA       1
#define CLM_AO_MLBS_VID_VAL       (CLM_AO_MLBS_VID_ENA + CLM_AL_MLBS_VID_ENA)
#else
#define CLM_AO_MLBS_VID_SEL       (CLM_AO_MLBS_MAP_IDX + CLM_AL_MLBS_MAP_IDX)
#define CLM_AL_MLBS_VID_SEL       2
#define CLM_AO_MLBS_VID_VAL       (CLM_AO_MLBS_VID_SEL + CLM_AL_MLBS_VID_SEL)
#endif /* VTSS_ARCH_JAGUAR_2_B */
#define CLM_AL_MLBS_VID_VAL       12
#define CLM_AO_MLBS_ISDX_ENA      (CLM_AO_MLBS_VID_VAL + CLM_AL_MLBS_VID_VAL)
#define CLM_AL_MLBS_ISDX_ENA      1
#define CLM_AO_MLBS_ISDX_VAL      (CLM_AO_MLBS_ISDX_ENA + CLM_AL_MLBS_ISDX_ENA)
#define CLM_AL_MLBS_ISDX_VAL      JR2_CLM_ISDX_LEN
#define CLM_AO_MLBS_FWD_DIS       (CLM_AO_MLBS_ISDX_VAL + CLM_AL_MLBS_ISDX_VAL)
#define CLM_AL_MLBS_FWD_DIS       1
#define CLM_AO_MLBS_CPU_ENA       (CLM_AO_MLBS_FWD_DIS + CLM_AL_MLBS_FWD_DIS)
#define CLM_AL_MLBS_CPU_ENA       1
#define CLM_AO_MLBS_CPU_VAL       (CLM_AO_MLBS_CPU_ENA + CLM_AL_MLBS_CPU_ENA)
#define CLM_AL_MLBS_CPU_VAL       3
#define CLM_AO_MLBS_OAM_SEL       (CLM_AO_MLBS_CPU_VAL + CLM_AL_MLBS_CPU_VAL)
#define CLM_AL_MLBS_OAM_SEL       3
#define CLM_AO_MLBS_TC_LABEL      (CLM_AO_MLBS_OAM_SEL + CLM_AL_MLBS_OAM_SEL)
#define CLM_AL_MLBS_TC_LABEL      2
#define CLM_AO_MLBS_TTL_LABEL     (CLM_AO_MLBS_TC_LABEL + CLM_AL_MLBS_TC_LABEL)
#define CLM_AL_MLBS_TTL_LABEL     2
#define CLM_AO_MLBS_NUM_LABELS    (CLM_AO_MLBS_TTL_LABEL + CLM_AL_MLBS_TTL_LABEL)
#define CLM_AL_MLBS_NUM_LABELS    2
#define CLM_AO_MLBS_FWD_TYPE      (CLM_AO_MLBS_NUM_LABELS + CLM_AL_MLBS_NUM_LABELS)
#define CLM_AL_MLBS_FWD_TYPE      3
#define CLM_AO_MLBS_MPLS_OAM_TYPE (CLM_AO_MLBS_FWD_TYPE + CLM_AL_MLBS_FWD_TYPE)
#define CLM_AL_MLBS_MPLS_OAM_TYPE 3
#if defined(VTSS_ARCH_JAGUAR_2_B)
#define CLM_AO_MLBS_MPLS_TTL_CPU  (CLM_AO_MLBS_MPLS_OAM_TYPE + CLM_AL_MLBS_MPLS_OAM_TYPE)
#define CLM_AL_MLBS_MPLS_TTL_CPU  1
#define CLM_AO_MLBS_PAG_MASK      (CLM_AO_MLBS_MPLS_TTL_CPU + CLM_AL_MLBS_MPLS_TTL_CPU)
#else
#define CLM_AO_MLBS_MPLS_MEP_ENA  (CLM_AO_MLBS_MPLS_OAM_TYPE + CLM_AL_MLBS_MPLS_OAM_TYPE)
#define CLM_AL_MLBS_MPLS_MEP_ENA  1
#define CLM_AO_MLBS_MPLS_MIP_ENA  (CLM_AO_MLBS_MPLS_MEP_ENA + CLM_AL_MLBS_MPLS_MEP_ENA)
#define CLM_AL_MLBS_MPLS_MIP_ENA  1
#define CLM_AO_MLBS_MPLS_OAM_FLVR (CLM_AO_MLBS_MPLS_MIP_ENA + CLM_AL_MLBS_MPLS_MIP_ENA)
#define CLM_AL_MLBS_MPLS_OAM_FLVR 1
#define CLM_AO_MLBS_MPLS_IP_CTRL  (CLM_AO_MLBS_MPLS_OAM_FLVR + CLM_AL_MLBS_MPLS_OAM_FLVR)
#define CLM_AL_MLBS_MPLS_IP_CTRL  1
#define CLM_AO_MLBS_PAG_MASK      (CLM_AO_MLBS_MPLS_IP_CTRL + CLM_AL_MLBS_MPLS_IP_CTRL)
#endif /* VTSS_ARCH_JAGUAR_2_B */
#define CLM_AL_MLBS_PAG_MASK      8
#define CLM_AO_MLBS_PAG           (CLM_AO_MLBS_PAG_MASK + CLM_AL_MLBS_PAG_MASK)
#define CLM_AL_MLBS_PAG           8
#define CLM_AO_MLBS_PL_ENA        (CLM_AO_MLBS_PAG + CLM_AL_MLBS_PAG)
#define CLM_AL_MLBS_PL_ENA        2
#define CLM_AO_MLBS_PL_PT         (CLM_AO_MLBS_PL_ENA + CLM_AL_MLBS_PL_ENA)
#define CLM_AL_MLBS_PL_PT         5
#define CLM_AO_MLBS_NXT_KEY       (CLM_AO_MLBS_PL_PT + CLM_AL_MLBS_PL_PT)
#define CLM_AL_MLBS_NXT_KEY       4
#define CLM_AO_MLBS_NXT_W16_OFFS  (CLM_AO_MLBS_NXT_KEY + CLM_AL_MLBS_NXT_KEY)
#define CLM_AL_MLBS_NXT_W16_OFFS  5
#define CLM_AO_MLBS_NXT_TYPE_OFFS (CLM_AO_MLBS_NXT_W16_OFFS + CLM_AL_MLBS_NXT_W16_OFFS)
#define CLM_AL_MLBS_NXT_TYPE_OFFS 2
#define CLM_AO_MLBS_NXT_PROT_OFFS (CLM_AO_MLBS_NXT_TYPE_OFFS + CLM_AL_MLBS_NXT_TYPE_OFFS)
#define CLM_AL_MLBS_NXT_PROT_OFFS 2
#define CLM_AO_MLBS_NXT_NORMALIZE (CLM_AO_MLBS_NXT_PROT_OFFS + CLM_AL_MLBS_NXT_PROT_OFFS)
#define CLM_AL_MLBS_NXT_NORMALIZE 1
#define CLM_AO_MLBS_NXT_IDX_CTRL  (CLM_AO_MLBS_NXT_NORMALIZE + CLM_AL_MLBS_NXT_NORMALIZE)
#if defined(VTSS_ARCH_JAGUAR_2_B)
#define CLM_AL_MLBS_NXT_IDX_CTRL  2
#else
#define CLM_AL_MLBS_NXT_IDX_CTRL  3
#endif /* VTSS_ARCH_JAGUAR_2_B */
#define CLM_AO_MLBS_NXT_IDX       (CLM_AO_MLBS_NXT_IDX_CTRL + CLM_AL_MLBS_NXT_IDX_CTRL)
#define CLM_AL_MLBS_NXT_IDX       12
#if !defined(VTSS_ARCH_JAGUAR_2_B)
#define CLM_AO_MLBS_RSVD          (CLM_AO_MLBS_NXT_IDX + CLM_AL_MLBS_NXT_IDX)
#define CLM_AL_MLBS_RSVD          1
#define CLM_AO_MLBS_PL_ACT_SEL    (CLM_AO_MLBS_RSVD + CLM_AL_MLBS_RSVD)
#define CLM_AL_MLBS_PL_ACT_SEL    1
#endif /* VTSS_ARCH_JAGUAR_2_B */

/* CLM X2 CLASSIFICATION action fields */
#define CLM_AO_CLAS_DEI_ENA       (CLM_AO_X2_DP_VAL + CLM_AL_X2_DP_VAL)
#define CLM_AL_CLAS_DEI_ENA       1
#define CLM_AO_CLAS_DEI_VAL       (CLM_AO_CLAS_DEI_ENA + CLM_AL_CLAS_DEI_ENA)
#define CLM_AL_CLAS_DEI_VAL       1
#define CLM_AO_CLAS_PCP_ENA       (CLM_AO_CLAS_DEI_VAL + CLM_AL_CLAS_DEI_VAL)
#define CLM_AL_CLAS_PCP_ENA       1
#define CLM_AO_CLAS_PCP_VAL       (CLM_AO_CLAS_PCP_ENA + CLM_AL_CLAS_PCP_ENA)
#define CLM_AL_CLAS_PCP_VAL       3
#define CLM_AO_CLAS_MAP_SEL       (CLM_AO_CLAS_PCP_VAL + CLM_AL_CLAS_PCP_VAL)
#define CLM_AL_CLAS_MAP_SEL       2
#define CLM_AO_CLAS_MAP_KEY       (CLM_AO_CLAS_MAP_SEL + CLM_AL_CLAS_MAP_SEL)
#define CLM_AL_CLAS_MAP_KEY       3
#define CLM_AO_CLAS_MAP_IDX       (CLM_AO_CLAS_MAP_KEY + CLM_AL_CLAS_MAP_KEY)
#define CLM_AL_CLAS_MAP_IDX       JR2_CLM_MAP_LEN
#if defined(VTSS_ARCH_JAGUAR_2_B)
#define CLM_AO_CLAS_VID_ENA       (CLM_AO_CLAS_MAP_IDX + CLM_AL_CLAS_MAP_IDX)
#define CLM_AL_CLAS_VID_ENA       1
#define CLM_AO_CLAS_VID_VAL       (CLM_AO_CLAS_VID_ENA + CLM_AL_CLAS_VID_ENA)
#else
#define CLM_AO_CLAS_VID_SEL       (CLM_AO_CLAS_MAP_IDX + CLM_AL_CLAS_MAP_IDX)
#define CLM_AL_CLAS_VID_SEL       2
#define CLM_AO_CLAS_VID_VAL       (CLM_AO_CLAS_VID_SEL + CLM_AL_CLAS_VID_SEL)
#endif /* VTSS_ARCH_JAGUAR_2_B */
#define CLM_AL_CLAS_VID_VAL       12
#define CLM_AO_CLAS_POP_ENA       (CLM_AO_CLAS_VID_VAL + CLM_AL_CLAS_VID_VAL)
#define CLM_AL_CLAS_POP_ENA       1
#define CLM_AO_CLAS_POP_VAL       (CLM_AO_CLAS_POP_ENA + CLM_AL_CLAS_POP_ENA)
#define CLM_AL_CLAS_POP_VAL       2
#define CLM_AO_CLAS_WAS_TAGGED    (CLM_AO_CLAS_POP_VAL + CLM_AL_CLAS_POP_VAL)
#define CLM_AL_CLAS_WAS_TAGGED    2
#define CLM_AO_CLAS_ISDX_ENA      (CLM_AO_CLAS_WAS_TAGGED + CLM_AL_CLAS_WAS_TAGGED)
#define CLM_AL_CLAS_ISDX_ENA      1
#define CLM_AO_CLAS_ISDX_VAL      (CLM_AO_CLAS_ISDX_ENA + CLM_AL_CLAS_ISDX_ENA)
#define CLM_AL_CLAS_ISDX_VAL      JR2_CLM_ISDX_LEN
#define CLM_AO_CLAS_FWD_DIS       (CLM_AO_CLAS_ISDX_VAL + CLM_AL_CLAS_ISDX_VAL)
#define CLM_AL_CLAS_FWD_DIS       1
#define CLM_AO_CLAS_CPU_ENA       (CLM_AO_CLAS_FWD_DIS + CLM_AL_CLAS_FWD_DIS)
#define CLM_AL_CLAS_CPU_ENA       1
#define CLM_AO_CLAS_CPU_VAL       (CLM_AO_CLAS_CPU_ENA + CLM_AL_CLAS_CPU_ENA)
#define CLM_AL_CLAS_CPU_VAL       3
#define CLM_AO_CLAS_MIP_SEL       (CLM_AO_CLAS_CPU_VAL + CLM_AL_CLAS_CPU_VAL)
#define CLM_AL_CLAS_MIP_SEL       2
#define CLM_AO_CLAS_OAM_SEL       (CLM_AO_CLAS_MIP_SEL + CLM_AL_CLAS_MIP_SEL)
#define CLM_AL_CLAS_OAM_SEL       3
#define CLM_AO_CLAS_PAG_MASK      (CLM_AO_CLAS_OAM_SEL + CLM_AL_CLAS_OAM_SEL)
#define CLM_AL_CLAS_PAG_MASK      8
#define CLM_AO_CLAS_PAG           (CLM_AO_CLAS_PAG_MASK + CLM_AL_CLAS_PAG_MASK)
#define CLM_AL_CLAS_PAG           8
#define CLM_AO_CLAS_PL_ENA        (CLM_AO_CLAS_PAG + CLM_AL_CLAS_PAG)
#define CLM_AL_CLAS_PL_ENA        2
#define CLM_AO_CLAS_PL_PT         (CLM_AO_CLAS_PL_ENA + CLM_AL_CLAS_PL_ENA)
#define CLM_AL_CLAS_PL_PT         5
#define CLM_AO_CLAS_NXT_KEY       (CLM_AO_CLAS_PL_PT + CLM_AL_CLAS_PL_PT)
#define CLM_AL_CLAS_NXT_KEY       4
#define CLM_AO_CLAS_NXT_W16_OFFS  (CLM_AO_CLAS_NXT_KEY + CLM_AL_CLAS_NXT_KEY)
#define CLM_AL_CLAS_NXT_W16_OFFS  5
#define CLM_AO_CLAS_NXT_TYPE_OFFS (CLM_AO_CLAS_NXT_W16_OFFS + CLM_AL_CLAS_NXT_W16_OFFS)
#define CLM_AL_CLAS_NXT_TYPE_OFFS 2
#define CLM_AO_CLAS_NXT_PROT_OFFS (CLM_AO_CLAS_NXT_TYPE_OFFS + CLM_AL_CLAS_NXT_TYPE_OFFS)
#define CLM_AL_CLAS_NXT_PROT_OFFS 2
#define CLM_AO_CLAS_NXT_NORMALIZE (CLM_AO_CLAS_NXT_PROT_OFFS + CLM_AL_CLAS_NXT_PROT_OFFS)
#define CLM_AL_CLAS_NXT_NORMALIZE 1
#define CLM_AO_CLAS_NXT_IDX_CTRL  (CLM_AO_CLAS_NXT_NORMALIZE + CLM_AL_CLAS_NXT_NORMALIZE)
#if defined(VTSS_ARCH_JAGUAR_2_B)
#define CLM_AL_CLAS_NXT_IDX_CTRL  2
#else
#define CLM_AL_CLAS_NXT_IDX_CTRL  3
#endif /* VTSS_ARCH_JAGUAR_2_B */
#define CLM_AO_CLAS_NXT_IDX       (CLM_AO_CLAS_NXT_IDX_CTRL + CLM_AL_CLAS_NXT_IDX_CTRL)
#define CLM_AL_CLAS_NXT_IDX       12
#if !defined(VTSS_ARCH_JAGUAR_2_B)
#define CLM_AO_CLAS_RSVD          (CLM_AO_CLAS_NXT_IDX + CLM_AL_CLAS_NXT_IDX)
#define CLM_AL_CLAS_RSVD          1
#define CLM_AO_CLAS_PL_ACT_SEL    (CLM_AO_CLAS_RSVD + CLM_AL_CLAS_RSVD)
#define CLM_AL_CLAS_PL_ACT_SEL    1
#endif /* VTSS_ARCH_JAGUAR_2_B */

/* CLM X4 FULL action fields */
#define CLM_AO_X4_DSCP_ENA      0
#define CLM_AL_X4_DSCP_ENA      1
#define CLM_AO_X4_DSCP_VAL      (CLM_AO_X4_DSCP_ENA + CLM_AL_X4_DSCP_ENA)
#define CLM_AL_X4_DSCP_VAL      6
#define CLM_AO_X4_COSID_ENA     (CLM_AO_X4_DSCP_VAL + CLM_AL_X4_DSCP_VAL)
#define CLM_AL_X4_COSID_ENA     1
#define CLM_AO_X4_COSID_VAL     (CLM_AO_X4_COSID_ENA + CLM_AL_X4_COSID_ENA)
#define CLM_AL_X4_COSID_VAL     3
#define CLM_AO_X4_QOS_ENA       (CLM_AO_X4_COSID_VAL + CLM_AL_X4_COSID_VAL)
#define CLM_AL_X4_QOS_ENA       1
#define CLM_AO_X4_QOS_VAL       (CLM_AO_X4_QOS_ENA + CLM_AL_X4_QOS_ENA)
#define CLM_AL_X4_QOS_VAL       3
#define CLM_AO_X4_DP_ENA        (CLM_AO_X4_QOS_VAL + CLM_AL_X4_QOS_VAL)
#define CLM_AL_X4_DP_ENA        1
#define CLM_AO_X4_DP_VAL        (CLM_AO_X4_DP_ENA + CLM_AL_X4_DP_ENA)
#define CLM_AL_X4_DP_VAL        2
#define CLM_AO_X4_DEI_ENA       (CLM_AO_X4_DP_VAL + CLM_AL_X4_DP_VAL)
#define CLM_AL_X4_DEI_ENA       1
#define CLM_AO_X4_DEI_VAL       (CLM_AO_X4_DEI_ENA + CLM_AL_X4_DEI_ENA)
#define CLM_AL_X4_DEI_VAL       1
#define CLM_AO_X4_PCP_ENA       (CLM_AO_X4_DEI_VAL + CLM_AL_X4_DEI_VAL)
#define CLM_AL_X4_PCP_ENA       1
#define CLM_AO_X4_PCP_VAL       (CLM_AO_X4_PCP_ENA + CLM_AL_X4_PCP_ENA)
#define CLM_AL_X4_PCP_VAL       3
#define CLM_AO_X4_MAP_SEL       (CLM_AO_X4_PCP_VAL + CLM_AL_X4_PCP_VAL)
#define CLM_AL_X4_MAP_SEL       2
#define CLM_AO_X4_MAP_KEY       (CLM_AO_X4_MAP_SEL + CLM_AL_X4_MAP_SEL)
#define CLM_AL_X4_MAP_KEY       3
#define CLM_AO_X4_MAP_IDX       (CLM_AO_X4_MAP_KEY + CLM_AL_X4_MAP_KEY)
#define CLM_AL_X4_MAP_IDX       JR2_CLM_MAP_LEN
#if defined(VTSS_ARCH_JAGUAR_2_B)
#define CLM_AO_X4_VID_ENA       (CLM_AO_X4_MAP_IDX + CLM_AL_X4_MAP_IDX)
#define CLM_AL_X4_VID_ENA       1
#define CLM_AO_X4_VID_VAL       (CLM_AO_X4_VID_ENA + CLM_AL_X4_VID_ENA)
#else
#define CLM_AO_X4_VID_SEL       (CLM_AO_X4_MAP_IDX + CLM_AL_X4_MAP_IDX)
#define CLM_AL_X4_VID_SEL       2
#define CLM_AO_X4_VID_VAL       (CLM_AO_X4_VID_SEL + CLM_AL_X4_VID_SEL)
#endif /* VTSS_ARCH_JAGUAR_2_B */
#define CLM_AL_X4_VID_VAL       12
#define CLM_AO_X4_POP_ENA       (CLM_AO_X4_VID_VAL + CLM_AL_X4_VID_VAL)
#define CLM_AL_X4_POP_ENA       1
#define CLM_AO_X4_POP_VAL       (CLM_AO_X4_POP_ENA + CLM_AL_X4_POP_ENA)
#define CLM_AL_X4_POP_VAL       2
#define CLM_AO_X4_WAS_TAGGED    (CLM_AO_X4_POP_VAL + CLM_AL_X4_POP_VAL)
#define CLM_AL_X4_WAS_TAGGED    2
#define CLM_AO_X4_ISDX_ENA      (CLM_AO_X4_WAS_TAGGED + CLM_AL_X4_WAS_TAGGED)
#define CLM_AL_X4_ISDX_ENA      1
#define CLM_AO_X4_ISDX_VAL      (CLM_AO_X4_ISDX_ENA + CLM_AL_X4_ISDX_ENA)
#define CLM_AL_X4_ISDX_VAL      JR2_CLM_ISDX_LEN
#define CLM_AO_X4_MASK_MODE     (CLM_AO_X4_ISDX_VAL + CLM_AL_X4_ISDX_VAL)
#define CLM_AL_X4_MASK_MODE     3
#define CLM_AO_X4_PORT_MASK     (CLM_AO_X4_MASK_MODE + CLM_AL_X4_MASK_MODE)
#define CLM_AL_X4_PORT_MASK     53
#define CLM_AO_X4_RT_SEL        (CLM_AO_X4_PORT_MASK + CLM_AL_X4_PORT_MASK)
#define CLM_AL_X4_RT_SEL        2
#define CLM_AO_X4_CPU_ENA       (CLM_AO_X4_RT_SEL + CLM_AL_X4_RT_SEL)
#define CLM_AL_X4_CPU_ENA       1
#define CLM_AO_X4_CPU_VAL       (CLM_AO_X4_CPU_ENA + CLM_AL_X4_CPU_ENA)
#define CLM_AL_X4_CPU_VAL       3
#define CLM_AO_X4_MIP_SEL       (CLM_AO_X4_CPU_VAL + CLM_AL_X4_CPU_VAL)
#define CLM_AL_X4_MIP_SEL       2
#define CLM_AO_X4_OAM_SEL       (CLM_AO_X4_MIP_SEL + CLM_AL_X4_MIP_SEL)
#define CLM_AL_X4_OAM_SEL       3
#define CLM_AO_X4_RSV_VAL       (CLM_AO_X4_OAM_SEL + CLM_AL_X4_OAM_SEL)
#define CLM_AL_X4_RSV_VAL       4
#define CLM_AO_X4_TC_LABEL      (CLM_AO_X4_RSV_VAL + CLM_AL_X4_RSV_VAL)
#define CLM_AL_X4_TC_LABEL      2
#define CLM_AO_X4_TTL_LABEL     (CLM_AO_X4_TC_LABEL + CLM_AL_X4_TC_LABEL)
#define CLM_AL_X4_TTL_LABEL     2
#define CLM_AO_X4_NUM_LABELS    (CLM_AO_X4_TTL_LABEL + CLM_AL_X4_TTL_LABEL)
#define CLM_AL_X4_NUM_LABELS    2
#define CLM_AO_X4_FWD_TYPE      (CLM_AO_X4_NUM_LABELS + CLM_AL_X4_NUM_LABELS)
#define CLM_AL_X4_FWD_TYPE      3
#define CLM_AO_X4_MPLS_OAM_TYPE (CLM_AO_X4_FWD_TYPE + CLM_AL_X4_FWD_TYPE)
#define CLM_AL_X4_MPLS_OAM_TYPE 3
#if defined(VTSS_ARCH_JAGUAR_2_B)
#define CLM_AO_X4_MPLS_TTL_CPU  (CLM_AO_X4_MPLS_OAM_TYPE + CLM_AL_X4_MPLS_OAM_TYPE)
#define CLM_AL_X4_MPLS_TTL_CPU  1
#define CLM_AO_X4_CUSTOM_ENA    (CLM_AO_X4_MPLS_TTL_CPU + CLM_AL_X4_MPLS_TTL_CPU)
#else
#define CLM_AO_X4_MPLS_MEP_ENA  (CLM_AO_X4_MPLS_OAM_TYPE + CLM_AL_X4_MPLS_OAM_TYPE)
#define CLM_AL_X4_MPLS_MEP_ENA  1
#define CLM_AO_X4_MPLS_MIP_ENA  (CLM_AO_X4_MPLS_MEP_ENA + CLM_AL_X4_MPLS_MEP_ENA)
#define CLM_AL_X4_MPLS_MIP_ENA  1
#define CLM_AO_X4_MPLS_OAM_FLVR (CLM_AO_X4_MPLS_MIP_ENA + CLM_AL_X4_MPLS_MIP_ENA)
#define CLM_AL_X4_MPLS_OAM_FLVR 1
#define CLM_AO_X4_MPLS_IP_CTRL  (CLM_AO_X4_MPLS_OAM_FLVR + CLM_AL_X4_MPLS_OAM_FLVR)
#define CLM_AL_X4_MPLS_IP_CTRL  1
#define CLM_AO_X4_CUSTOM_ENA    (CLM_AO_X4_MPLS_IP_CTRL + CLM_AL_X4_MPLS_IP_CTRL)
#endif /* VTSS_ARCH_JAGUAR_2_B */
#define CLM_AL_X4_CUSTOM_ENA    3
#define CLM_AO_X4_CUSTOM_OFFSET (CLM_AO_X4_CUSTOM_ENA + CLM_AL_X4_CUSTOM_ENA)
#define CLM_AL_X4_CUSTOM_OFFSET 2
#define CLM_AO_X4_PAG_MASK      (CLM_AO_X4_CUSTOM_OFFSET + CLM_AL_X4_CUSTOM_OFFSET)
#define CLM_AL_X4_PAG_MASK      8
#define CLM_AO_X4_PAG           (CLM_AO_X4_PAG_MASK + CLM_AL_X4_PAG_MASK)
#define CLM_AL_X4_PAG           8
#define CLM_AO_X4_RESERVED      (CLM_AO_X4_PAG + CLM_AL_X4_PAG)
#if defined(VTSS_ARCH_JAGUAR_2_B)
#define CLM_AL_X4_RESERVED      13
#define CLM_AO_X4_MATCH_ID      (CLM_AO_X4_RESERVED + CLM_AL_X4_RESERVED)
#else
#define CLM_AL_X4_RESERVED      7
#define CLM_AO_X4_LPORT         (CLM_AO_X4_RESERVED + CLM_AL_X4_RESERVED)
#define CLM_AL_X4_LPORT         6
#define CLM_AO_X4_MATCH_ID      (CLM_AO_X4_LPORT + CLM_AL_X4_LPORT)
#endif /* VTSS_ARCH_JAGUAR_2_B */
#define CLM_AL_X4_MATCH_ID      12
#define CLM_AO_X4_MATCH_MASK    (CLM_AO_X4_MATCH_ID + CLM_AL_X4_MATCH_ID)
#define CLM_AL_X4_MATCH_MASK    12
#define CLM_AO_X4_PL_ENA        (CLM_AO_X4_MATCH_MASK + CLM_AL_X4_MATCH_MASK)
#define CLM_AL_X4_PL_ENA        2
#define CLM_AO_X4_PL_PT         (CLM_AO_X4_PL_ENA + CLM_AL_X4_PL_ENA)
#define CLM_AL_X4_PL_PT         5
#define CLM_AO_X4_NXT_KEY       (CLM_AO_X4_PL_PT + CLM_AL_X4_PL_PT)
#define CLM_AL_X4_NXT_KEY       4
#define CLM_AO_X4_NXT_W16_OFFS  (CLM_AO_X4_NXT_KEY + CLM_AL_X4_NXT_KEY)
#define CLM_AL_X4_NXT_W16_OFFS  5
#define CLM_AO_X4_NXT_TYPE_OFFS (CLM_AO_X4_NXT_W16_OFFS + CLM_AL_X4_NXT_W16_OFFS)
#define CLM_AL_X4_NXT_TYPE_OFFS 2
#define CLM_AO_X4_NXT_PROT_OFFS (CLM_AO_X4_NXT_TYPE_OFFS + CLM_AL_X4_NXT_TYPE_OFFS)
#define CLM_AL_X4_NXT_PROT_OFFS 2
#define CLM_AO_X4_NXT_NORMALIZE (CLM_AO_X4_NXT_PROT_OFFS + CLM_AL_X4_NXT_PROT_OFFS)
#define CLM_AL_X4_NXT_NORMALIZE 1
#define CLM_AO_X4_NXT_IDX_CTRL  (CLM_AO_X4_NXT_NORMALIZE + CLM_AL_X4_NXT_NORMALIZE)
#if defined(VTSS_ARCH_JAGUAR_2_B)
#define CLM_AL_X4_NXT_IDX_CTRL  2
#else
#define CLM_AL_X4_NXT_IDX_CTRL  3
#endif /* VTSS_ARCH_JAGUAR_2_B */
#define CLM_AO_X4_NXT_IDX       (CLM_AO_X4_NXT_IDX_CTRL + CLM_AL_X4_NXT_IDX_CTRL)
#define CLM_AL_X4_NXT_IDX       12
#if !defined(VTSS_ARCH_JAGUAR_2_B)
#define CLM_AO_X4_RSVD          (CLM_AO_X4_NXT_IDX + CLM_AL_X4_NXT_IDX)
#define CLM_AL_X4_RSVD          1
#define CLM_AO_X4_PL_ACT_SEL    (CLM_AO_X4_RSVD + CLM_AL_X4_RSVD)
#define CLM_AL_X4_PL_ACT_SEL    1
#define CLM_AO_X4_LPORT_ENA     (CLM_AO_X4_PL_ACT_SEL + CLM_AL_X4_PL_ACT_SEL)
#define CLM_AL_X4_LPORT_ENA     1
#endif /* VTSS_ARCH_JAGUAR_2_B */

/* ================================================================= *
 *  VCAP IS2
 * ================================================================= */

/* IS2 X4 fields (IP4_VID) */
#define IS2_KO_X4_FIRST          0
#define IS2_KL_X4_FIRST          1
#define IS2_KO_X4_PAG            (IS2_KO_X4_FIRST + IS2_KL_X4_FIRST)
#define IS2_KL_X4_PAG            8
#define IS2_KO_X4_VID            (IS2_KO_X4_PAG + IS2_KL_X4_PAG)
#define IS2_KL_X4_VID            12
#define IS2_KO_X4_SMAC_SIP       (IS2_KO_X4_VID + IS2_KL_X4_VID)
#define IS2_KL_X4_SMAC_SIP       1
#define IS2_KO_X4_DMAC_DIP       (IS2_KO_X4_SMAC_SIP + IS2_KL_X4_SMAC_SIP)
#define IS2_KL_X4_DMAC_DIP       1
#define IS2_KO_X4_L3_RT          (IS2_KO_X4_DMAC_DIP + IS2_KL_X4_DMAC_DIP)
#define IS2_KL_X4_L3_RT          1
#define IS2_KO_X4_DIP            (IS2_KO_X4_L3_RT + IS2_KL_X4_L3_RT)
#define IS2_KL_X4_DIP            32
#define IS2_KO_X4_SIP            (IS2_KO_X4_DIP + IS2_KL_X4_DIP)
#define IS2_KL_X4_SIP            32

/* IS2 X8 key types */
#define IS2_X8_TYPE_ETYPE      0
#define IS2_X8_TYPE_ARP        3
#define IS2_X8_TYPE_IP_UDP_TCP 4
#define IS2_X8_TYPE_IP_OTHER   5
#define IS2_X8_TYPE_CUSTOM_2   8
#define IS2_X8_TYPE_IP6_VID    9

/* IS2 X8 common key fields (except IP6_VID) */
#define IS2_KO_X8_TYPE           0
#define IS2_KL_X8_TYPE           4
#define IS2_KO_X8_FIRST          (IS2_KO_X8_TYPE + IS2_KL_X8_TYPE)
#define IS2_KL_X8_FIRST          1
#define IS2_KO_X8_PAG            (IS2_KO_X8_FIRST + IS2_KL_X8_FIRST)
#define IS2_KL_X8_PAG            8
#define IS2_KO_X8_PORT_SEL       (IS2_KO_X8_PAG + IS2_KL_X8_PAG)
#define IS2_KL_X8_PORT_SEL       2
#define IS2_KO_X8_PORT_MASK      (IS2_KO_X8_PORT_SEL + IS2_KL_X8_PORT_SEL)
#define IS2_KL_X8_PORT_MASK      53
#define IS2_KO_X8_L2_MC          (IS2_KO_X8_PORT_MASK + IS2_KL_X8_PORT_MASK)
#define IS2_KL_X8_L2_MC          1
#define IS2_KO_X8_L2_BC          (IS2_KO_X8_L2_MC + IS2_KL_X8_L2_MC)
#define IS2_KL_X8_L2_BC          1
#define IS2_KO_X8_SERVICE_FRM    (IS2_KO_X8_L2_BC + IS2_KL_X8_L2_BC)
#define IS2_KL_X8_SERVICE_FRM    1
#define IS2_KO_X8_L2_FWD         (IS2_KO_X8_SERVICE_FRM + IS2_KL_X8_SERVICE_FRM)
#define IS2_KL_X8_L2_FWD         1
#define IS2_KO_X8_VLAN_TAGGED    (IS2_KO_X8_L2_FWD + IS2_KL_X8_L2_FWD)
#define IS2_KL_X8_VLAN_TAGGED    1
#define IS2_KO_X8_VID            (IS2_KO_X8_VLAN_TAGGED + IS2_KL_X8_VLAN_TAGGED)
#define IS2_KL_X8_VID            12
#define IS2_KO_X8_DEI            (IS2_KO_X8_VID + IS2_KL_X8_VID)
#define IS2_KL_X8_DEI            1
#define IS2_KO_X8_PCP            (IS2_KO_X8_DEI + IS2_KL_X8_DEI)
#define IS2_KL_X8_PCP            3
/* The following fields are not valid for ARP entries */
#define IS2_KO_X8_SMAC_SIP       (IS2_KO_X8_PCP + IS2_KL_X8_PCP)
#define IS2_KL_X8_SMAC_SIP       1
#define IS2_KO_X8_DMAC_DIP       (IS2_KO_X8_SMAC_SIP + IS2_KL_X8_SMAC_SIP)
#define IS2_KL_X8_DMAC_DIP       1
#define IS2_KO_X8_L3_RT          (IS2_KO_X8_DMAC_DIP + IS2_KL_X8_DMAC_DIP)
#define IS2_KL_X8_L3_RT          1

/* IS2 X8 ETYPE key fields */
#define IS2_KO_ETYPE_DMAC        (IS2_KO_X8_L3_RT + IS2_KL_X8_L3_RT)
#define IS2_KL_ETYPE_DMAC        48
#define IS2_KO_ETYPE_SMAC        (IS2_KO_ETYPE_DMAC + IS2_KL_ETYPE_DMAC)
#define IS2_KL_ETYPE_SMAC        48
#define IS2_KO_ETYPE_ETYPE_LEN   (IS2_KO_ETYPE_SMAC + IS2_KL_ETYPE_SMAC)
#define IS2_KL_ETYPE_ETYPE_LEN   1
#define IS2_KO_ETYPE_ETYPE       (IS2_KO_ETYPE_ETYPE_LEN + IS2_KL_ETYPE_ETYPE_LEN)
#define IS2_KL_ETYPE_ETYPE       16
#define IS2_KO_ETYPE_PAYLOAD     (IS2_KO_ETYPE_ETYPE + IS2_KL_ETYPE_ETYPE)
#define IS2_KL_ETYPE_PAYLOAD     64
#define IS2_KO_ETYPE_CCM_CNT_EQ0 (IS2_KO_ETYPE_PAYLOAD + IS2_KL_ETYPE_PAYLOAD)
#define IS2_KL_ETYPE_CCM_CNT_EQ0 1
#define IS2_KO_ETYPE_OAM         (IS2_KO_ETYPE_CCM_CNT_EQ0 + IS2_KL_ETYPE_CCM_CNT_EQ0)
#define IS2_KL_ETYPE_OAM         1

/* IS2 X8 ARP key fields */
#define IS2_KO_ARP_SMAC          (IS2_KO_X8_PCP + IS2_KL_X8_PCP)
#define IS2_KL_ARP_SMAC          48
#define IS2_KO_ARP_ADDR_OK       (IS2_KO_ARP_SMAC + IS2_KL_ARP_SMAC)
#define IS2_KL_ARP_ADDR_OK       1
#define IS2_KO_ARP_PROTO_OK      (IS2_KO_ARP_ADDR_OK + IS2_KL_ARP_ADDR_OK)
#define IS2_KL_ARP_PROTO_OK      1
#define IS2_KO_ARP_LEN_OK        (IS2_KO_ARP_PROTO_OK + IS2_KL_ARP_PROTO_OK)
#define IS2_KL_ARP_LEN_OK        1
#define IS2_KO_ARP_TARGET_MATCH  (IS2_KO_ARP_LEN_OK + IS2_KL_ARP_LEN_OK)
#define IS2_KL_ARP_TARGET_MATCH  1
#define IS2_KO_ARP_SENDER_MATCH  (IS2_KO_ARP_TARGET_MATCH + IS2_KL_ARP_TARGET_MATCH)
#define IS2_KL_ARP_SENDER_MATCH  1
#define IS2_KO_ARP_OPCODE_UNKN   (IS2_KO_ARP_SENDER_MATCH + IS2_KL_ARP_SENDER_MATCH)
#define IS2_KL_ARP_OPCODE_UNKN   1
#define IS2_KO_ARP_OPCODE        (IS2_KO_ARP_OPCODE_UNKN + IS2_KL_ARP_OPCODE_UNKN)
#define IS2_KL_ARP_OPCODE        2
#define IS2_KO_ARP_DIP           (IS2_KO_ARP_OPCODE + IS2_KL_ARP_OPCODE)
#define IS2_KL_ARP_DIP           32
#define IS2_KO_ARP_SIP           (IS2_KO_ARP_DIP + IS2_KL_ARP_DIP)
#define IS2_KL_ARP_SIP           32
#define IS2_KO_ARP_DIP_EQ_SIP    (IS2_KO_ARP_SIP + IS2_KL_ARP_SIP)
#define IS2_KL_ARP_DIP_EQ_SIP    1

/* IS2 X8 IP4_TCP_UDP/IP4_OTHER key fields */
#define IS2_KO_IP4_IP4           (IS2_KO_X8_L3_RT + IS2_KL_X8_L3_RT)
#define IS2_KL_IP4_IP4           1
#define IS2_KO_IP4_FRAGMENT      (IS2_KO_IP4_IP4 + IS2_KL_IP4_IP4)
#define IS2_KL_IP4_FRAGMENT      1
#define IS2_KO_IP4_FRAG_OFFS     (IS2_KO_IP4_FRAGMENT + IS2_KL_IP4_FRAGMENT)
#define IS2_KL_IP4_FRAG_OFFS     1
#define IS2_KO_IP4_OPTIONS       (IS2_KO_IP4_FRAG_OFFS + IS2_KL_IP4_FRAG_OFFS)
#define IS2_KL_IP4_OPTIONS       1
#define IS2_KO_IP4_TTL           (IS2_KO_IP4_OPTIONS + IS2_KL_IP4_OPTIONS)
#define IS2_KL_IP4_TTL           1
#define IS2_KO_IP4_TOS           (IS2_KO_IP4_TTL + IS2_KL_IP4_TTL)
#define IS2_KL_IP4_TOS           8
#define IS2_KO_IP4_DIP           (IS2_KO_IP4_TOS + IS2_KL_IP4_TOS)
#define IS2_KL_IP4_DIP           32
#define IS2_KO_IP4_SIP           (IS2_KO_IP4_DIP + IS2_KL_IP4_DIP)
#define IS2_KL_IP4_SIP           32
#define IS2_KO_IP4_DIP_EQ_SIP    (IS2_KO_IP4_SIP + IS2_KL_IP4_SIP)
#define IS2_KL_IP4_DIP_EQ_SIP    1

/* IS2 X8 IP4_TCP_UDP key fields */
#define IS2_KO_IP4_TU_TCP        (IS2_KO_IP4_DIP_EQ_SIP + IS2_KL_IP4_DIP_EQ_SIP)
#define IS2_KL_IP4_TU_TCP        1
#define IS2_KO_IP4_TU_DPORT      (IS2_KO_IP4_TU_TCP + IS2_KL_IP4_TU_TCP)
#define IS2_KL_IP4_TU_DPORT      16
#define IS2_KO_IP4_TU_SPORT      (IS2_KO_IP4_TU_DPORT + IS2_KL_IP4_TU_DPORT)
#define IS2_KL_IP4_TU_SPORT      16
#define IS2_KO_IP4_TU_RANGE      (IS2_KO_IP4_TU_SPORT + IS2_KL_IP4_TU_SPORT)
#define IS2_KL_IP4_TU_RANGE      8
#define IS2_KO_IP4_TU_SP_EQ_DP   (IS2_KO_IP4_TU_RANGE + IS2_KL_IP4_TU_RANGE)
#define IS2_KL_IP4_TU_SP_EQ_DP   1
#define IS2_KO_IP4_TU_SEQ_EQ0    (IS2_KO_IP4_TU_SP_EQ_DP + IS2_KL_IP4_TU_SP_EQ_DP)
#define IS2_KL_IP4_TU_SEQ_EQ0    1
#define IS2_KO_IP4_TU_FIN        (IS2_KO_IP4_TU_SEQ_EQ0 + IS2_KL_IP4_TU_SEQ_EQ0)
#define IS2_KL_IP4_TU_FIN        1
#define IS2_KO_IP4_TU_SYN        (IS2_KO_IP4_TU_FIN + IS2_KL_IP4_TU_FIN)
#define IS2_KL_IP4_TU_SYN        1
#define IS2_KO_IP4_TU_RST        (IS2_KO_IP4_TU_SYN + IS2_KL_IP4_TU_SYN)
#define IS2_KL_IP4_TU_RST        1
#define IS2_KO_IP4_TU_PSH        (IS2_KO_IP4_TU_RST + IS2_KL_IP4_TU_RST)
#define IS2_KL_IP4_TU_PSH        1
#define IS2_KO_IP4_TU_ACK        (IS2_KO_IP4_TU_PSH + IS2_KL_IP4_TU_PSH)
#define IS2_KL_IP4_TU_ACK        1
#define IS2_KO_IP4_TU_URG        (IS2_KO_IP4_TU_ACK + IS2_KL_IP4_TU_ACK)
#define IS2_KL_IP4_TU_URG        1
#define IS2_KO_IP4_TU_PAYLOAD    (IS2_KO_IP4_TU_URG + IS2_KL_IP4_TU_URG)
#define IS2_KL_IP4_TU_PAYLOAD    64

/* IS2 X8 IP4_OTHER key fields */
#define IS2_KO_IP4_OTHER_PROTO   (IS2_KO_IP4_DIP_EQ_SIP + IS2_KL_IP4_DIP_EQ_SIP)
#define IS2_KL_IP4_OTHER_PROTO   8
#define IS2_KO_IP4_OTHER_PAYLOAD (IS2_KO_IP4_OTHER_PROTO + IS2_KL_IP4_OTHER_PROTO)
#define IS2_KL_IP4_OTHER_PAYLOAD 96

/* IS2 X8 CUSTOM_2 key fields */
#define IS2_KO_CUSTOM_2_PAYLOAD  (IS2_KO_X8_L3_RT + IS2_KL_X8_L3_RT)
#define IS2_KL_CUSTOM_2_PAYLOAD  192

/* IS2 X8 IP6_VID key fields */
#define IS2_KO_IP6_VID_VID       (IS2_KO_X8_PAG + IS2_KL_X8_PAG)
#define IS2_KL_IP6_VID_VID       12
#define IS2_KO_IP6_VID_SMAC_SIP  (IS2_KO_IP6_VID_VID + IS2_KL_IP6_VID_VID)
#define IS2_KL_IP6_VID_SMAC_SIP  1
#define IS2_KO_IP6_VID_DMAC_DIP  (IS2_KO_IP6_VID_SMAC_SIP + IS2_KL_IP6_VID_SMAC_SIP)
#define IS2_KL_IP6_VID_DMAC_DIP  1
#define IS2_KO_IP6_VID_L3_RT     (IS2_KO_IP6_VID_DMAC_DIP + IS2_KL_IP6_VID_DMAC_DIP)
#define IS2_KL_IP6_VID_L3_RT     1
#define IS2_KO_IP6_VID_DIP       (IS2_KO_IP6_VID_L3_RT + IS2_KL_IP6_VID_L3_RT)
#define IS2_KL_IP6_VID_DIP       128
#define IS2_KO_IP6_VID_SIP       (IS2_KO_IP6_VID_DIP + IS2_KL_IP6_VID_DIP)
#define IS2_KL_IP6_VID_SIP       128

/* IS2 action fields */
#define IS2_AO_IS_INNER_ACL    0
#define IS2_AL_IS_INNER_ACL    1
#define IS2_AO_PL_ENA          (IS2_AO_IS_INNER_ACL + IS2_AL_IS_INNER_ACL)
#define IS2_AL_PL_ENA          1
#define IS2_AO_PL_VAL          (IS2_AO_PL_ENA + IS2_AL_PL_ENA)
#define IS2_AL_PL_VAL          5
#define IS2_AO_HIT_ME_ONCE     (IS2_AO_PL_VAL + IS2_AL_PL_VAL)
#define IS2_AL_HIT_ME_ONCE     1
#define IS2_AO_INTR_ENA        (IS2_AO_HIT_ME_ONCE + IS2_AL_HIT_ME_ONCE)
#define IS2_AL_INTR_ENA        1
#define IS2_AO_CPU_ENA         (IS2_AO_INTR_ENA + IS2_AL_INTR_ENA)
#define IS2_AL_CPU_ENA         1
#define IS2_AO_CPU_VAL         (IS2_AO_CPU_ENA + IS2_AL_CPU_ENA)
#define IS2_AL_CPU_VAL         3
#define IS2_AO_CPU_DIS         (IS2_AO_CPU_VAL + IS2_AL_CPU_VAL)
#define IS2_AL_CPU_DIS         1
#define IS2_AO_LRN_DIS         (IS2_AO_CPU_DIS + IS2_AL_CPU_DIS)
#define IS2_AL_LRN_DIS         1
#define IS2_AO_RT_DIS          (IS2_AO_LRN_DIS + IS2_AL_LRN_DIS)
#define IS2_AL_RT_DIS          1
#define IS2_AO_POLICE_ENA      (IS2_AO_RT_DIS + IS2_AL_RT_DIS)
#define IS2_AL_POLICE_ENA      1
#define IS2_AO_POLICE_VAL      (IS2_AO_POLICE_ENA + IS2_AL_POLICE_ENA)
#define IS2_AL_POLICE_VAL      5
#define IS2_AO_IGNORE_PL_CTRL  (IS2_AO_POLICE_VAL + IS2_AL_POLICE_VAL)
#define IS2_AL_IGNORE_PL_CTRL  1
#define IS2_AO_DLB_OFFSET      (IS2_AO_IGNORE_PL_CTRL + IS2_AL_IGNORE_PL_CTRL)
#define IS2_AL_DLB_OFFSET      3
#define IS2_AO_MASK_MODE       (IS2_AO_DLB_OFFSET + IS2_AL_DLB_OFFSET)
#define IS2_AL_MASK_MODE       3
#define IS2_AO_PORT_MASK       (IS2_AO_MASK_MODE + IS2_AL_MASK_MODE)
#define IS2_AL_PORT_MASK       55
#define IS2_AO_MIRROR_PROBE    (IS2_AO_PORT_MASK + IS2_AL_PORT_MASK)
#define IS2_AL_MIRROR_PROBE    2
#define IS2_AO_REW_PTP         (IS2_AO_MIRROR_PROBE + IS2_AL_MIRROR_PROBE)
#define IS2_AL_REW_PTP         2
#define IS2_AO_REW_DELAY       (IS2_AO_REW_PTP + IS2_AL_REW_PTP)
#define IS2_AL_REW_DELAY       2
#define IS2_AO_REW_SEQ_TS      (IS2_AO_REW_DELAY + IS2_AL_REW_DELAY)
#define IS2_AL_REW_SEQ_TS      2
#define IS2_AO_REW_DMAC        (IS2_AO_REW_SEQ_TS + IS2_AL_REW_SEQ_TS)
#define IS2_AL_REW_DMAC        1
#define IS2_AO_REW_SMAC        (IS2_AO_REW_DMAC + IS2_AL_REW_DMAC)
#define IS2_AL_REW_SMAC        1
#define IS2_AO_TTL_UPDATE      (IS2_AO_REW_SMAC + IS2_AL_REW_SMAC)
#define IS2_AL_TTL_UPDATE      1
#define IS2_AO_SAM_SEQ_ENA     (IS2_AO_TTL_UPDATE + IS2_AL_TTL_UPDATE)
#define IS2_AL_SAM_SEQ_ENA     1
#define IS2_AO_TCP_UDP_ENA     (IS2_AO_SAM_SEQ_ENA + IS2_AL_SAM_SEQ_ENA)
#define IS2_AL_TCP_UDP_ENA     1
#define IS2_AO_MATCH_ID        (IS2_AO_TCP_UDP_ENA + IS2_AL_TCP_UDP_ENA)
#define IS2_AL_MATCH_ID        16
#define IS2_AO_MATCH_MASK      (IS2_AO_MATCH_ID + IS2_AL_MATCH_ID)
#define IS2_AL_MATCH_MASK      16
#define IS2_AO_CNT_ID          (IS2_AO_MATCH_MASK + IS2_AL_MATCH_MASK)
#define IS2_AL_CNT_ID          12
#define IS2_AO_SWAP_MAC        (IS2_AO_CNT_ID + IS2_AL_CNT_ID)
#define IS2_AL_SWAP_MAC        1
#define IS2_AO_ACL_RT_MODE     (IS2_AO_SWAP_MAC + IS2_AL_SWAP_MAC)
#define IS2_AL_ACL_RT_MODE     4
#define IS2_AO_ACL_MAC         (IS2_AO_ACL_RT_MODE + IS2_AL_ACL_RT_MODE)
#define IS2_AL_ACL_MAC         48
#define IS2_AO_PTP_DOM         (IS2_AO_ACL_MAC + IS2_AL_ACL_MAC)
#define IS2_AL_PTP_DOM         2

/* IS2 action MASK_MODE */
#define IS2_MASK_MODE_OR_DSTMASK   0
#define IS2_MASK_MODE_AND_VLANMASK 1
#define IS2_MASK_MODE_REPLACE_PGID 2
#define IS2_MASK_MODE_REPLACE_ALL  3
#define IS2_MASK_MODE_REDIR_PGID   4
#define IS2_MASK_MODE_OR_PGID_MASK 5
#define IS2_MASK_MODE_VSTAX        6

/* IS2 action PTP modes */
#define IS2_REW_PTP_NONE 0
#define IS2_REW_PTP_ONE  1
#define IS2_REW_PTP_TWO  2
#define IS2_REW_PTP_TOD  3

/* IS2 action delay */
#define IS2_REW_DELAY_NONE 0
#define IS2_REW_DELAY_EGR  1
#define IS2_REW_DELAY_IGR1 2
#define IS2_REW_DELAY_IGR2 3

/* IS2 action sequence number and timestamp command */
#define IS2_REW_SEQ_TS_NONE     0
#define IS2_REW_SEQ_TS_INCR     1
#define IS2_REW_SEQ_TS_RSP_TS   2
#define IS2_REW_SEQ_TS_RSP_NONE 3

/* ================================================================= *
 *  VCAP LPM
 * ================================================================= */

/* LPM X1 SGL_IP4 key fields */
#define LPM_KO_X1_DST_FLAG 0
#define LPM_KL_X1_DST_FLAG 1
#define LPM_KO_X1_IP4_XIP  (LPM_KO_X1_DST_FLAG + LPM_KL_X1_DST_FLAG)
#define LPM_KL_X1_IP4_XIP  32

/* LPM X2 DBL_IP4 key fields */
#define LPM_KO_X2_IP4_SIP  0
#define LPM_KL_X2_IP4_SIP  32
#define LPM_KO_X2_IP4_DIP  (LPM_KO_X2_IP4_SIP + LPM_KL_X2_IP4_SIP)
#define LPM_KL_X2_IP4_DIP  32

/* LPM X4 SGL_IP6 key fields */
#define LPM_KO_X4_DST_FLAG 0
#define LPM_KL_X4_DST_FLAG 1
#define LPM_KO_X4_IP6_XIP  (LPM_KO_X4_DST_FLAG + LPM_KL_X4_DST_FLAG)
#define LPM_KL_X4_IP6_XIP  128

/* LPM X8 DBL_IP6 key fields */
#define LPM_KO_X8_IP6_SIP  0
#define LPM_KL_X8_IP6_SIP  128
#define LPM_KO_X8_IP6_DIP  (LPM_KO_X8_IP6_SIP + LPM_KL_X8_IP6_SIP)
#define LPM_KL_X8_IP6_DIP  128

/* LPM action types */
#define LPM_TYPE_ARP_PTR   0
#define LPM_TYPE_L3MC_PTR  1
#define LPM_TYPE_ARP_ENTRY 2

/* LPM common action field */
#define LPM_AO_TYPE 0
#define LPM_AL_TYPE 2

/* LPM ARP_PTR action fields */
#define LPM_AO_ARP_PTR_ARP_PTR   (LPM_AO_TYPE + LPM_AL_TYPE)
#if defined(VTSS_ARCH_SERVAL_T)
#define LPM_AL_ARP_PTR_ARP_PTR   8
#else
#define LPM_AL_ARP_PTR_ARP_PTR   11
#endif /* VTSS_ARCH_SERVAL_T */
#if defined(VTSS_ARCH_JAGUAR_2_B)
#define LPM_AO_ARP_PTR_ECMP_CNT  (LPM_AO_ARP_PTR_ARP_PTR + LPM_AL_ARP_PTR_ARP_PTR)
#else
#define LPM_AO_ARP_PTR_REMAP_ENA (LPM_AO_ARP_PTR_ARP_PTR + LPM_AL_ARP_PTR_ARP_PTR)
#define LPM_AL_ARP_PTR_REMAP_ENA 1
#define LPM_AO_ARP_PTR_ECMP_CNT  (LPM_AO_ARP_PTR_REMAP_ENA + LPM_AL_ARP_PTR_REMAP_ENA)
#endif /* VTSS_ARCH_JAGUAR_2_B */
#define LPM_AL_ARP_PTR_ECMP_CNT  4
#define LPM_AO_ARP_PTR_RGID      (LPM_AO_ARP_PTR_ECMP_CNT + LPM_AL_ARP_PTR_ECMP_CNT)
#define LPM_AL_ARP_PTR_RGID      3

/* LPM L3MC_PTR action fields */
#define LPM_AO_L3MC_PTR (LPM_AO_TYPE + LPM_AL_TYPE)
#if defined(VTSS_ARCH_SERVAL_T)
#define LPM_AL_L3MC_PTR 8
#else
#define LPM_AL_L3MC_PTR 10
#endif /* VTSS_ARCH_SERVAL_T */

/* LPM ARP_ENTRY action fields */
#define LPM_AO_ARP_ENTRY_MAC_MSB              (LPM_AO_TYPE + LPM_AL_TYPE)
#define LPM_AL_ARP_ENTRY_MAC_MSB              16
#define LPM_AO_ARP_ENTRY_MAC_LSB              (LPM_AO_ARP_ENTRY_MAC_MSB + LPM_AL_ARP_ENTRY_MAC_MSB)
#define LPM_AL_ARP_ENTRY_MAC_LSB              32
#define LPM_AO_ARP_ENTRY_VMID                 (LPM_AO_ARP_ENTRY_MAC_LSB + LPM_AL_ARP_ENTRY_MAC_LSB)
#if defined(VTSS_ARCH_SERVAL_T)
#define LPM_AL_ARP_ENTRY_VMID                 5
#else
#define LPM_AL_ARP_ENTRY_VMID                 7
#endif
#define LPM_AO_ARP_ENTRY_ZERO_DMAC_CPU_QUEUE  (LPM_AO_ARP_ENTRY_VMID + LPM_AL_ARP_ENTRY_VMID)
#define LPM_AL_ARP_ENTRY_ZERO_DMAC_CPU_QUEUE  3
#define LPM_AO_ARP_ENTRY_SIP_RPF_ENA          (LPM_AO_ARP_ENTRY_ZERO_DMAC_CPU_QUEUE + LPM_AL_ARP_ENTRY_ZERO_DMAC_CPU_QUEUE)
#define LPM_AL_ARP_ENTRY_SIP_RPF_ENA          1
#define LPM_AO_ARP_ENTRY_SECUR_MATCH_VMID_ENA (LPM_AO_ARP_ENTRY_SIP_RPF_ENA + LPM_AL_ARP_ENTRY_SIP_RPF_ENA)
#define LPM_AL_ARP_ENTRY_SECUR_MATCH_VMID_ENA 1
#define LPM_AO_ARP_ENTRY_SECUR_MATCH_MAC_ENA  (LPM_AO_ARP_ENTRY_SECUR_MATCH_VMID_ENA + LPM_AL_ARP_ENTRY_SECUR_MATCH_VMID_ENA)
#define LPM_AL_ARP_ENTRY_SECUR_MATCH_MAC_ENA  1
#define LPM_AO_ARP_ENTRY_ARP_ENA              (LPM_AO_ARP_ENTRY_SECUR_MATCH_MAC_ENA + LPM_AL_ARP_ENTRY_SECUR_MATCH_MAC_ENA)
#define LPM_AL_ARP_ENTRY_ARP_ENA              1

/* ================================================================= *
 *  VCAP ES0
 * ================================================================= */

/* ES0 key types */
#define ES0_TYPE_ISDX 0
#define ES0_TYPE_VID  1

/* ES0 key fields */
#define ES0_KO_TYPE        0
#define ES0_KL_TYPE        1
#define ES0_KO_EGR_PORT    (ES0_KO_TYPE + ES0_KL_TYPE)
#if defined(VTSS_ARCH_SERVAL_T)
#define ES0_KL_EGR_PORT    4
#else
#define ES0_KL_EGR_PORT    6
#endif /* VTSS_ARCH_SERVAL_T */
#define ES0_KO_PROT_ACT    (ES0_KO_EGR_PORT + ES0_KL_EGR_PORT)
#define ES0_KL_PROT_ACT    1
#define ES0_KO_VSI         (ES0_KO_PROT_ACT + ES0_KL_PROT_ACT)
#if defined(VTSS_ARCH_SERVAL_T)
#define ES0_KL_VSI         7
#else
#define ES0_KL_VSI         10
#endif /* VTSS_ARCH_SERVAL_T */
#define ES0_KO_COSID       (ES0_KO_VSI + ES0_KL_VSI)
#define ES0_KL_COSID       3
#define ES0_KO_COLOR       (ES0_KO_COSID + ES0_KL_COSID)
#define ES0_KL_COLOR       1
#define ES0_KO_SERVICE_FRM (ES0_KO_COLOR + ES0_KL_COLOR)
#define ES0_KL_SERVICE_FRM 1
#define ES0_KO_VID_ISDX    (ES0_KO_SERVICE_FRM + ES0_KL_SERVICE_FRM)
#define ES0_KL_VID_ISDX    12

/* ES0 PUSH_OUTER_TAG values */
#define ES0_ACT_PUSH_OT_PORT_ENA 0
#define ES0_ACT_PUSH_OT_ES0      1
#define ES0_ACT_PUSH_OT_PORT     2
#define ES0_ACT_PUSH_OT_NONE     3

/* ES0 TPID_SEL values */
#define ES0_ACT_TPID_SEL_C        0
#define ES0_ACT_TPID_SEL_S        1
#define ES0_ACT_TPID_SEL_CUSTOM_1 2
#define ES0_ACT_TPID_SEL_CUSTOM_2 3
#define ES0_ACT_TPID_SEL_CUSTOM_3 4
#define ES0_ACT_TPID_SEL_CLASS    5

/* ES0 PCP_SEL values */
#define ES0_ACT_PCP_SEL_CL_PCP  0
#define ES0_ACT_PCP_SEL_PCP_ES0 1
#define ES0_ACT_PCP_SEL_POPPED  3
#define ES0_ACT_PCP_SEL_MAP_0   4
#define ES0_ACT_PCP_SEL_MAP_1   5
#define ES0_ACT_PCP_SEL_MAP_2   6
#define ES0_ACT_PCP_SEL_MAP_3   7

/* ES0 DEI_SEL values */
#define ES0_ACT_DEI_SEL_CL_DEI  0
#define ES0_ACT_DEI_SEL_DEI_ES0 1
#define ES0_ACT_DEI_SEL_MAPPED  2
#define ES0_ACT_DEI_SEL_POPPED  3
#define ES0_ACT_DEI_SEL_MAP_0   4
#define ES0_ACT_DEI_SEL_MAP_1   5
#define ES0_ACT_DEI_SEL_MAP_2   6
#define ES0_ACT_DEI_SEL_MAP_3   7

/* ES0 DSCP_SEL values */
#define ES0_ACT_DSCP_SEL_PORT  0
#define ES0_ACT_DSCP_SEL_CL    1
#define ES0_ACT_DSCP_SEL_ES0   2
#define ES0_ACT_DSCP_SEL_RESV  3
#define ES0_ACT_DSCP_SEL_MAP_0 4
#define ES0_ACT_DSCP_SEL_MAP_1 5
#define ES0_ACT_DSCP_SEL_MAP_2 6
#define ES0_ACT_DSCP_SEL_MAP_3 7

/* ES0 LABEL_SEL values */
#define ES0_ACT_LABEL_SEL_ES0   0
#define ES0_ACT_LABEL_SEL_RESV1 1
#define ES0_ACT_LABEL_SEL_RESV2 2
#define ES0_ACT_LABEL_SEL_RESV3 3
#define ES0_ACT_LABEL_SEL_MAP_0 4
#define ES0_ACT_LABEL_SEL_MAP_1 5
#define ES0_ACT_LABEL_SEL_MAP_2 6
#define ES0_ACT_LABEL_SEL_MAP_3 7

/* ES0 TC_SEL values */
#define ES0_ACT_TC_SEL_CL    0
#define ES0_ACT_TC_SEL_ES0   1
#define ES0_ACT_TC_SEL_COSID 2
#define ES0_ACT_TC_SEL_RESV  3
#define ES0_ACT_TC_SEL_MAP_0 4
#define ES0_ACT_TC_SEL_MAP_1 5
#define ES0_ACT_TC_SEL_MAP_2 6
#define ES0_ACT_TC_SEL_MAP_3 7

/* ES0 action fields */
#define ES0_AO_PUSH_OUTER_TAG   0
#define ES0_AL_PUSH_OUTER_TAG   2
#define ES0_AO_PUSH_INNER_TAG   (ES0_AO_PUSH_OUTER_TAG + ES0_AL_PUSH_OUTER_TAG)
#define ES0_AL_PUSH_INNER_TAG   1
#define ES0_AO_TAG_A_TPID_SEL   (ES0_AO_PUSH_INNER_TAG + ES0_AL_PUSH_INNER_TAG)
#define ES0_AL_TAG_A_TPID_SEL   3
#define ES0_AO_TAG_A_VID_SEL    (ES0_AO_TAG_A_TPID_SEL + ES0_AL_TAG_A_TPID_SEL)
#define ES0_AL_TAG_A_VID_SEL    1
#define ES0_AO_TAG_A_PCP_SEL    (ES0_AO_TAG_A_VID_SEL + ES0_AL_TAG_A_VID_SEL)
#define ES0_AL_TAG_A_PCP_SEL    3
#define ES0_AO_TAG_A_DEI_SEL    (ES0_AO_TAG_A_PCP_SEL + ES0_AL_TAG_A_PCP_SEL)
#define ES0_AL_TAG_A_DEI_SEL    3
#define ES0_AO_TAG_B_TPID_SEL   (ES0_AO_TAG_A_DEI_SEL + ES0_AL_TAG_A_DEI_SEL)
#define ES0_AL_TAG_B_TPID_SEL   3
#define ES0_AO_TAG_B_VID_SEL    (ES0_AO_TAG_B_TPID_SEL + ES0_AL_TAG_B_TPID_SEL)
#define ES0_AL_TAG_B_VID_SEL    1
#define ES0_AO_TAG_B_PCP_SEL    (ES0_AO_TAG_B_VID_SEL + ES0_AL_TAG_B_VID_SEL)
#define ES0_AL_TAG_B_PCP_SEL    3
#define ES0_AO_TAG_B_DEI_SEL    (ES0_AO_TAG_B_PCP_SEL + ES0_AL_TAG_B_PCP_SEL)
#define ES0_AL_TAG_B_DEI_SEL    3
#define ES0_AO_TAG_C_TPID_SEL   (ES0_AO_TAG_B_DEI_SEL + ES0_AL_TAG_B_DEI_SEL)
#define ES0_AL_TAG_C_TPID_SEL   3
#define ES0_AO_TAG_C_PCP_SEL    (ES0_AO_TAG_C_TPID_SEL + ES0_AL_TAG_C_TPID_SEL)
#define ES0_AL_TAG_C_PCP_SEL    3
#define ES0_AO_TAG_C_DEI_SEL    (ES0_AO_TAG_C_PCP_SEL + ES0_AL_TAG_C_PCP_SEL)
#define ES0_AL_TAG_C_DEI_SEL    3
#define ES0_AO_VID_A_VAL        (ES0_AO_TAG_C_DEI_SEL + ES0_AL_TAG_C_DEI_SEL)
#define ES0_AL_VID_A_VAL        12
#define ES0_AO_PCP_A_VAL        (ES0_AO_VID_A_VAL + ES0_AL_VID_A_VAL)
#define ES0_AL_PCP_A_VAL        3
#define ES0_AO_DEI_A_VAL        (ES0_AO_PCP_A_VAL + ES0_AL_PCP_A_VAL)
#define ES0_AL_DEI_A_VAL        1
#define ES0_AO_VID_B_VAL        (ES0_AO_DEI_A_VAL + ES0_AL_DEI_A_VAL)
#define ES0_AL_VID_B_VAL        12
#define ES0_AO_PCP_B_VAL        (ES0_AO_VID_B_VAL + ES0_AL_VID_B_VAL)
#define ES0_AL_PCP_B_VAL        3
#define ES0_AO_DEI_B_VAL        (ES0_AO_PCP_B_VAL + ES0_AL_PCP_B_VAL)
#define ES0_AL_DEI_B_VAL        1
#define ES0_AO_VID_C_VAL        (ES0_AO_DEI_B_VAL + ES0_AL_DEI_B_VAL)
#define ES0_AL_VID_C_VAL        12
#define ES0_AO_PCP_C_VAL        (ES0_AO_VID_C_VAL + ES0_AL_VID_C_VAL)
#define ES0_AL_PCP_C_VAL        3
#define ES0_AO_DEI_C_VAL        (ES0_AO_PCP_C_VAL + ES0_AL_PCP_C_VAL)
#define ES0_AL_DEI_C_VAL        1
#define ES0_AO_POP_VAL          (ES0_AO_DEI_C_VAL + ES0_AL_DEI_C_VAL)
#define ES0_AL_POP_VAL          1
#define ES0_AO_UNTAG_VID_ENA    (ES0_AO_POP_VAL + ES0_AL_POP_VAL)
#define ES0_AL_UNTAG_VID_ENA    1
#define ES0_AO_PUSH_TAG_C       (ES0_AO_UNTAG_VID_ENA + ES0_AL_UNTAG_VID_ENA)
#define ES0_AL_PUSH_TAG_C       2
#define ES0_AO_TAG_C_VID_SEL    (ES0_AO_PUSH_TAG_C + ES0_AL_PUSH_TAG_C)
#define ES0_AL_TAG_C_VID_SEL    1
#define ES0_AO_DSCP_SEL         (ES0_AO_TAG_C_VID_SEL + ES0_AL_TAG_C_VID_SEL)
#define ES0_AL_DSCP_SEL         3
#define ES0_AO_DSCP_VAL         (ES0_AO_DSCP_SEL + ES0_AL_DSCP_SEL)
#define ES0_AL_DSCP_VAL         6
#if defined(VTSS_ARCH_JAGUAR_2_B)
#define ES0_AO_LABEL_SEL        (ES0_AO_DSCP_VAL + ES0_AL_DSCP_VAL)
#else
#define ES0_AO_PROT_SEL         (ES0_AO_DSCP_VAL + ES0_AL_DSCP_VAL)
#define ES0_AL_PROT_SEL         2
#define ES0_AO_LABEL_SEL        (ES0_AO_PROT_SEL + ES0_AL_PROT_SEL)
#endif /* VTSS_ARCH_JAGUAR_2_B */
#define ES0_AL_LABEL_SEL        3
#define ES0_AO_TC_SEL           (ES0_AO_LABEL_SEL + ES0_AL_LABEL_SEL)
#define ES0_AL_TC_SEL           3
#define ES0_AO_SBIT_SEL         (ES0_AO_TC_SEL + ES0_AL_TC_SEL)
#define ES0_AL_SBIT_SEL         1
#define ES0_AO_TTL_SEL          (ES0_AO_SBIT_SEL + ES0_AL_SBIT_SEL)
#define ES0_AL_TTL_SEL          1
#define ES0_AO_MPLS_LABEL       (ES0_AO_TTL_SEL + ES0_AL_TTL_SEL)
#define ES0_AL_MPLS_LABEL       20
#define ES0_AO_TC_VAL           (ES0_AO_MPLS_LABEL + ES0_AL_MPLS_LABEL)
#define ES0_AL_TC_VAL           3
#define ES0_AO_SBIT_VAL         (ES0_AO_TC_VAL + ES0_AL_TC_VAL)
#define ES0_AL_SBIT_VAL         1
#define ES0_AO_TTL_VAL          (ES0_AO_SBIT_VAL + ES0_AL_SBIT_VAL)
#define ES0_AL_TTL_VAL          8
#define ES0_AO_CW_DIS           (ES0_AO_TTL_VAL + ES0_AL_TTL_VAL)
#define ES0_AL_CW_DIS           1
#define ES0_AO_ENCAP_ID         (ES0_AO_CW_DIS + ES0_AL_CW_DIS)
#if defined(VTSS_ARCH_SERVAL_T)
#define ES0_AL_ENCAP_ID         7
#else
#define ES0_AL_ENCAP_ID         10
#endif /* VTSS_ARCH_SERVAL_T */
#if defined(VTSS_ARCH_JAGUAR_2_B)
#define ES0_AO_POP_CNT          (ES0_AO_ENCAP_ID + ES0_AL_ENCAP_ID)
#else
#define ES0_AO_ENCAP_ID_P       (ES0_AO_ENCAP_ID + ES0_AL_ENCAP_ID)
#define ES0_AL_ENCAP_ID_P       ES0_AL_ENCAP_ID
#define ES0_AO_POP_CNT          (ES0_AO_ENCAP_ID_P + ES0_AL_ENCAP_ID_P)
#endif /* VTSS_ARCH_JAGUAR_2_B */
#define ES0_AL_POP_CNT          5
#define ES0_AO_ESDX_BASE        (ES0_AO_POP_CNT + ES0_AL_POP_CNT)
#if defined(VTSS_ARCH_SERVAL_T)
#define ES0_AL_ESDX_BASE        10
#else
#define ES0_AL_ESDX_BASE        13
#endif /* VTSS_ARCH_SERVAL_T */
#if defined(VTSS_ARCH_JAGUAR_2_B)
#define ES0_AO_ESDX_COSID_OFFS  (ES0_AO_ESDX_BASE + ES0_AL_ESDX_BASE)
#else
#define ES0_AO_ESDX_BASE_P      (ES0_AO_ESDX_BASE + ES0_AL_ESDX_BASE)
#define ES0_AL_ESDX_BASE_P      ES0_AL_ESDX_BASE
#define ES0_AO_ESDX_COSID_OFFS  (ES0_AO_ESDX_BASE_P + ES0_AL_ESDX_BASE_P)
#endif /* VTSS_ARCH_JAGUAR_2_B */
#define ES0_AL_ESDX_COSID_OFFS  24
#define ES0_AO_MAP_0_IDX        (ES0_AO_ESDX_COSID_OFFS + ES0_AL_ESDX_COSID_OFFS)
#define ES0_AL_MAP_0_IDX        JR2_CLM_MAP_LEN
#define ES0_AO_MAP_1_IDX        (ES0_AO_MAP_0_IDX + ES0_AL_MAP_0_IDX)
#define ES0_AL_MAP_1_IDX        JR2_CLM_MAP_LEN
#define ES0_AO_MAP_2_IDX        (ES0_AO_MAP_1_IDX + ES0_AL_MAP_1_IDX)
#define ES0_AL_MAP_2_IDX        JR2_CLM_MAP_LEN
#define ES0_AO_MAP_3_IDX        (ES0_AO_MAP_2_IDX + ES0_AL_MAP_2_IDX)
#define ES0_AL_MAP_3_IDX        JR2_CLM_MAP_LEN
#define ES0_AO_MAP_0_KEY        (ES0_AO_MAP_3_IDX + ES0_AL_MAP_3_IDX)
#define ES0_AL_MAP_0_KEY        4
#define ES0_AO_MAP_1_KEY        (ES0_AO_MAP_0_KEY + ES0_AL_MAP_0_KEY)
#define ES0_AL_MAP_1_KEY        4
#define ES0_AO_MAP_2_KEY        (ES0_AO_MAP_1_KEY + ES0_AL_MAP_1_KEY)
#define ES0_AL_MAP_2_KEY        4
#define ES0_AO_MAP_3_KEY        (ES0_AO_MAP_2_KEY + ES0_AL_MAP_2_KEY)
#define ES0_AL_MAP_3_KEY        4
#define ES0_AO_OAM_MEP_ENA      (ES0_AO_MAP_3_KEY + ES0_AL_MAP_3_KEY)
#define ES0_AL_OAM_MEP_ENA      1
#define ES0_AO_OAM_MEP_VAL      (ES0_AO_OAM_MEP_ENA + ES0_AL_OAM_MEP_ENA)
#if defined(VTSS_ARCH_SERVAL_T)
#define ES0_AL_OAM_MEP_VAL      8
#else
#define ES0_AL_OAM_MEP_VAL      10
#endif /* VTSS_ARCH_SERVAL_T */
#if defined(VTSS_ARCH_JAGUAR_2_B)
#define ES0_AO_OAM_LM_COLOR_SEL (ES0_AO_OAM_MEP_VAL + ES0_AL_OAM_MEP_VAL)
#else
#define ES0_AO_OAM_MEP_VAL_P    (ES0_AO_OAM_MEP_VAL + ES0_AL_OAM_MEP_VAL)
#define ES0_AL_OAM_MEP_VAL_P    ES0_AL_OAM_MEP_VAL
#define ES0_AO_OAM_LM_COLOR_SEL (ES0_AO_OAM_MEP_VAL_P + ES0_AL_OAM_MEP_VAL_P)
#endif /* VTSS_ARCH_JAGUAR_2_B */
#define ES0_AL_OAM_LM_COLOR_SEL 2
#define ES0_AO_INDEP_MEL_ENA    (ES0_AO_OAM_LM_COLOR_SEL + ES0_AL_OAM_LM_COLOR_SEL)
#define ES0_AL_INDEP_MEL_ENA    1
#define ES0_AO_MIP_IDX          (ES0_AO_INDEP_MEL_ENA + ES0_AL_INDEP_MEL_ENA)
#if defined(VTSS_ARCH_SERVAL_T)
#define ES0_AL_MIP_IDX          7
#else
#define ES0_AL_MIP_IDX          10
#endif /* VTSS_ARCH_SERVAL_T */
#define ES0_AO_FWD_SEL          (ES0_AO_MIP_IDX + ES0_AL_MIP_IDX)
#define ES0_AL_FWD_SEL          2
#define ES0_AO_CPU_QUEUE        (ES0_AO_FWD_SEL + ES0_AL_FWD_SEL)
#define ES0_AL_CPU_QUEUE        3
#define ES0_AO_PL_PT            (ES0_AO_CPU_QUEUE + ES0_AL_CPU_QUEUE)
#define ES0_AL_PL_PT            2
#if defined(VTSS_ARCH_JAGUAR_2_B)
#define ES0_AO_LOOP_ENA         (ES0_AO_PL_PT + ES0_AL_PL_PT)
#else
#define ES0_AO_PL_ACT           (ES0_AO_PL_PT + ES0_AL_PL_PT)
#define ES0_AL_PL_ACT           1
#define ES0_AO_SWAP_MAC_ENA     (ES0_AO_PL_ACT + ES0_AL_PL_ACT)
#define ES0_AL_SWAP_MAC_ENA     1
#define ES0_AO_LOOP_ENA         (ES0_AO_SWAP_MAC_ENA + ES0_AL_SWAP_MAC_ENA)
#endif /* VTSS_ARCH_JAGUAR_2_B */
#define ES0_AL_LOOP_ENA         1

#endif /* _JAGUAR2_REG_H */

