// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

:sectnums:
== Media Redundancy Protocol (MRP) example

Command 'example init mrp' will add a MRP instance in a interconnected node with Manager ring role
and Client interconnect role. +
There will be tree ports - the primary, the secondary and the interconnection port,
that can be given as parameter.

Command 'example help mrp' will show: +
MRP Ring Role +
MRP Interconnect Role +
MRP Test frame Unicast MAC +
MRP Test Interval +
MRP Test Monitor Count +
MRP InTest Interval +
MRP InTest Monitor Count +

Command 'example run command' can be used to the following: +
MRP status show. +
MRP event status show. +
CPU RX frame print. +
CPU TX Test frame. +

The Test Loss Of Continuity detection and clear can be tested by sending MRP_Test frame on the
ring ports an do status show commands.

The transmitted Test PDU update can be seen by activating CPU TX Test. The sequence number is incremented.
The ring status is Open and the transaction number is one.

Copying of protocol PDU can be tested by sending in LinkDown on ring port and InTopologyChange
on interconnected port and activate CPU RX frame.

Correct forwarding of different MRP frame can be observed by sending the frames against the ports.
